Repository kyma-project/kyma-environment-broker, pull requests merged in 2023-10, with the labels that each got.

#76 Restore AvS in case of failing operation
  internal/process/upgrade_cluster/initialisation.go
  internal/process/upgrade_kyma/initialisation.go
Labels: size/M, lgtm

#82 Revert "Make region mandatory in the KEB schema (#42)"
  internal/appinfo/runtime_info.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/services.go
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema.json
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  internal/provider/gcp_provider.go
  internal/provider/openstack_provider.go
Labels: size/L, lgtm

#83 Process compass runtime ID
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  internal/model.go
  internal/process/provisioning/apply_kyma_step.go
  internal/process/provisioning/apply_kyma_step_test.go
Labels: size/L, lgtm

#96 Worker pool for provisioning/deprovisioning/update configurable
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/process/staged_manager.go
  internal/process/staged_manager_test.go
Labels: size/M, lgtm

#100 Bump keb
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: lgtm, size/XS

#99 Extend AvS config model to support Tags
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/avs/config.go
  internal/avs/external_eval_assistant.go
  internal/avs/internal_eval_assistant.go
  internal/avs/model.go
  internal/avs/model_configurator.go
  internal/avs/model_test.go
  internal/process/deprovisioning/avs_evaluations_test.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/provisioning/external_eval_step_test.go
  internal/process/provisioning/internal_eval_test.go
  internal/process/provisioning/internal_eval_updater.go
  internal/process/provisioning/internal_eval_updater_test.go
  internal/process/provisioning/runtime_tags_step.go
  internal/process/provisioning/runtime_tags_step_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: lgtm, size/XL

#102 Removal of Test Config
  resources/keb/templates/rename-config.yaml
Labels: lgtm, size/XS

#107 Fix Kyma Environments Cleanup CronJob
  utils/kyma-environments-cleanup-job/apply.sh
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#111 Don't provide GardenerShootName AvS tag
  internal/avs/config.go
  internal/avs/external_eval_assistant.go
  internal/avs/internal_eval_assistant.go
  internal/avs/model_test.go
  internal/process/provisioning/internal_eval_test.go
Labels: size/S, lgtm

#112 Revert the change
  files/swagger/index.html
Labels: lgtm, size/XS

#108 Fix Subaccount Cleanup Job
  internal/cis/account_cleanup.go
  internal/cis/account_cleanup_test.go
  internal/cis/automock/CisClient.go
  internal/cis/client.go
  internal/cis/client_test.go
  internal/cis/client_ver_1.go
  internal/cis/client_ver_1_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#113 Moved First KEB Resource
  docs/03-03-runtime-operations.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/templates/_helpers.tpl
  resources/kcp/values.yaml
  resources/keb/files/dashboard.json
  resources/keb/templates/_helpers.tpl
  resources/keb/templates/dashboard.yaml
  resources/keb/templates/refactoring-config.yaml
  resources/keb/values.yaml
Labels: area/documentation, lgtm, size/XL

#119 Escaped Invalid Characters for Failing Build
  resources/keb/values.yaml
Labels: lgtm, size/XS

#95 Update operation docs
  Dockerfile.keb
  Makefile
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/update.go
  cmd/broker/upgrade_cluster.go
  cmd/broker/upgrade_kyma.go
  docs/03-03-runtime-operations.md
Labels: area/documentation, lgtm, size/XXL

#122 Resources Sync
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/values.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm

#118 Fix runtime dto Status.State for deprovision type
  internal/runtime/converter.go
Labels: lgtm, size/XS

#123 Region labels for kyma resource fix
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma_test.go
  internal/model.go
  internal/orchestration/manager/upgrade_cluster.go
  internal/orchestration/manager/upgrade_kyma.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/steps/lifecycle_manager.go
Labels: size/L, kind/bug, lgtm

#105 Add region to skr tests
  testing/e2e/skr/keb-endpoints-test/index.js
  testing/e2e/skr/kyma-environment-broker/client.js
Labels: size/S, lgtm

#127 Add missing platformRegion to SKR tests
  testing/e2e/skr/kyma-environment-broker/client.js
Labels: lgtm, size/XS

#90 Make region always mandatory in the KEB schema
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma_test.go
  internal/appinfo/runtime_info.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/aws-schema-additional-params-region-required.json
  internal/broker/testdata/aws-schema-eu-region-required.json
  internal/broker/testdata/aws-schema-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params-region-required.json
  internal/broker/testdata/azure-lite-schema-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-region-required.json
  internal/broker/testdata/azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-schema-additional-params-region-required.json
  internal/broker/testdata/azure-schema-eu-region-required.json
  internal/broker/testdata/azure-schema-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params-region-required.json
  internal/broker/testdata/free-aws-schema-eu-region-required.json
  internal/broker/testdata/free-aws-schema-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params-region-required.json
  internal/broker/testdata/free-azure-schema-eu-region-required.json
  internal/broker/testdata/free-azure-schema-region-required.json
  internal/broker/testdata/gcp-schema-additional-params-region-required.json
  internal/broker/testdata/gcp-schema-region-required.json
  internal/broker/testdata/openstack-schema-additional-params-region-required.json
  internal/broker/testdata/openstack-schema-region-required.json
Labels: lgtm, size/XXL

#128 Logs and events enhancements
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  internal/process/deprovisioning/check_cluster_deregistration.go
  internal/process/deprovisioning/check_runtime_removal_step.go
  internal/process/deprovisioning/check_runtime_removal_step_test.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/operation_manager.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/staged_manager.go
Labels: size/M, lgtm
