Repository kyma-project/kyma-environment-broker, pull requests merged in 2023-09, with the labels that each got.

#28 Update README.md
  README.md
Labels: area/documentation

#33 Fix BTPOperator_Cleanup step
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
Labels: size/L, lgtm

#34 Added Dependabot from the Old Repo
  .github/dependabot.yml
Labels: size/S, lgtm

#43 Freemium networking params
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema.json
Labels: size/L, lgtm

#51 Update service description doc
  docs/03-01-service-description.md
Labels: size/S, area/documentation, lgtm

#42 Make region mandatory in the KEB schema
  internal/appinfo/runtime_info.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/services.go
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema.json
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  internal/provider/gcp_provider.go
  internal/provider/openstack_provider.go
Labels: size/L, lgtm

#49 Networking docs
  docs/03-19-custom-networking-configuration.md
  internal/broker/instance_create.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema.json
Labels: size/L, area/documentation, lgtm

#63 Initial Chart for KEB Chart Reorganisation
  resources/keb/.helmignore
  resources/keb/Chart.yaml
  resources/keb/templates/rename-config.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm

#66 Fix/trial cleanup job
  cmd/broker/broker_suite_test.go
  cmd/broker/update_test.go
  cmd/trialcleanup/main.go
  internal/broker/client.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/suspension/handler.go
Labels: lgtm, size/XL

#75 Add Markdown link check to the repository
  .github/workflows/markdown-link-check.yaml
  .mlc.config.json
  CODE_OF_CONDUCT.md
  docs/03-02-runtime-components.md
  docs/03-03-runtime-operations.md
  docs/contributor/04-10-workflows.md
  internal/third_party/machinebox/graphql/README.md
Labels: size/M, area/documentation, lgtm

#65 Fix AvS problems with optimistic locking
  internal/avs/delegator.go
  internal/process/deprovisioning/avs_evaluations.go
  internal/process/staged_manager.go
Labels: size/M, lgtm

#77 Migrated Test CM
  resources/keb/templates/refactoring-config.yaml
Labels: lgtm, size/XS

#78 Add a security policy (SECURITY.md)
  SECURITY.md
Labels: area/documentation, lgtm, size/XS
