Repository kyma-project/kyma-environment-broker, pull requests merged in 2023-12, with the labels that each got.

#240 Set tracing for label validator script
  scripts/label_validator.sh
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#235 Replace release label validation script
  .github/workflows/create-release.yaml
  scripts/python/release_label_validator.py
  scripts/python/requirements.txt
Labels: size/M, lgtm, kind/enhancement, cla: yes

#219 Add Rest of KEB Resources
  .github/workflows/run-keb-chart-tests-reusable.yaml
  docs/contributor/01-20-swagger.md
  docs/contributor/06-30-subaccount-cleanup-cronjob.md
  docs/user/02-10-broker-endpoints.md
  resources/keb/templates/NOTES.txt
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/profiler-pvc.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/service-monitor.yaml
  resources/keb/templates/service.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/templates/virtualservice.yaml
  resources/keb/values.yaml
Labels: size/S, kind/feature, area/documentation, lgtm, cla: yes

#246 Template Correction
  resources/keb/templates/virtualservice.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#247 Add release tag to release workflow name
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#254 Document new workflows
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#255 Document release workflow
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/contributor/04-20-release.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#239 Returning Bad Request (400) for update when validation fails
  cmd/broker/update_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#261 Image Bump
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#263 Move Migrator Job
  resources/kcp/templates/migrator-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/values.yaml
Labels: size/L, kind/cleanup, lgtm, kind/enhancement, cla: yes

#266 Image Bump
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#264 Remove deprecated components list provider and kyma-operator dependency
  cmd/broker/broker_suite_test.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/additional-runtime-components.yaml
  cmd/broker/testdata/kyma-components.yaml
  cmd/broker/update_test.go
  go.mod
  go.sum
  internal/process/upgrade_kyma/automock/component_list_provider.go
  internal/runtime/components_provider.go
  internal/runtime/provider.go
  internal/runtime/provider_fake.go
  internal/runtime/provider_test.go
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#262 Adjust the docs to the new content guidelines
  README.md
  docs/contributor/01-10-authorization.md
  docs/contributor/01-20-swagger.md
  docs/contributor/02-10-runtime-components.md
  docs/contributor/02-20-runtime-overrides.md
  docs/contributor/02-30-kyma-versions.md
  docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md
  docs/contributor/02-60-orchestrate-kyma-upgrade.md
  docs/contributor/02-70-orchestration-status.md
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/contributor/03-20-eu-access.md
  docs/contributor/03-30-trial-expiration.md
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
  docs/contributor/05-10-e2e_tests.md
  docs/contributor/06-40-trial-cleanup-cronjob.md
  docs/user/01-10-architecture.md
  docs/user/01-20-target-architecture.md
  docs/user/02-10-broker-endpoints.md
  docs/user/03-10-service-description.md
  docs/user/03-20-runtime-operations.md
  docs/user/04-10-custom-oidc-configuration.md
  docs/user/04-20-custom-administrators.md
  docs/user/04-30-custom-networking-configuration.md
  docs/user/05-10-provisioning-kyma-environment.md
  docs/user/05-20-deprovisioning-kyma-environment.md
  docs/user/05-30-operation-status.md
  docs/user/05-40-instance-details.md
  docs/user/05-50-configure-list-of-modules.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#268 Corrected Migrator Image Version
  resources/keb/values.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#269 Update broker-configuration-for-given-version-and-plan doc
  docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#234 Trial suspension e2e test
  .gitignore
  testing/e2e/skr/.gitignore
  testing/e2e/skr/Makefile
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/package.json
  testing/e2e/skr/skr-test/test.js
  testing/e2e/skr/trial-suspension-test/helpers.js
  testing/e2e/skr/trial-suspension-test/test.js
Labels: size/L, lgtm, kind/enhancement, cla: yes

#271 Adjust operation duration metrics
  internal/metrics/operation_duration.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#272 Fix make for skr-trial-suspension
  testing/e2e/skr/Makefile
Labels: kind/bug, lgtm, size/XS, cla: yes

#274 Fix Kyma Environments Cleanup Job lifetime
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#275 Fix Trial Suspension E2E test false positive
  testing/e2e/skr/package.json
  testing/e2e/skr/trial-suspension-test/test.js
Labels: size/S, kind/bug, lgtm, cla: yes

#276 Add direct support for argo sync waves for the migrator job
  resources/keb/templates/migrator-job.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#277 Fix remove gardenercluster steps
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/delete_gardener_cluster.go
Labels: size/S, kind/bug, lgtm, area/control-plane, cla: yes

#278 Fix GardenerCluster deletion, bump keb image
  resources/keb/values.yaml
Labels: kind/bug, lgtm, size/XS, area/control-plane, cla: yes

#281 Add trial expiration endpoint to KEB endpoints test
  testing/e2e/skr/keb-endpoints-test/index.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#267 EDP utility
  .gitignore
  internal/edp/client.go
  utils/edp-registrator/README.md
  utils/edp-registrator/checksubaccounts.py
  utils/edp-registrator/env.dev.template
  utils/edp-registrator/env.prod.template
  utils/edp-registrator/env.stage.template
  utils/edp-registrator/main.go
  utils/edp-registrator/operations_report.py
Labels: size/L, area/documentation, lgtm, area/control-plane, kind/enhancement, cla: yes

#283 Bump KEB images to 1.0.0
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#287 Moved Migration Scripts
  .gitignore
  internal/cis/e2e/tests_utils.go
  internal/storage/tests_utils.go
  resources/keb/files/migrations/202001221020_initialize_schema.down.sql
  resources/keb/files/migrations/202001221020_initialize_schema.up.sql
  resources/keb/files/migrations/202001231030_add_datetimes_to_instances.down.sql
  resources/keb/files/migrations/202001231030_add_datetimes_to_instances.up.sql
  resources/keb/files/migrations/202002121000_add_operations.down.sql
  resources/keb/files/migrations/202002121000_add_operations.up.sql
  resources/keb/files/migrations/202002201000_add_lms_tenants.down.sql
  resources/keb/files/migrations/202002201000_add_lms_tenants.up.sql
  resources/keb/files/migrations/202004032115_add_additonal_runtime_info.down.sql
  resources/keb/files/migrations/202004032115_add_additonal_runtime_info.up.sql
  resources/keb/files/migrations/202004201217_fix-delated-typo.down.sql
  resources/keb/files/migrations/202004201217_fix-delated-typo.up.sql
  resources/keb/files/migrations/202008241000_add_orchestrations.down.sql
  resources/keb/files/migrations/202008241000_add_orchestrations.up.sql
  resources/keb/files/migrations/202009171000_add_runtime_states.down.sql
  resources/keb/files/migrations/202009171000_add_runtime_states.up.sql
  resources/keb/files/migrations/202009230900_add_orchestration_id_to_operation.down.sql
  resources/keb/files/migrations/202009230900_add_orchestration_id_to_operation.up.sql
  resources/keb/files/migrations/202010131417_add_provider_region_to_instance.down.sql
  resources/keb/files/migrations/202010131417_add_provider_region_to_instance.up.sql
  resources/keb/files/migrations/202012150900_add_provisioning_parameters_to_operation.down.sql
  resources/keb/files/migrations/202012150900_add_provisioning_parameters_to_operation.up.sql
  resources/keb/files/migrations/202012151612_add_version_to_instance.down.sql
  resources/keb/files/migrations/202012151612_add_version_to_instance.up.sql
  resources/keb/files/migrations/202101131044_add_not_null_provisioning_parameters.down.sql
  resources/keb/files/migrations/202101131044_add_not_null_provisioning_parameters.up.sql
  resources/keb/files/migrations/202101131045_add_cls_instances.down.sql
  resources/keb/files/migrations/202101131045_add_cls_instances.up.sql
  resources/keb/files/migrations/202103011331_orchestration_type.down.sql
  resources/keb/files/migrations/202103011331_orchestration_type.up.sql
  resources/keb/files/migrations/202103251452_add_indexes.down.sql
  resources/keb/files/migrations/202103251452_add_indexes.up.sql
  resources/keb/files/migrations/202104010820_add_finished_stages.down.sql
  resources/keb/files/migrations/202104010820_add_finished_stages.up.sql
  resources/keb/files/migrations/202105191350_add_instance_provider.down.sql
  resources/keb/files/migrations/202105191350_add_instance_provider.up.sql
  resources/keb/files/migrations/202141251610_add_reconciler_input.down.sql
  resources/keb/files/migrations/202141251610_add_reconciler_input.up.sql
  resources/keb/files/migrations/202143071502_add_instance_subscriptionGAID.down.sql
  resources/keb/files/migrations/202143071502_add_instance_subscriptionGAID.up.sql
  resources/keb/files/migrations/202207281547_add_expired_at.down.sql
  resources/keb/files/migrations/202207281547_add_expired_at.up.sql
  resources/keb/files/migrations/202209211320_events.down.sql
  resources/keb/files/migrations/202209211320_events.up.sql
  resources/keb/files/migrations/202210121025_drop_events_references.down.sql
  resources/keb/files/migrations/202210121025_drop_events_references.up.sql
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#289 Corrected Invalid Placement of Migration Scripts
  internal/cis/e2e/tests_utils.go
  internal/storage/tests_utils.go
  resources/keb/migrations/202001221020_initialize_schema.down.sql
  resources/keb/migrations/202001221020_initialize_schema.up.sql
  resources/keb/migrations/202001231030_add_datetimes_to_instances.down.sql
  resources/keb/migrations/202001231030_add_datetimes_to_instances.up.sql
  resources/keb/migrations/202002121000_add_operations.down.sql
  resources/keb/migrations/202002121000_add_operations.up.sql
  resources/keb/migrations/202002201000_add_lms_tenants.down.sql
  resources/keb/migrations/202002201000_add_lms_tenants.up.sql
  resources/keb/migrations/202004032115_add_additonal_runtime_info.down.sql
  resources/keb/migrations/202004032115_add_additonal_runtime_info.up.sql
  resources/keb/migrations/202004201217_fix-delated-typo.down.sql
  resources/keb/migrations/202004201217_fix-delated-typo.up.sql
  resources/keb/migrations/202008241000_add_orchestrations.down.sql
  resources/keb/migrations/202008241000_add_orchestrations.up.sql
  resources/keb/migrations/202009171000_add_runtime_states.down.sql
  resources/keb/migrations/202009171000_add_runtime_states.up.sql
  resources/keb/migrations/202009230900_add_orchestration_id_to_operation.down.sql
  resources/keb/migrations/202009230900_add_orchestration_id_to_operation.up.sql
  resources/keb/migrations/202010131417_add_provider_region_to_instance.down.sql
  resources/keb/migrations/202010131417_add_provider_region_to_instance.up.sql
  resources/keb/migrations/202012150900_add_provisioning_parameters_to_operation.down.sql
  resources/keb/migrations/202012150900_add_provisioning_parameters_to_operation.up.sql
  resources/keb/migrations/202012151612_add_version_to_instance.down.sql
  resources/keb/migrations/202012151612_add_version_to_instance.up.sql
  resources/keb/migrations/202101131044_add_not_null_provisioning_parameters.down.sql
  resources/keb/migrations/202101131044_add_not_null_provisioning_parameters.up.sql
  resources/keb/migrations/202101131045_add_cls_instances.down.sql
  resources/keb/migrations/202101131045_add_cls_instances.up.sql
  resources/keb/migrations/202103011331_orchestration_type.down.sql
  resources/keb/migrations/202103011331_orchestration_type.up.sql
  resources/keb/migrations/202103251452_add_indexes.down.sql
  resources/keb/migrations/202103251452_add_indexes.up.sql
  resources/keb/migrations/202104010820_add_finished_stages.down.sql
  resources/keb/migrations/202104010820_add_finished_stages.up.sql
  resources/keb/migrations/202105191350_add_instance_provider.down.sql
  resources/keb/migrations/202105191350_add_instance_provider.up.sql
  resources/keb/migrations/202141251610_add_reconciler_input.down.sql
  resources/keb/migrations/202141251610_add_reconciler_input.up.sql
  resources/keb/migrations/202143071502_add_instance_subscriptionGAID.down.sql
  resources/keb/migrations/202143071502_add_instance_subscriptionGAID.up.sql
  resources/keb/migrations/202207281547_add_expired_at.down.sql
  resources/keb/migrations/202207281547_add_expired_at.up.sql
  resources/keb/migrations/202209211320_events.down.sql
  resources/keb/migrations/202209211320_events.up.sql
  resources/keb/migrations/202210121025_drop_events_references.down.sql
  resources/keb/migrations/202210121025_drop_events_references.up.sql
Labels: kind/bug, lgtm, size/XS, cla: yes

#296 Adding more logs for update handler
  internal/suspension/handler.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#300 Ensure deprovisioning succeeded in all E2E SKR tests
  testing/e2e/skr/skr-aws-upgrade-integration/index.js
  testing/e2e/skr/skr-networking-test/index.js
  testing/e2e/skr/skr-test/deprovision-skr.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#299 Runtime Reconciler with kubeconfig provider
  internal/btpmanager/credentials/manager.go
  internal/kubeconfig/provider.go
  internal/kubeconfig/provider_test.go
  internal/process/deprovisioning/btp_operator_cleanup.go
Labels: size/L, lgtm, area/control-plane, kind/enhancement, cla: yes

#279 Removing openstack term and replacing with sap-converged-cloud
  cmd/broker/broker_suite_test.go
  cmd/broker/update_test.go
  internal/dto.go
  internal/process/input/builder.go
  internal/process/input/input.go
  internal/storage/driver/postsql/instance_test.go
  resources/keb/files/catalog.yaml
  resources/keb/files/swagger.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#303 bump to 1.0.1
  resources/keb/values.yaml
Labels: size/S, lgtm, area/control-plane, kind/enhancement, cla: yes

#286 Remove provisioning skip option in skr tests
  testing/e2e/skr/skr-aws-upgrade-integration/index.js
  testing/e2e/skr/skr-networking-test/.env.template
  testing/e2e/skr/skr-networking-test/index.js
  testing/e2e/skr/skr-test/.env.template
  testing/e2e/skr/skr-test/deprovision-skr.js
  testing/e2e/skr/skr-test/provision-skr.js
  testing/e2e/skr/skr-test/provision/deprovision-skr.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/skr-test/test.js
  testing/e2e/skr/trial-suspension-test/test.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#307 Decreasing poller timeout in the broker test suite
  cmd/broker/broker_suite_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#310 Separate envtest bin directory for every test
  setup-envtest.sh
Labels: lgtm, kind/enhancement, cla: yes

#270 Block EDP deregistration if other instances exists with the same subaccount
  cmd/broker/deprovisioning.go
  internal/edp/client_fake.go
  internal/process/deprovisioning/edp_deregistration.go
  internal/process/deprovisioning/edp_deregistration_test.go
Labels: size/L, lgtm, area/control-plane, kind/enhancement, cla: yes

#306 Use kcfg provider in runtimereconciler
  internal/btpmanager/credentials/manager.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#244 PollImmediate in update endpoint
  internal/broker/instance_update.go
Labels: lgtm, size/XS, area/control-plane, kind/enhancement, cla: yes

#312 Bump KEB images to 1.0.2
  resources/keb/values.yaml
Labels: lgtm, kind/enhancement, cla: yes

#309 Documentation update for sap-converged-cloud
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/user/03-10-service-description.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#315 Makefile Variable Correction
  scripts/generic_make_go.mk
Labels: kind/bug, lgtm, size/XS, cla: yes
