Repository kyma-project/kyma-environment-broker, pull requests merged in 2023-11, with the labels that each got.

#137 fixing provider tag value
  internal/avs/external_eval_assistant.go
  internal/avs/internal_eval_assistant.go
  internal/avs/model.go
Labels: size/S, lgtm

#140 Control Plane Sync
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/values.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm

#139 disable external AVS evaulation
  cmd/broker/main.go
  internal/avs/config.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS

#109 Add mandatory region parameter to docs
  docs/03-01-service-description.md
  docs/03-08-kyma-versions.md
  docs/03-12-custom-oidc-configuration.md
  docs/03-13-custom-administrators.md
  docs/03-19-custom-networking-configuration.md
  docs/08-01-provisioning-kyma-environment.md
Labels: size/S, area/documentation, lgtm

#129 Add a flag to expose schema with region required
  cmd/broker/suite_test.go
  internal/broker/broker.go
  internal/broker/services.go
  internal/broker/services_test.go
Labels: size/L, lgtm

#145 Fix environments cleanup job
  internal/environmentscleanup/service.go
Labels: lgtm, size/XS

#146 Bump kyma-environments-cleanup-job to v20231107-1e28423d
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: lgtm, size/XS

#148 Release workflow part 1
  .github/release.yml
  .github/workflows/create-release.yaml
  Makefile
  internal/storage/tests_utils.go
  scripts/check_artifacts_existence.sh
  scripts/create_draft_release.sh
  scripts/label_validator.sh
  scripts/publish_release.sh
Labels: size/L, lgtm

#150 docs update
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
Labels: area/documentation, lgtm, size/XS

#155 Keb Sync
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm

#164 Fix repo in the release workflow
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS

#163 Change kyma-environments-cleanup-job image registry
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: lgtm, size/XS

#165 Fix link to KEB docs in swagger
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
Labels: lgtm, size/XS

#168 Documentation update - users
  docs/user/05-30-operation-status.md
  docs/user/05-40-instance-details.md
Labels: size/M, area/documentation, lgtm

#169 update modules support
  cmd/broker/provisioning_test.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params-region-required.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu-region-required.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema-region-required.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema-region-required.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params-region-required.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu-region-required.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema-region-required.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/azure-trial-schema-additional-params.json
  internal/broker/testdata/azure-trial-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu-region-required.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema-region-required.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu-region-required.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema-region-required.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params-region-required.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema-region-required.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params-region-required.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema-region-required.json
  internal/broker/testdata/openstack-schema.json
  internal/broker/testdata/own-cluster-schema-additional-params.json
  internal/broker/testdata/own-cluster-schema.json
  internal/process/provisioning/override_kyma_modules.go
  internal/process/provisioning/override_kyma_modules_test.go
  internal/testdata/kymatemplate/kyma-with-keda-and-btp-operator-all-params-set.yaml
  internal/testdata/kymatemplate/kyma-with-keda-and-btp-operator-only-name.yaml
Labels: lgtm, size/XXL

#142 Add Trial expiration endpoint
  cmd/broker/main.go
  docs/contributor/03-30-trial-expiration.md
  internal/expiration/handler.go
  internal/expiration/handler_test.go
  internal/process/fake.go
Labels: size/L, area/documentation, lgtm

#177 Handle rate limiting in Subaccount Cleanup CronJob
  internal/cis/client.go
  resources/keb/values.yaml
Labels: lgtm, size/XS

#178 Modules improvements
  cmd/broker/main.go
  common/storage/storage.go
  internal/broker/instance_create.go
  internal/dto.go
  internal/process/input/input.go
  internal/process/provisioning/override_kyma_modules.go
  internal/process/provisioning/override_kyma_modules_test.go
Labels: size/M, lgtm

#141 Moved Config Resources and Missing Prune
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/keb/Chart.yaml
  resources/keb/files/catalog.yaml
  resources/keb/files/gardener-dashboard.json
  resources/keb/files/swagger.yaml
  resources/keb/templates/_helpers.tpl
  resources/keb/templates/authorization-policy.yaml
  resources/keb/templates/dashboard.yaml
  resources/keb/templates/gardener-dashboard.yaml
  resources/keb/templates/keb-migrations.yaml
  resources/keb/templates/policy.yaml
  resources/keb/templates/rbac.yaml
  resources/keb/templates/request-authentication.yaml
  resources/keb/templates/secrets.yaml
  resources/keb/templates/swagger.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm

#182 Gardener Cluster step
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
Labels: size/L, lgtm

#183 Instance Label Correction
  resources/keb/templates/authorization-policy.yaml
  resources/keb/templates/policy.yaml
  resources/keb/templates/request-authentication.yaml
Labels: lgtm, size/XS

#176 Create or update sec. scanning config file in the release workflow
  .github/workflows/create-release.yaml
  scripts/await_pr_merge.sh
  scripts/check_artifacts_existence.sh
  scripts/create_scan_config.sh
  scripts/create_sec_scanner_bump_pr.sh
Labels: size/L, lgtm

#189 Add commit status check to release workflow
  .github/workflows/create-release.yaml
Labels: size/L, lgtm

#190 Bump actions/checkout to v4
  .github/workflows/create-release.yaml
  .github/workflows/run-eslint.yaml
Labels: size/S, lgtm

#191 Restore needed release job
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS

#197 Check gardener cluster
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
Labels: size/L, lgtm, area/control-plane, kind/enhancement

#199 KEB Sync
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm

#201 infrastructure manager feature flag
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, area/control-plane, kind/enhancement

#203 Security scanners adjustments in the release workflow
  .github/workflows/create-release.yaml
  scripts/create_scan_config.sh
Labels: lgtm, size/XS

#202 Update runtime components document
  docs/assets/runtime-components.svg
  docs/contributor/02-10-runtime-components.md
Labels: size/S, area/documentation, lgtm

#206 Update schema
  internal/broker/plans_schema.go
  internal/broker/testdata/aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws-schema-additional-params-region-required.json
  internal/broker/testdata/aws-schema-additional-params.json
  internal/broker/testdata/aws-schema-eu-region-required.json
  internal/broker/testdata/aws-schema-eu.json
  internal/broker/testdata/aws-schema-region-required.json
  internal/broker/testdata/aws-schema.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure-lite-schema-additional-params-region-required.json
  internal/broker/testdata/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure-lite-schema-eu-region-required.json
  internal/broker/testdata/azure-lite-schema-eu.json
  internal/broker/testdata/azure-lite-schema-region-required.json
  internal/broker/testdata/azure-lite-schema.json
  internal/broker/testdata/azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure-schema-additional-params-region-required.json
  internal/broker/testdata/azure-schema-additional-params.json
  internal/broker/testdata/azure-schema-eu-region-required.json
  internal/broker/testdata/azure-schema-eu.json
  internal/broker/testdata/azure-schema-region-required.json
  internal/broker/testdata/azure-schema.json
  internal/broker/testdata/azure-trial-schema-additional-params.json
  internal/broker/testdata/azure-trial-schema.json
  internal/broker/testdata/free-aws-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/free-aws-schema-additional-params-region-required.json
  internal/broker/testdata/free-aws-schema-additional-params.json
  internal/broker/testdata/free-aws-schema-eu-region-required.json
  internal/broker/testdata/free-aws-schema-eu.json
  internal/broker/testdata/free-aws-schema-region-required.json
  internal/broker/testdata/free-aws-schema.json
  internal/broker/testdata/free-azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/free-azure-schema-additional-params-region-required.json
  internal/broker/testdata/free-azure-schema-additional-params.json
  internal/broker/testdata/free-azure-schema-eu-region-required.json
  internal/broker/testdata/free-azure-schema-eu.json
  internal/broker/testdata/free-azure-schema-region-required.json
  internal/broker/testdata/free-azure-schema.json
  internal/broker/testdata/gcp-schema-additional-params-region-required.json
  internal/broker/testdata/gcp-schema-additional-params.json
  internal/broker/testdata/gcp-schema-region-required.json
  internal/broker/testdata/gcp-schema.json
  internal/broker/testdata/openstack-schema-additional-params-region-required.json
  internal/broker/testdata/openstack-schema-additional-params.json
  internal/broker/testdata/openstack-schema-region-required.json
  internal/broker/testdata/openstack-schema.json
  internal/broker/testdata/own-cluster-schema-additional-params.json
  internal/broker/testdata/own-cluster-schema.json
Labels: size/L, lgtm

#208 fix btp mgr creds tests
  .gitignore
  internal/btpmanager/credentials/manager_test.go
Labels: size/S, lgtm

#210 Add label validation
  .github/workflows/create-release.yaml
  .github/workflows/label-validator.yml
  scripts/label_validator.sh
Labels: size/M, lgtm

#209 fix btp mgr creds tests
  internal/btpmanager/credentials/manager_test.go
Labels: size/M, lgtm, kind/enhancement

#212 GardenerCluster RBAC for KEB
  resources/keb/templates/rbac.yaml
Labels: kind/feature, lgtm, size/XS, area/control-plane

#215 update images
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement

#216 Improve label validator
  scripts/label_validator.sh
Labels: size/S, lgtm, kind/enhancement

#193 Simple Time Measurements
  cmd/broker/broker_suite_test.go
  internal/broker/poller.go
Labels: size/S, lgtm, kind/enhancement

#220 Increase poller timeout in unit tests
  cmd/broker/broker_suite_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#221 Keb Sync 4
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
Labels: kind/feature, lgtm, size/XS, cla: yes

#218 Add unit test workflow
  .github/workflows/create-release.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-unit-tests.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#225 Bump KEBto v20231129-21180bef
  resources/keb/values.yaml
Labels: kind/feature, lgtm, area/control-plane, cla: yes

#167 Documentation update - contributors
  docs/contributor/02-60-orchestrate-kyma-upgrade.md
  docs/contributor/06-30-subaccount-cleanup-cronjob.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#226 Add keb helm chart tests
  .github/workflows/run-keb-chart-tests-reusable.yaml
  .github/workflows/run-keb-chart-tests.yaml
  scripts/testing/get-latest-k3s-releases.sh
  scripts/testing/k3s-setup.sh
  scripts/testing/yaml/registries.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#227 Add keb chart validation to release
  .github/workflows/create-release.yaml
  .github/workflows/run-keb-chart-tests-reusable.yaml
  .github/workflows/run-keb-chart-tests.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes
