Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-08, with the labels that each got.

#971 Fix typo in release without prow workflow
  .github/workflows/create-release-without-prow.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#974 KIM Integration - default list of KIM driven plans
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#973 KIM Integration - RuntimeResourceName added to instance details
  cmd/broker/provisioning.go
  internal/model.go
  internal/process/provisioning/create_resource_names_step.go
  internal/process/provisioning/create_resource_names_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#976 KIM Integration - AWS Freemium and Azure Lite
  internal/process/provisioning/create_runtime_resource_step.go
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure.go
  internal/provider/azure_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#977 Administrators added to parameters for SKR creation
  testing/e2e/skr/kyma-environment-broker/client.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#970 KIM Integration - AWS trial unit tests
  internal/provider/aws_provider.go
  internal/provider/aws_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#979 Run helm install test in create release without prow workflow
  .github/workflows/create-release-without-prow.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  scripts/testing/yaml/postgres/postgres-configmap.yaml
  scripts/testing/yaml/postgres/postgres-deployment.yaml
  scripts/testing/yaml/postgres/postgres-secret.yaml
  scripts/testing/yaml/postgres/postgres-service.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#972 KIM Integration - Driven by KIM only predicate
  internal/kim/config.go
  internal/kim/config_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#982 KIM Integration Check Runtime resource step
  cmd/broker/provisioning.go
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#983 Provide KIM integration for freemium
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/azure.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#980 Add KEB deployment test configuration
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  Dockerfile.keb
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#987 Move image builders to one workflow file
  .github/workflows/pull-build-keb-images.yaml
  .github/workflows/pull-keb-archiver-job-build-ga.yaml
  .github/workflows/pull-keb-build-ga.yaml
  .github/workflows/pull-keb-cleanup-build-ga.yaml
  .github/workflows/pull-keb-deprovision-retrigger-job-build-ga.yaml
  .github/workflows/pull-keb-expirator-build-ga.yaml
  .github/workflows/pull-keb-runtime-reconciler-job-build-ga.yaml
  .github/workflows/pull-keb-subaccount-cleanup-job-build-ga.yaml
  .github/workflows/pull-keb-subaccount-sync-build-ga.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#988 KIM Integration - Default runtime administrator handling
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#993 KIM Integration - EnforceSeedLocation supported
  internal/process/provisioning/create_runtime_resource_step.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#994 Deprovisioning runtime resource
  cmd/broker/deprovisioning.go
  cmd/broker/deprovisioning_suite_test.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step_test.go
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/deprovisioning/delete_runtime_resource_step_test.go
  internal/test_utils.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#998 Use internal docker registry in k3s-setup
  scripts/testing/k3s-setup.sh
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#991 Prepare helm install test to be run on PR
  .github/workflows/create-release-without-prow.yaml
  .github/workflows/create-release.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  .github/workflows/run-keb-chart-tests-reusable.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/values.yaml
  scripts/bump_keb_chart.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#999 KIM Integration - `preview` plan on Azure
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1002 Start helm install tests on PR
  .github/workflows/pull-build-and-test-images.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#990 KIM Integration - SAP Converged Cloud provider
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/sap-converged-cloud.go
  internal/provider/sap-converged-cloud_provider.go
  internal/provider/sap-converged-cloud_provider_test.go
  internal/provider/zones.go
  internal/provider/zones_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1003 Pass PR number to helm install test
  .github/workflows/pull-build-and-test-images.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1000 KIM Integration - Testing networking for non-default parameters
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1007 Use only GitHub Actions image builder on PR
  .github/workflows/pull-build-and-test-images.yaml
  .github/workflows/run-keb-chart-tests.yaml
  docs/contributor/04-10-workflows.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1009 Revert golang to 1.22.5
  Dockerfile.job
  Dockerfile.keb
  Dockerfile.runtimereconciler
  Dockerfile.subaccountsync
Labels: kind/bug, lgtm, size/XS, cla: yes

#997 KIM Integration - dedicated timeout for CheckRuntimeResource step
  cmd/broker/provisioning.go
  internal/process/input/input.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1010 KIM Integration - Azure Lite added to supported plans
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1011 Bump golang images to 1.22.6
  Dockerfile.job
  Dockerfile.keb
  Dockerfile.runtimereconciler
  Dockerfile.subaccountsync
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1012 Switch to GitHub Actions image builder in release workflow
  .github/workflows/create-release-without-prow.yaml
  .github/workflows/create-release.yaml
  .github/workflows/run-keb-chart-tests-reusable.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#1015 Use postgres from internal docker registry
  cmd/broker/storage_test.go
  internal/docker_helper.go
  internal/storage/driver/postsql/postsql_test.go
  internal/subaccountsync/state_reconciler_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1018 KIM Integration - conditionally handling GardenerCluster
  cmd/broker/deprovisioning.go
  cmd/broker/provisioning.go
  internal/kim/config.go
  internal/kim/config_test.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
  internal/process/steps/runtime_resource.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1006 KIM Integration - `preview` plan on AWS
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1019 Kim with OIDC
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  go.mod
  go.sum
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1022 KCP CLI - deprovisioned instances fetch limit
  internal/storage/postsql/read.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1023 Update release and workflow documentation
  docs/assets/release.drawio
  docs/assets/release.drawio.svg
  docs/assets/release.svg
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#1024 KIM Integration - Tests refactor
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1026 KIM Integration - Volume support and worker group name
  internal/process/provisioning/create_runtime_resource_step.go
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure.go
  internal/provider/azure_test.go
  internal/provider/gcp.go
  internal/provider/model.go
  internal/provider/sap-converged-cloud.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1031 add provider label to Kyma CR
  internal/process/provisioning/apply_kyma_step_test.go
  internal/process/steps/lifecycle_manager.go
  internal/process/steps/lifecycle_manager_kubeconfig_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1028 Limit deprovisioned instances
  common/runtime/client.go
  common/runtime/client_test.go
  internal/storage/postsql/read.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1033 KIM Integration - correctly skipped steps for KIM only driven plans
  cmd/broker/provisioning.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1037 KIM Integration - Check runtime step run conditionally
  cmd/broker/provisioning.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/provisioning/check_runtime_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1040 KIM Integration - managed by provisioner label not set for KIM only
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1047 Gi in volumesize
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1045 KIM Integration - disabling kubeconfig deletion
  cmd/broker/deprovisioning.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1029 KIM Integration - egress setting based on license
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1049 KIM Integration - adjustments to current KIM behavior
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1062 Script for sync EDP and KCP (subaccounts)
  utils/edp-registrator/check_all_sids.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1065 Extend KCP rt output
  internal/runtime/handler.go
  internal/storage/postsql/read.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1056 Use Assured Workloads for GCP KSA SKRs - cf-sa30
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  common/hyperscaler/account_pool_test.go
  common/hyperscaler/account_provider.go
  common/hyperscaler/account_provider_test.go
  common/hyperscaler/hyperscaler_type.go
  common/hyperscaler/hyperscaler_type_test.go
  common/hyperscaler/shared_pool_test.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/deprovisioning/release_subscription_step_test.go
  internal/process/provisioning/resolve_creds.go
  internal/process/provisioning/resolve_creds_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1060 Extend Hyperscaler Account Pool documentation
  docs/contributor/03-10-hyperscaler-account-pool.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#1071 Add VaultStaticSecret support to the keb
  resources/keb/templates/_helpers.tpl
  resources/keb/templates/secrets.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/vss.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1044 Configuration is set only for plans (no longer per version and plan)
  docs/README.md
  docs/contributor/02-40-broker-configuration-for-given-plan.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1075 Update KEB helm install test to use secrets
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1066 China update
  resources/cn/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1057 KIM Integration - Skipping `Remove_Runtime` step conditionally
  cmd/broker/deprovisioning.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/deprovisioning/remove_runtime_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1061 KIM Integration - instances on `runtimes` endpoint decorated with Runtime CR
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  common/runtime/model.go
  internal/broker/broker.go
  internal/broker/kim_config.go
  internal/broker/kim_config_test.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/deprovisioning/remove_runtime_test.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/provisioning/check_runtime_step_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/provisioning/get_kubeconfig_step.go
  internal/process/provisioning/get_kubeconfig_test.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
  internal/process/steps/lifecycle_manager.go
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
  internal/provisioner/fake_client.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes
