Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-10, with the labels that each got.

#1225 Fix KEB install test on release
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1222 Adjust workflow skipping
  .github/workflows/build-e2e-provisioning-test-image.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pull-build-images.yaml
  .github/workflows/run-govulncheck.yaml
  .github/workflows/run-keb-chart-install-tests.yaml
  .github/workflows/run-verify.yaml
  docs/contributor/04-10-workflows.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#1228 Add missing workflow skip check for bot
  .github/workflows/pr-checks.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1231 Default region for KSA
  internal/provider/gcp.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1237 Add kubeconfig to credentials in SKR test
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/XS, kind/enhancement, cla: yes

#1236 Pin markdown link check version
  .github/workflows/markdown-link-check.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1232 KIM Integration - safe checks and test cases
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure_test.go
  internal/provider/gcp.go
  internal/provider/gcp_test.go
  internal/provider/sap-converged-cloud.go
  internal/provider/sap-converged-cloud_test.go
  internal/provider/zones.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#1240 Add configurable timeout for update operation
  cmd/broker/suite_test.go
  cmd/broker/update.go
  internal/process/input/input.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1234 KIM Integration - `Purpose` default configurable per landscape
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure.go
  internal/provider/azure_test.go
  internal/provider/gcp.go
  internal/provider/gcp_test.go
  internal/provider/model.go
  internal/provider/provider_values.go
  internal/provider/sap-converged-cloud.go
  internal/provider/sap-converged-cloud_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1246 AVS variables removed from KEB deployment
  cmd/broker/main.go
  resources/keb/templates/deployment.yaml
Labels: kind/enhancement

#1244 Integration Test for Gardener Kubeconfig Expiration
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
  testing/e2e/skr/skr-binding-test/index.js
  testing/e2e/skr/utils/index.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1248 globaccounts tool
  .github/workflows/create-release.yaml
  .github/workflows/pull-build-images.yaml
  Dockerfile.globalaccounts
  cmd/globalaccounts/main.go
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
  resources/keb/templates/globalaccounts.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1250 adjust pipelines for globalaccouts tool
  .github/workflows/create-release.yaml
  scripts/create_scan_config.sh
Labels: size/XS, kind/enhancement, cla: yes

#1251 adjust pipelines for globalaccount tools
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1252 Rename token_request to service_account in bindings
  docs/user/05-60-kyma-bindings.md
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bindings/bindings_manager.go
  requests/bindings/create-tokenrequest.http
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1256 Fix chart for globalaccount tool
  resources/keb/templates/globalaccounts.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1255 Add max and min expiration time
  docs/user/05-60-kyma-bindings.md
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1213 Initial DB Table
  internal/fixture/fixture.go
  internal/model.go
  internal/storage/dbmodel/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/driver/postsql/binding_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/init.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  internal/storage/storage.go
  resources/keb/migrations/202410030001_add_kyma_bindings.down.sql
  resources/keb/migrations/202410030001_add_kyma_bindings.up.sql
  resources/keb/migrations/202410030002_add_binding_indexes.down.sql
  resources/keb/migrations/202410030002_add_binding_indexes.up.sql
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1258 fix globalaccount tool chart
  resources/keb/templates/globalaccounts.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1243 Removal of Duplicated Accepts Incomplete & token_request Default Behaviour
  docs/user/05-60-kyma-bindings.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1263 Binding db in memory
  internal/storage/driver/memory/binding.go
  internal/storage/storage.go
Labels: size/M, kind/enhancement

#1264 Fix chart for globalaccount tool
  resources/keb/templates/globalaccounts.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1266 Fix chart for globalaccount tools
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1268 Fix chart for globalaccounts tool
  resources/keb/templates/globalaccounts.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1272 Expired instance - final docs update
  docs/contributor/03-30-trial-and-free-expiration.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1273 Fix chart for globalaccounts tool
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1233 Incorporate Schema Migrator
  Dockerfile.schemamigrator
  cmd/accountcleanup/main.go
  cmd/deprovisionretrigger/main.go
  cmd/expirator/main.go
  cmd/schemamigrator/main.go
  cmd/schemamigrator/main_test.go
  cmd/trialcleanup/main.go
  common/setup/builder.go
  docs/user/03-10-service-description.md
  go.mod
  go.sum
  internal/schemamigrator/cleaner/halt.go
  internal/schemamigrator/mocks/FileSystem.go
  internal/schemamigrator/mocks/MyFileInfo.go
  scripts/schemamigrator/create_migration.sh
  scripts/schemamigrator/multiple-postgresql-databases.sh
  scripts/schemamigrator/validate.sh
Labels: area/documentation, lgtm, size/XXL, kind/enhancement, cla: yes

#1261 Add binding expiration tests to SKR tests
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/M, kind/enhancement, cla: yes

#1249 GET and DELETE in Kyma Binding SKR test
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/L, kind/enhancement, cla: yes

#1277 Globalaccounts tool fix namespace
  internal/globalaccounts/globalaccounts.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1280 Change wait for images steps in KEB chart install test
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  scripts/wait_for_images.sh
Labels: size/M, kind/enhancement, cla: yes

#1281 Globalaccounts tool improvements
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
  resources/keb/templates/globalaccounts.yaml
Labels: size/M, kind/enhancement, cla: yes

#1284 Globalaccounts tool improvements
  internal/globalaccounts/globalaccounts.go
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1275 Bindings on runtime endpoint
  cmd/broker/binding_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  common/runtime/model.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/dbmodel/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/read.go
Labels: size/L, kind/enhancement, cla: yes

#1286 Global accounts tool
  resources/keb/templates/globalaccounts.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1289 vso correction (avs trial values now stored in vault for every env)
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1278 Add request logging for service bindings
  cmd/broker/main.go
  internal/middleware/request_logging.go
Labels: size/M, kind/enhancement, cla: yes

#1293 Globalaccounts tool - fix config
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
Labels: size/XS, kind/enhancement, cla: yes

#1295 Global account tool - fix config
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
Labels: size/S, kind/enhancement, cla: yes

#1299 Add Schema Migrator to dev images build GA
  .github/workflows/pull-build-images.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1300 Global accouns tool improvements
  internal/broker/instance_update.go
  internal/broker/labeling.go
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
  internal/k8s/metadata.go
  resources/keb/templates/globalaccounts.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1303 Params for runtimes endpoint - bindings
  common/runtime/model.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1307 Binding params for kcp cli
  common/runtime/client.go
Labels: size/XS, kind/enhancement, cla: yes

#1306 Add expires_at to bindings table in db
  internal/broker/bind_create.go
  internal/broker/bindings/bindings_manager.go
  internal/broker/bindings/gardener_request_bindingmanager.go
  internal/fixture/fixture.go
  internal/model.go
  internal/runtime/handler.go
  internal/storage/dbmodel/binding.go
  internal/storage/postsql/write.go
  resources/keb/migrations/202410110732_add_binding_expires_at.down.sql
  resources/keb/migrations/202410110732_add_binding_expires_at.up.sql
Labels: size/M, kind/enhancement, cla: yes

#1292 Schema Migrator CI
  .github/workflows/create-release.yaml
  .github/workflows/pull-validate-schema-migrator.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  docs/contributor/04-10-workflows.md
  docs/contributor/07-30-schema-migrator.md
  internal/schemamigrator/cleaner/halt.go
  resources/keb/templates/migrator-job.yaml
  resources/keb/values.yaml
  scripts/create_scan_config.sh
  scripts/schemamigrator/create_migration.sh
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1311 Add `created_by` to binding
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/fixture/fixture.go
  internal/model.go
  internal/storage/dbmodel/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/driver/postsql/binding_test.go
  internal/storage/postsql/write.go
  resources/keb/migrations/202410111300_add_created_by_to_binding.down.sql
  resources/keb/migrations/202410111300_add_created_by_to_binding.up.sql
Labels: size/L, kind/enhancement, cla: yes

#1291 Limit bindings to max 10
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/storage/driver/postsql/binding.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1315 Free Cleanup CronJob doc
  docs/contributor/06-10-keb-cronjobs.md
  docs/contributor/06-40-trial-cleanup-cronjob.md
  docs/contributor/06-40-trial-free-cleanup-cronjobs.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1305 Initial Bindings Delete API Implementation
  cmd/broker/bind_create_test.go
  cmd/broker/main.go
  internal/broker/bind_delete.go
  internal/storage/driver/memory/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/driver/postsql/binding_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/write.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1283 Add SKR test for creating more than 10 bindings
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1320 With-bindings usage flag for info/runtimes endpoint
  internal/runtime/handler.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1312 SB - remove support for Gardener `adminkubeconfig`
  cmd/broker/bind_create_test.go
  cmd/broker/main.go
  docs/user/05-60-kyma-bindings.md
  internal/broker/bind_create.go
  internal/broker/bindings/gardener_request_bindingmanager.go
  internal/fixture/fixture.go
  internal/model.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/dbmodel/binding.go
  internal/storage/postsql/write.go
  requests/bindings/create-tokenrequest.http
  resources/keb/migrations/202410150814_remove_binding_type.down.sql
  resources/keb/migrations/202410150814_remove_binding_type.up.sql
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1322 Missing Bindings' Resources Removal
  cmd/broker/bind_create_test.go
  cmd/broker/main.go
  internal/broker/bind_delete.go
  internal/broker/bindings/bindings_manager.go
Labels: size/L, kind/bug, lgtm, cla: yes

#1319 Remove Gardener kubeconfig binding SKR tests
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1317 Globalaccountstool v5
  internal/globalaccounts/globalaccounts.go
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1333 Global Accounts Migration Tools fixes
  internal/globalaccounts/globalaccounts.go
Labels: size/XS, kind/enhancement, cla: yes

#1330 Fix delete request in SKR bindings test
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/XS, kind/enhancement, cla: yes

#1338 Revert "Bump jsonpath-plus and @kubernetes/client-node in /testing/e2…
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#1336 Fix report msg in global account tool
  internal/globalaccounts/globalaccounts.go
Labels: size/XS, kind/enhancement, cla: yes

#1325 SB - renaming auxiliary functions in tests
  cmd/broker/bind_create_test.go
Labels: size/M, kind/enhancement, cla: yes

#1327 SB - more concise test cases
  cmd/broker/bind_create_test.go
Labels: size/M, kind/enhancement, cla: yes

#1340 Global accounts tools - dry run changes
  internal/globalaccounts/config.go
  internal/globalaccounts/globalaccounts.go
  resources/keb/values.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1343 Return expires_at field in Binding Metadata
  cmd/broker/bind_create_test.go
  go.mod
  go.sum
  internal/broker/bind_create.go
Labels: size/S, kind/enhancement, cla: yes

#1344 Fix missing newline in ga tool raport
  internal/globalaccounts/globalaccounts.go
Labels: size/S, kind/enhancement, cla: yes

#1332 Fix binding e2e test
  cmd/broker/binding_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/broker/bindings/bindings_manager.go
  internal/kubeconfig/provider.go
Labels: size/M, kind/enhancement, cla: yes

#1351 Change binding `created_by` format
  cmd/broker/bind_create_test.go
  internal/broker/bind_create.go
Labels: size/S, kind/enhancement, cla: yes

#1356 Move binding createdBy tests
  cmd/broker/bind_create_test.go
  internal/broker/bind_create_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1360 Handle incorrect binding parameters
  cmd/broker/binding_test.go
  internal/broker/bind_create.go
Labels: size/S, kind/enhancement, cla: yes

#1329 Add more linting to Markdown files
  docs/README.md
  docs/contributor/01-10-authorization.md
  docs/contributor/01-20-swagger.md
  docs/contributor/02-30-keb-configuration.md
  docs/contributor/02-40-broker-configuration-for-given-plan.md
  docs/contributor/02-50-orchestration.md
  docs/contributor/02-70-orchestration-status.md
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/contributor/03-20-eu-access.md
  docs/contributor/03-30-trial-and-free-expiration.md
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
  docs/contributor/05-10-e2e_tests.md
  docs/contributor/06-10-keb-cronjobs.md
  docs/contributor/06-20-environments-cleanup-cronjob.md
  docs/contributor/06-30-subaccount-cleanup-cronjob.md
  docs/contributor/06-40-trial-free-cleanup-cronjobs.md
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
  docs/contributor/07-10-runtime-reconciler.md
  docs/contributor/07-20-subaccount-sync.md
  docs/contributor/07-30-schema-migrator.md
  docs/user/01-10-architecture.md
  docs/user/01-20-target-architecture.md
  docs/user/02-10-broker-endpoints.md
  docs/user/03-10-service-description.md
  docs/user/03-20-runtime-operations.md
  docs/user/04-10-custom-oidc-configuration.md
  docs/user/04-20-custom-administrators.md
  docs/user/04-30-custom-networking-configuration.md
  docs/user/05-10-provisioning-kyma-environment.md
  docs/user/05-20-deprovisioning-kyma-environment.md
  docs/user/05-30-operation-status.md
  docs/user/05-40-instance-details.md
  docs/user/05-50-configure-list-of-modules.md
  docs/user/05-60-kyma-bindings.md
  docs/user/06-10-metrics.md
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#1363 Provide valid binding expiration time in cmd/broker tests
  cmd/broker/binding_test.go
  internal/kubeconfig/provider.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1345 Adjust HTTP codes for bindings PUT
  cmd/broker/binding_test.go
  cmd/broker/suite_test.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/storage/dberr/errors.go
  internal/storage/dberr/errors_test.go
  internal/storage/driver/postsql/binding.go
Labels: size/L, kind/enhancement, cla: yes

#1367 globalaccounts fixes
  internal/globalaccounts/globalaccounts.go
Labels: size/S, kind/enhancement

#1369 Add binding SKR test for response codes
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/M, kind/enhancement, cla: yes

#1375 Change message when max binding reached
  cmd/broker/bind_create_test.go
  internal/broker/bind_create.go
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/XS, kind/enhancement, cla: yes

#1374 Change incorrect parameters response message
  cmd/broker/binding_test.go
  internal/broker/bind_create.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1362 SB: Make sure Service Bindings do not do not block Service Instance deletion
  cmd/broker/bind_create_test.go
  cmd/broker/binding_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_delete.go
  internal/broker/bind_get.go
  internal/broker/bind_get_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1373 Check CRD existence in Labeler
  internal/broker/instance_update_test.go
  internal/broker/labeler.go
  internal/globalaccounts/globalaccounts.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1376 Update swagger with bindings
  resources/keb/files/swagger.yaml
Labels: size/L, kind/enhancement, cla: yes

#1382 SB: documentation updated
  docs/user/05-60-kyma-bindings.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#1384 SB: Create long term binding in SKR tests
  testing/e2e/skr/skr-binding-test/index.js
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1366 Corrected Binding Insert Order
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/storage/driver/memory/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/write.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1365 Expired Service Bindings cleanup job
  .github/workflows/create-release.yaml
  .github/workflows/pull-build-images.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  cmd/servicebindingcleanup/main.go
  docs/contributor/06-10-keb-cronjobs.md
  docs/contributor/06-70-service-binding-cleanup-cronjob.md
  internal/broker/client.go
  internal/servicebindingcleanup/service.go
  internal/servicebindingcleanup/service_test.go
  internal/storage/driver/memory/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  resources/keb/templates/service-binding-cleanup-job.yaml
  resources/keb/values.yaml
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#1385 Improve Service Binding Cleanup job
  internal/broker/client.go
  internal/servicebindingcleanup/service.go
  internal/servicebindingcleanup/service_test.go
  internal/storage/driver/postsql/binding.go
  internal/storage/postsql/read.go
Labels: size/L, kind/enhancement, cla: yes

#1386 Swagger update - bindings added
  resources/keb/files/swagger.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1387 Extend bindings logs
  internal/broker/bind_create.go
  internal/broker/bind_delete.go
  internal/broker/bind_get.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1371 Create e2e provisioning API test
  docs/contributor/05-10-e2e_tests.md
  testing/e2e/skr/Makefile
  testing/e2e/skr/provisioning-service-test/.env.template
  testing/e2e/skr/provisioning-service-test/cmd/provisioning_service_test.go
  testing/e2e/skr/provisioning-service-test/cmd/suite_test.go
  testing/e2e/skr/provisioning-service-test/go.mod
  testing/e2e/skr/provisioning-service-test/go.sum
  testing/e2e/skr/provisioning-service-test/internal/model.go
  testing/e2e/skr/provisioning-service-test/internal/provisioning_client.go
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#1392 Rename bidnings envtest
  cmd/broker/bindings_envtest_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1398 Remove request logging for service bindings
  cmd/broker/main.go
  internal/middleware/request_logging.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1395 Remove unused values from KEB chart
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1399 Fix KEB chart
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#1388 Timeout of creation Service Binding
  cmd/broker/binding_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/broker/bind_create.go
  internal/broker/server.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, kind/enhancement, cla: yes
