Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-12, with the labels that each got.

#1513 Increase provisioning and deprovisioning duration metric range
  internal/metricsv2/operation_duration.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1517 Use everywhere new constructor for op manager
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_runtime_removal_step.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
  internal/process/deprovisioning/delete_gardener_cluster.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/deprovisioning/edp_deregistration.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/deprovisioning/remove_instance_step.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/operation_manager.go
  internal/process/operation_manager_test.go
  internal/process/provisioning/apply_kyma_step.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/provisioning/create_resource_names_step.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/edp_registration.go
  internal/process/provisioning/generate_runtime_id_step.go
  internal/process/provisioning/get_kubeconfig_step.go
  internal/process/provisioning/initialisation.go
  internal/process/provisioning/inject_btp_operator_credentials_step.go
  internal/process/provisioning/override_kyma_modules.go
  internal/process/provisioning/resolve_creds.go
  internal/process/provisioning/start_step.go
  internal/process/staged_manager.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/kyma_template.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
  internal/process/steps/runtime_resource.go
  internal/process/update/check_step.go
  internal/process/update/initialisation_step.go
  internal/process/update/update_runtime_step.go
  internal/process/update/upgrade_shoot_step.go
Labels: size/L, kind/enhancement, cla: yes

#1519 Fix component name
  internal/error/errors.go
  internal/process/deprovisioning/btp_operator_cleanup.go
Labels: size/S, kind/enhancement, cla: yes

#1526 Provision only SKR in SKR suspension test
  scripts/testing/get-latest-k3s-releases.sh
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/trial-suspension-test/test.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1522 Remove logs from storage layer
  internal/cis/e2e/tests_utils.go
  internal/storage/driver/postsql/events/events.go
  internal/storage/driver/postsql/initialization_test.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/orchestration.go
  internal/storage/driver/postsql/postsql_test.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/subaccount_state.go
  internal/storage/postsql/init.go
  internal/storage/storage.go
Labels: size/L, kind/enhancement, cla: yes

#1529 Use slog in env cleanup job
  cmd/accountcleanup/main.go
  cmd/archiver/main.go
  cmd/broker/main.go
  cmd/deprovisionretrigger/main.go
  cmd/expirator/main.go
  cmd/runtimereconciler/main.go
  cmd/servicebindingcleanup/main.go
  cmd/subaccountsync/main.go
  cmd/trialcleanup/main.go
  common/setup/builder.go
  common/setup/error_handlers.go
  internal/cis/e2e/account_cleanup_test.go
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
  internal/globalaccounts/globalaccounts.go
  internal/storage/storage.go
  internal/storage/storage_handler.go
Labels: size/L, kind/enhancement, cla: yes

#1527 Set KEB dependecies
  internal/error/errors.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_runtime_removal_step.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
  internal/process/deprovisioning/delete_gardener_cluster.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/deprovisioning/remove_instance_step.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/provisioning/create_resource_names_step.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/generate_runtime_id_step.go
  internal/process/provisioning/get_kubeconfig_step.go
  internal/process/provisioning/initialisation.go
  internal/process/provisioning/inject_btp_operator_credentials_step.go
  internal/process/provisioning/override_kyma_modules.go
  internal/process/provisioning/resolve_creds.go
  internal/process/provisioning/start_step.go
  internal/process/staged_manager.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/kyma_template.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
  internal/process/steps/runtime_resource.go
  internal/process/update/check_step.go
  internal/process/update/initialisation_step.go
  internal/process/update/update_runtime_step.go
  internal/process/update/upgrade_shoot_step.go
Labels: size/M, kind/enhancement, cla: yes

#1531 Use slog in Account Cleanup Job
  cmd/accountcleanup/main.go
  internal/cis/account_cleanup.go
  internal/cis/account_cleanup_test.go
  internal/cis/client.go
  internal/cis/client_test.go
  internal/cis/client_ver_1.go
  internal/cis/client_ver_1_test.go
  internal/cis/e2e/account_cleanup_test.go
  internal/cis/fake_server.go
Labels: size/L, kind/enhancement, cla: yes

#1535 Use slog in Deprovision Retrigger Job
  cmd/deprovisionretrigger/main.go
Labels: size/M, kind/enhancement, cla: yes

#1536 Use slog in Global Accounts Job
  internal/globalaccounts/globalaccounts.go
Labels: size/L, kind/enhancement, cla: yes

#1538 Use slog in Trial Cleanup Job
  cmd/trialcleanup/main.go
Labels: size/M, kind/enhancement, cla: yes

#1539 Retract v0.0.1 version
  go.mod
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1540 Use slog in Schema Migrator Job
  cmd/schemamigrator/main.go
Labels: size/M, kind/enhancement, cla: yes

#1542 Use slog in Subaccount Sync Job
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/subaccountsync/main.go
  internal/config/provider_test.go
  internal/config/reader.go
  internal/config/reader_test.go
  internal/process/provisioning/create_resource_names_step_test.go
Labels: size/L, kind/enhancement, cla: yes

#1533 Hide targetsecret in runtimes endpoint
  common/runtime/model.go
  internal/runtime/converter.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1543 Replace deprecated NewNamedRateLimitingQueue
  internal/process/queue.go
Labels: size/XS, kind/enhancement, cla: yes

#1544 Use slog in Runtime Reconciler
  cmd/runtimereconciler/main.go
  internal/btpmanager/credentials/job.go
  internal/btpmanager/credentials/manager.go
  internal/btpmanager/credentials/manager_test.go
Labels: size/L, kind/enhancement, cla: yes

#1545 Use slog in handlers
  cmd/broker/bindings_envtest_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/broker/bind_create_test.go
  internal/event/pubsub.go
  internal/event/pubsub_test.go
  internal/health/server.go
  internal/kubeconfig/handler.go
  internal/kubeconfig/handler_test.go
  internal/metricsv2/operations_result_test.go
  internal/process/upgrade_cluster/manager_test.go
  internal/provisioner/client.go
  internal/provisioner/client_test.go
Labels: size/L, kind/enhancement, cla: yes

#1549 Apply kyma step does not set compass runtime id in the Kyma resource
  cmd/broker/provisioning_test.go
  internal/model.go
  internal/process/provisioning/apply_kyma_step.go
  internal/process/provisioning/apply_kyma_step_test.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1547 Use slog in metrics
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/metricsv2/bind.go
  internal/metricsv2/instances_collector.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operation_duration.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_result_test.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
Labels: size/L, kind/enhancement, cla: yes

#1550 Use slog in runtime and expiration endpoints
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/expiration/handler.go
  internal/expiration/handler_test.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1552 Use slog in orchestration
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  common/orchestration/resolver.go
  common/orchestration/resolver_test.go
  internal/orchestration/handlers/cancel.go
  internal/orchestration/handlers/cancel_test.go
  internal/orchestration/handlers/cluster_handler.go
  internal/orchestration/handlers/cluster_handler_test.go
  internal/orchestration/handlers/cluster_retry.go
  internal/orchestration/handlers/handlers.go
  internal/orchestration/handlers/orchestration_handler.go
  internal/orchestration/handlers/orchestration_handler_test.go
  internal/orchestration/runtime_lister.go
Labels: size/L, kind/enhancement, cla: yes

#1555 Replace deprecated Polls
  cmd/broker/bindings_envtest_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/subaccountsync/main.go
  common/setup/builder.go
  internal/broker/instance_update.go
  internal/broker/poller.go
  internal/event/pubsub_test.go
  internal/globalaccounts/globalaccounts.go
  internal/kubeconfig/provider_test.go
  internal/kymacustomresource/kyma_cr_updater_test.go
  internal/orchestration/manager/manager.go
  internal/process/staged_manager_test.go
  internal/process/upgrade_cluster/manager_test.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/orchestration.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/subaccount_state.go
  testing/e2e/provisioning/pkg/client/broker/broker_client.go
  testing/e2e/provisioning/pkg/client/broker/upgrade_broker_client.go
  testing/e2e/provisioning/pkg/client/v1_client/configmap.go
  testing/e2e/provisioning/pkg/client/v1_client/secret.go
Labels: size/L, kind/enhancement, cla: yes

#1532 Skip secret reconciliation if secret labelled
  cmd/runtimereconciler/main.go
  internal/btpmanager/credentials/job.go
  internal/btpmanager/credentials/manager.go
  internal/btpmanager/credentials/manager_test.go
  internal/btpmanager/credentials/metrics.go
  resources/keb/templates/policy.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/service-monitor.yaml
  resources/keb/templates/service.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#1561 Label for `runtime-reconciler` renamed
  internal/btpmanager/credentials/manager.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1563 Reverted original label name for reconciliation skipping
  internal/btpmanager/credentials/manager.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1565 Metrics use `shootName`
  internal/btpmanager/credentials/manager.go
  internal/btpmanager/credentials/metrics.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1568 Use slog in API
  cmd/broker/bindings_envtest_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/appinfo/runtime_info_test.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_delete.go
  internal/broker/bind_get.go
  internal/broker/bind_get_test.go
  internal/broker/bind_last_operation.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_deprovision.go
  internal/broker/instance_deprovision_test.go
  internal/broker/instance_get.go
  internal/broker/instance_get_test.go
  internal/broker/instance_last_operation.go
  internal/broker/instance_last_operation_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/services.go
  internal/broker/services_test.go
  internal/httputil/response.go
  internal/httputil/response_test.go
  internal/suspension/handler.go
  internal/suspension/handler_test.go
Labels: size/XL, kind/enhancement, cla: yes

#1571 Remove logrus
  cmd/broker/bindings_envtest_test.go
  cmd/broker/broker_suite_test.go
  common/deprovision/client.go
  common/hyperscaler/azure/client.go
  common/hyperscaler/azure/provider.go
  common/hyperscaler/azure/testing/testing.go
  docs/user/03-20-runtime-operations.md
  go.mod
  internal/broker/client.go
  internal/broker/labeler.go
  internal/httputil/write_response.go
  internal/logger/spy_logger.go
  internal/metricsv2/debuger.go
  internal/model.go
  internal/process/deprovisioning/automock/step.go
  internal/provisioner/graphqlizer.go
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
  testing/e2e/provisioning/pkg/client/broker/broker_client.go
  testing/e2e/provisioning/pkg/client/broker/upgrade_broker_client.go
  testing/e2e/provisioning/pkg/client/runtime/runtime_client.go
  testing/e2e/provisioning/pkg/client/v1_client/configmap.go
  testing/e2e/provisioning/pkg/client/v1_client/secret.go
  testing/e2e/provisioning/test/e2e_provisioning_test.go
  testing/e2e/provisioning/test/e2e_suspension_test.go
  testing/e2e/provisioning/test/e2e_upgrade_test.go
  testing/e2e/provisioning/test/test_suite.go
  testing/e2e/provisioning/test/upgrade_test_suite.go
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1573 Remove log
  cmd/broker/storage_test.go
  internal/broker/bind_create_test.go
  internal/docker_helper.go
Labels: size/M, kind/enhancement, cla: yes

#1575 Container port redefined for `runtime-reconciler`
  resources/keb/templates/runtime-reconciler-deployment.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1577 Gardener upgrade
  go.mod
  go.sum
Labels: size/M, kind/enhancement, cla: yes

#1534 Add us-west-2 AWS region
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/provider/aws_provider.go
Labels: size/L, kind/feature, lgtm, cla: yes

#1558 Fix Service Binding doc
  docs/README.md
  docs/assets/bindings-create-flow.drawio.svg
  docs/assets/bindings-delete-flow.drawio.svg
  docs/assets/bindings-get-flow.drawio.svg
  docs/contributor/03-40-kyma-bindings-processes.md
  docs/user/05-60-kyma-bindings-api-examples.md
  docs/user/05-60-kyma-bindings.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1578 Make the default Nodes CIDR bigger
  docs/user/03-10-service-description.md
  docs/user/05-40-instance-details.md
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/networking/cidr.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/provider/azure_provider_test.go
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1579 Fix labels on runtime-reconciler
  resources/keb/templates/runtime-reconciler-deployment.yaml
Labels: kind/bug, size/XS, cla: yes

#1583 Remove logrus from env test
  go.mod
  internal/broker/bind_envtest_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1582 `skip-reconciliation` label - documentation update
  docs/contributor/07-10-runtime-reconciler.md
Labels: area/documentation, size/XS, kind/enhancement, cla: yes

#1584 Do not override last error
  internal/process/operation_manager.go
  internal/process/operation_manager_test.go
  internal/process/staged_manager.go
Labels: size/S, kind/enhancement, cla: yes

#1589 Align azure_lite root volume to be the same as other paid plan runtimes
  internal/provider/azure.go
  internal/provider/azure_provider.go
  internal/provider/azure_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1595 Enable current configuration load
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/aws/update-free-aws-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/azure-trial-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/azure/update-azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/update-free-azure-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/own-cluster-schema-additional-params.json
  internal/broker/testdata/own-cluster-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
  internal/broker/testdata/update-own-cluster-schema-additional-params.json
  internal/broker/testdata/update-own-cluster-schema.json
Labels: size/M, kind/enhancement, cla: yes

#1599 Revert "Enable current configuration load (#1595)"
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/aws/update-free-aws-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/azure-trial-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/azure/update-azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/update-free-azure-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/own-cluster-schema-additional-params.json
  internal/broker/testdata/own-cluster-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
  internal/broker/testdata/update-own-cluster-schema-additional-params.json
  internal/broker/testdata/update-own-cluster-schema.json
Labels: size/M, kind/enhancement, cla: yes

#1601 Add CLI tool scaffold to replace old nodejs SKR tests
  testing/e2e/skr-tester/Makefile
  testing/e2e/skr-tester/cmd/main.go
  testing/e2e/skr-tester/go.mod
  testing/e2e/skr-tester/go.sum
  testing/e2e/skr-tester/pkg/broker/client.go
  testing/e2e/skr-tester/pkg/command/deprovision.go
  testing/e2e/skr-tester/pkg/command/provision.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/logger/logger.go
Labels: size/XL, kind/enhancement, cla: yes
