Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-03, with the labels that each got.

#505 Add govulncheck action
  .github/workflows/run-govulncheck.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-verify.yaml
  docs/contributor/04-10-workflows.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#502 Unnecessary Last Operation Load
  internal/storage/dbmodel/instance.go
  internal/storage/driver/postsql/instance.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#513 Remove govulncheck action
  .github/workflows/run-govulncheck.yaml
  docs/contributor/04-10-workflows.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#498 Archiving and cleaning in the deprovisioning process
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/last_operation_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/archive/config.go
  internal/broker/instance_last_operation.go
  internal/broker/instance_last_operation_test.go
  internal/model.go
  internal/process/deprovisioning/archiving_step.go
  internal/process/deprovisioning/archiving_step_test.go
  internal/process/deprovisioning/clean_step.go
  internal/process/deprovisioning/clean_step_test.go
  internal/process/deprovisioning/remove_instance_step.go
  internal/process/staged_manager.go
  internal/provisioner/fake_client.go
  internal/storage/driver/memory/operation.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#515 Change kcp prefix to compass
  resources/keb/files/dashboard.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#518 Bump to 1.2.5, change compass prefix to kcp
  resources/keb/files/dashboard.json
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#510 [betaEnabled] Introduce priority queues
  internal/syncqueues/model.go
  internal/syncqueues/priority_queue.go
  internal/syncqueues/priority_queue_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#526 Bump schema migrator to v20240307-f250dc83
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#500 Metrics refactor start
  cmd/broker/main.go
  internal/broker/plans.go
  internal/metrics/metrics.go
  internal/metricsv2/metricsv2.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/model.go
  internal/process/events.go
  internal/process/staged_manager.go
  internal/storage/automock/operations.go
  internal/storage/dbmodel/operation.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/operation.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#521 DB layer for betaEnabled
  internal/model.go
  internal/storage/dbmodel/subaccount_state.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/memory/subaccount_state.go
  internal/storage/driver/memory/subaccount_state_test.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/subaccount_state.go
  internal/storage/driver/postsql/subaccount_state_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/init.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  internal/storage/storage.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#496 Fix issues reported by golangci linter
  Makefile
  cmd/accountcleanup/main.go
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/deprovisionretrigger/main.go
  cmd/trialcleanup/main.go
  common/hyperscaler/account_pool.go
  common/hyperscaler/shared_pool.go
  common/orchestration/resolver.go
  common/orchestration/strategies/parallel.go
  common/setup/builder.go
  internal/avs/client.go
  internal/dto.go
  internal/environmentscleanup/service.go
  internal/orchestration/manager/manager.go
  internal/orchestration/manager/upgrade_kyma.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step_test.go
  internal/process/provisioning/get_kubeconfig_test.go
  internal/process/provisioning/inject_btp_operator_credentials_step_test.go
  internal/process/provisioning/override_kyma_modules.go
  internal/process/staged_manager_test.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
  internal/process/steps/kyma_template.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
  internal/process/update/manager_test.go
  internal/process/upgrade_kyma/apply_kyma_step.go
  internal/provisioner/client_test.go
  internal/provisioner/fake_client.go
  internal/storage/driver/memory/operation.go
  internal/test_utils.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#527 Fetch instance archived runtimes endpoint
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/main.go
  internal/archive/archive.go
  internal/model.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/storage_handler.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#539 Linter improvements
  .golangci.yml
  Makefile
  common/orchestration/client_test.go
  internal/btpmanager/credentials/manager_test.go
  internal/config/validator.go
  internal/edp/client_test.go
  internal/orchestration/handlers/kyma_handler_test.go
  internal/process/input/input_test.go
  internal/provisioner/graphqlizer_test.go
  internal/reconciler/fake.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#514 Query Optimisation - Group Operations in Go
  internal/model.go
  internal/runtime/handler.go
  internal/storage/automock/operations.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/operation.go
  internal/storage/ext.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#543 Removal of Unused Watcher
  cmd/runtimereconciler/main.go
  go.mod
  go.sum
  internal/btpmanager/credentials/manager_test.go
  internal/btpmanager/credentials/watcher.go
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#544 Add Kyma CustomResource GroupVersionKind and GroupVersionResource provider
  internal/kymacustomresource/resource_kind_provider.go
  internal/kymacustomresource/resource_kind_provider_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#540 Linter
  .github/workflows/run-verify.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#545 Archiver, init
  cmd/archiver/main.go
  cmd/runtimereconciler/main.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#546 Introduce new and duplicate old metrics
  Makefile
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/metrics/metrics.go
  internal/metricsv2/instances_collector.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operation_duration.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/process/events.go
  internal/process/staged_manager.go
  resources/keb/files/dashboardv2.json
  resources/keb/templates/dashboardv2.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#529 Add Kyma CR Updater
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
Labels: size/L, kind/feature, lgtm, cla: yes

#550 adding new oidc group
  resources/keb/templates/authorization-policy.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#551 Fix trial expiration handler
  internal/expiration/handler.go
  internal/expiration/handler_test.go
Labels: size/L, kind/bug, lgtm, cla: yes

#555 Upgrade shoot with retries and timeouts
  internal/process/update/upgrade_shoot_step.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#559 Linter timeout increase
  .golangci.yml
  Makefile
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#558 First batch of dependabot changes
  Dockerfile.job
  Dockerfile.keb
  Dockerfile.runtimereconciler
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#561 Second part of dependabot updates
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#567 PostgreSQL container is not removed after test failure
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/orchestration_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/storage_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma_test.go
Labels: size/M, kind/bug, lgtm, cla: yes

#569 Add business metrics dashboard
  resources/keb/files/business-metrics-dashboard.json
  resources/keb/templates/business-metrics-dashboard.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#571 Remove business metrics dashboard ID
  resources/keb/files/business-metrics-dashboard.json
Labels: size/S, lgtm, kind/enhancement, cla: yes

#564 Tests for metrics
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/metrics_test.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/process/events.go
  internal/process/staged_manager.go
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#575 Reporting Missing Metric for Deprovision
  internal/metrics/operation_result.go
Labels: size/S, kind/bug, lgtm, cla: yes

#576 Fix business metrics dashboard configmap
  resources/keb/files/business-metrics-dashboard.json
  resources/keb/templates/business-metrics-dashboard.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#570 Metrics docs
  docs/assets/metrics.drawio
  docs/assets/metrics.svg
  docs/user/06-10-metrics.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#578 Use new priority queue with callbacks
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
  internal/syncqueues/model.go
  internal/syncqueues/priority_queue.go
  internal/syncqueues/priority_queue_test.go
  internal/syncqueues/priority_queue_with_stats.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#547 Archiver
  cmd/archiver/main.go
  docs/contributor/06-60-archiver-job.md
  docs/contributor/08-10-cleaning-and-archiving.md
  internal/archive/config.go
  internal/archive/service.go
  internal/archive/service_test.go
  internal/model.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/memory/instance_archived.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_archived.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  utils/archiver/apply.sh
  utils/archiver/kyma-environment-broker-archiver.yaml
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#581 Subaccount sync application stub
  Dockerfile.subaccountsync
  cmd/subaccountsync/main.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#577 Add govulncheck
  .github/workflows/run-govulncheck.yaml
  docs/contributor/04-10-workflows.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#584 GetDistinctSubaccounts query corrected
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/read.go
  internal/storage/storage_handler.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#541 Ensure inputCreator is not nil
  internal/model.go
  internal/process/deprovision_operation.go
  internal/process/deprovision_operation_test.go
  internal/process/operation_manager.go
  internal/process/operation_manager_test.go
  internal/process/provision_operation.go
  internal/process/provision_operation_test.go
  internal/process/provisioning/resolve_creds.go
  internal/process/update_operation.go
  internal/process/upgrade_cluster_operation.go
  internal/process/upgrade_kyma_operation.go
Labels: kind/bug, lgtm, size/XL, cla: yes

#589 CIS fake server for tests
  go.mod
  internal/cis/fake_server.go
  internal/cis/fake_server_test.go
  internal/cis/testdata/events.json
  internal/cis/testdata/subaccounts.json
Labels: area/tests, lgtm, size/XL, kind/enhancement, cla: yes

#591 Add promote KEB to dev workflow
  .github/workflows/promote-keb-to-dev.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#594 Fake CIS server extended
  internal/cis/fake_server.go
  internal/cis/fake_server_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#590 Remove director references
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  common/director/automock/GraphQLClient.go
  common/director/client.go
  common/director/client_test.go
  common/director/config.go
  common/director/fake.go
  common/director/query.go
  docs/contributor/02-31-keb-configuration.md
  docs/user/05-10-provisioning-kyma-environment.md
  docs/user/05-40-instance-details.md
  go.mod
  go.sum
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#595 Corrected fake server
  internal/cis/fake_server.go
  internal/cis/fake_server_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#597 Set Logrus Time Format to Nano Seconds
  cmd/broker/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#599 Extend InstanceArchived table with status of the provisioning
  internal/archive/archive.go
  internal/archive/archive_test.go
  internal/model.go
  internal/storage/dbmodel/instance_archived.go
  internal/storage/driver/postsql/instance_archived_test.go
  internal/storage/postsql/write.go
  resources/keb/migrations/202403280900_add_instance_archived_provisioning_state.down.sql
  resources/keb/migrations/202403280900_add_instance_archived_provisioning_state.up.sql
Labels: size/S, lgtm, kind/enhancement, cla: yes

#600 Free expiration FF
  go.mod
  internal/broker/broker.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#602 Free can be expired
  cmd/broker/expiration_test.go
  cmd/broker/suite_test.go
  internal/expiration/handler.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#606 Update gh-pages readme
  README.md
Labels: size/S, lgtm, kind/enhancement, cla: yes

#609 Added Missing `DATABASE_EMBEDDED` Env
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#601 Optional Skip for Deprovisioning
  testing/e2e/skr/skr-test/test.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes
