Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-02, with the labels that each got.

#421 Add error handling to runtime reconciler
  cmd/runtimereconciler/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#422 Change vars to const in metrics package
  internal/metrics/operations_db_collector.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#424 Update dashboard.json to use increase_proetheus
  resources/keb/files/dashboard.json
Labels: size/S, lgtm, kind/enhancement, cla: yes

#426 Update istio gwateway config
  resources/keb/Chart.yaml
  resources/keb/templates/virtualservice.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#427 Fix Gardener cluster name and kyma name cleanup in the deprovisioning…
  cmd/broker/deprovisioning.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/delete_gardener_cluster.go
  internal/process/deprovisioning/delete_gardenercluster_step_test.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_kyma_resource_step_test.go
  internal/process/deprovisioning/remove_instance_step.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/lifecycle_manager.go
Labels: size/M, kind/bug, lgtm, area/control-plane, cla: yes

#430 Bump to 1.1.7
  resources/keb/values.yaml
Labels: size/S, lgtm, area/control-plane, kind/enhancement, cla: yes

#433 Remove last k3s versions input from release
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#432 Fix btpoperatorcleanup step
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
  internal/process/provisioning/apply_kyma_step.go
Labels: size/S, kind/bug, lgtm, area/control-plane, cla: yes

#435 Bump1.1.8
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, area/control-plane, kind/enhancement, cla: yes

#431 envtest
  envtest.sh
  internal/btpmanager/credentials/manager_test.go
  internal/kubeconfig/provider_test.go
  internal/test_utils.go
  setup-envtest.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#442 fix operation collector
  .gitignore
  internal/metrics/operations_collector.go
  internal/storage/dbmodel/operation.go
  internal/storage/driver/postsql/operation.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#449 bump to v1.1.10
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#453 Documentation update
  docs/README.md
  docs/assets/keb-arch.drawio
  docs/assets/keb-arch.svg
  docs/contributor/01-20-swagger.md
  docs/contributor/02-10-runtime-components.md
  docs/contributor/02-20-runtime-overrides.md
  docs/contributor/02-30-kyma-versions.md
  docs/contributor/02-31-keb-configuration.md
  docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md
  docs/contributor/02-50-orchestration.md
  docs/contributor/02-60-orchestrate-kyma-upgrade.md
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/contributor/03-20-eu-access.md
  docs/contributor/04-20-release.md
  docs/contributor/05-10-e2e_tests.md
  docs/contributor/06-20-environments-cleanup-cronjob.md
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
  docs/contributor/07-10-runtime-reconciler.md
  docs/user/01-10-architecture.md
  docs/user/01-20-target-architecture.md
  docs/user/02-10-broker-endpoints.md
  docs/user/03-10-service-description.md
  docs/user/03-20-runtime-operations.md
  docs/user/04-10-custom-oidc-configuration.md
  docs/user/04-20-custom-administrators.md
  docs/user/04-30-custom-networking-configuration.md
  docs/user/05-10-provisioning-kyma-environment.md
  docs/user/05-40-instance-details.md
  docs/user/05-50-configure-list-of-modules.md
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#451 Add job skipping to workflows
  .github/workflows/create-release.yaml
  .github/workflows/run-eslint.yaml
  .github/workflows/run-keb-chart-tests-reusable.yaml
  .github/workflows/run-keb-chart-tests.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-verify.yaml
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#444 Change default machines in aws, azure, gcp, sap-converged-cloud plans
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/check_cluster_configuration_test.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  internal/provider/gcp_provider.go
  internal/provider/sap-converged-cloud_provider.go
Labels: size/L, kind/feature, lgtm, cla: yes

#450 Change default machine types in docs
  docs/user/03-10-service-description.md
Labels: size/L, kind/feature, area/documentation, lgtm, cla: yes

#459 Bump images to 1.2.0
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#445 Use SQL DB in e2e unit tests
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/expiration_test.go
  cmd/broker/last_operation_test.go
  cmd/broker/storage_test.go
  cmd/broker/suite_test.go
  docs/contributor/04-10-workflows.md
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/conflict_test.go
  internal/storage/driver/postsql/initialization_test.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/driver/postsql/orchestration_test.go
  internal/storage/driver/postsql/postsql_test.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/storage_handler.go
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#463 catch error in e2e tests
  testing/e2e/skr/kcp/client.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#464 Enhanced Logging
  internal/kubeconfig/provider.go
  internal/process/provisioning/inject_btp_operator_credentials_step.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#469 Retry K8S Client Creation
  internal/kubeconfig/provider.go
  internal/process/provisioning/inject_btp_operator_credentials_step.go
Labels: size/S, kind/bug, lgtm, cla: yes

#462 Use 3 zones in sap-converged-cloud plan
  internal/process/input/builder.go
  internal/provider/sap-converged-cloud_provider.go
  internal/provider/sap-converged-cloud_provider_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#470 Use in with cluster
  README.md
  docs/contributor/02-31-keb-configuration.md
  docs/contributor/04-10-workflows.md
  docs/user/03-10-service-description.md
  docs/user/05-50-configure-list-of-modules.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#473 [Metrics] Error while calling pubsub event handler
  internal/metrics/operation_duration.go
  internal/metrics/operation_result.go
  internal/metrics/step_result.go
Labels: size/S, kind/bug, lgtm, cla: yes

#466 Instances archived
  internal/archive/archive.go
  internal/archive/archive_test.go
  internal/model.go
  internal/storage/automock/operations.go
  internal/storage/dbmodel/instance_archived.go
  internal/storage/driver/memory/instance_archived.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/memory/runtime_state.go
  internal/storage/driver/postsql/instance_archived.go
  internal/storage/driver/postsql/instance_archived_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/init.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  internal/storage/storage.go
  resources/keb/migrations/202402211130_instance_archived.down.sql
  resources/keb/migrations/202402211130_instance_archived.up.sql
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#476 temporary test metrics
  internal/metrics/metrics.go
  internal/metricsv2/metricsv2.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#477 Update dependencies
  go.mod
  go.sum
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#479 Bump to 1.2.2
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#480 temporary metric handler changes
  internal/metrics/metrics.go
  internal/metricsv2/metricsv2.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#483 Bump KEB to 1.2.3
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#471 update query used to fetch total operation failures
  resources/keb/files/dashboard.json
  resources/keb/templates/dashboard.yaml
  resources/keb/templates/gardener-dashboard.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#486 Fix openstack - remove not needed params
  internal/process/input/builder.go
  internal/process/input/input.go
  internal/provider/sap-converged-cloud_provider.go
  internal/provisioner/graphqlizer.go
  internal/provisioner/graphqlizer_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#488 Bump to 1.2.4
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#491 Fix issues reported by golangci
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/suite_test.go
  common/orchestration/client_test.go
  common/orchestration/resolver_test.go
  internal/avs/model_test.go
  internal/broker/client_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update_test.go
  internal/environmentscleanup/service_test.go
  internal/kubeconfig/provider_test.go
  internal/process/deprovisioning/check_cluster_deregistration_test.go
  internal/process/deprovisioning/check_runtime_removal_step_test.go
  internal/process/deprovisioning/delete_gardenercluster_step_test.go
  internal/process/deprovisioning/delete_kyma_resource_step_test.go
  internal/process/deprovisioning/deregister_cluster_test.go
  internal/process/deprovisioning/edp_deregistration_test.go
  internal/process/deprovisioning/init_test.go
  internal/process/deprovisioning/release_subscription_step_test.go
  internal/process/input/input.go
  internal/process/provisioning/apply_kyma_step_test.go
  internal/process/provisioning/check_cluster_configuration_test.go
  internal/process/provisioning/create_cluster_configuration_step_test.go
  internal/process/provisioning/edp_registration_test.go
  internal/process/provisioning/get_kubeconfig_test.go
  internal/process/provisioning/initialisation_test.go
  internal/process/provisioning/inject_btp_operator_credentials_step_test.go
  internal/process/provisioning/resolve_creds_test.go
  internal/process/provisioning/start_step_test.go
  internal/process/staged_manager_test.go
  internal/process/steps/gardener_cluster_test.go
  internal/process/steps/kyma_template_test.go
  internal/process/update/initialisation_step_test.go
  internal/process/update/manager_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provider/sap-converged-cloud_provider.go
  internal/storage/driver/memory/runtime_state_test.go
  internal/suspension/handler_test.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes
