Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-06, with the labels that each got.

#786 Cleanup RuntimeInput, InputBuilderFactory
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  docs/README.md
  docs/assets/runtime-components.svg
  docs/contributor/02-10-runtime-components.md
  docs/user/01-20-target-architecture.md
  internal/component_input_helpers.go
  internal/config/provider_test.go
  internal/fixture/fixture.go
  internal/model.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/input/automock/component_list_provider.go
  internal/process/input/automock/components_disabler.go
  internal/process/input/automock/disabled_components_provider.go
  internal/process/input/automock/optional_component_service.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input.go
  internal/process/input/input_test.go
  internal/process/provisioning/automock/provisioner_input_creator.go
  internal/process/provisioning/base_provision_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/provisioning/initialisation.go
  internal/process/provisioning/resolve_creds.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/process/upgrade_kyma/automock/components_disabler.go
  internal/process/upgrade_kyma/automock/disabled_components_provider.go
  internal/process/upgrade_kyma/automock/optional_component_service.go
  internal/process/upgrade_kyma/automock/provisioner_input_creator.go
  internal/process/upgrade_kyma/initialisation.go
  internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  internal/provisioning/automock/provisioner_input_creator.go
  internal/runtime/components/components.go
  internal/runtime/components_provider.go
  internal/runtime/components_provider_fake.go
  internal/runtime/components_provider_test.go
  internal/runtime/custom_disabler_example.go
  internal/runtime/custom_disabler_example_test.go
  internal/runtime/disabled_components.go
  internal/runtime/disabled_components_service.go
  internal/runtime/generic_component_disabler.go
  internal/runtime/generic_component_disabler_test.go
  internal/runtime/opt_components_service.go
  internal/runtime/testdata/additional-runtime-components.yaml
  internal/runtime/testdata/kyma-components.yaml
  internal/runtime/testdata/managed-runtime-components.yaml
Labels: area/documentation, lgtm, size/XXL, kind/enhancement, cla: yes

#800 Fix Azure lites machine types
  internal/broker/plans.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#796 ShootAndSeedSameRegion - Schema & Feature Flag
  internal/appinfo/runtime_info.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#794 Change to use cloudsql-proxy v2 image and cmd
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
  utils/archiver/apply.sh
  utils/archiver/kyma-environment-broker-archiver.yaml
  utils/kyma-environments-cleanup-job/README.md
  utils/kyma-environments-cleanup-job/apply.sh
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#804 ShootAndSeedSameRegion - Provisioner & KEB
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  go.mod
  go.sum
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/dto.go
  internal/process/input/builder.go
  internal/process/input/input.go
  internal/process/input/input_test.go
  internal/provisioner/fake_client.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#806 Change default machine type in Azure lite
  internal/process/input/builder.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#807 Cleanup after free plan
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/storage/dbmodel/operation.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/postsql/read.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#809 Bump Go to 1.22.4
  Dockerfile.job
  Dockerfile.keb
  Dockerfile.runtimereconciler
  Dockerfile.subaccountsync
  go.mod
Labels: size/S, lgtm, kind/enhancement, cla: yes

#802 Remove reconciler dependency
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  go.mod
  go.sum
  internal/fixture/fixture.go
  internal/model.go
  internal/orchestration/handlers/orchestration_handler.go
  internal/orchestration/handlers/orchestration_handler_test.go
  internal/storage/dbmodel/runtime_state.go
  internal/storage/driver/memory/runtime_state.go
  internal/storage/driver/memory/runtime_state_test.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/postsql/write.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#814 Handling missing subaccount label in Kyma CR
  internal/subaccountsync/informer.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#811 Handle partial events synchronization
  internal/subaccountsync/cis_events.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#817 Configurable strategy for runtimeID to subaccountID mapping
  cmd/subaccountsync/main.go
  internal/subaccountsync/config.go
  internal/subaccountsync/informer.go
  internal/subaccountsync/subaccount_sync_service.go
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#821 Bump schema migrator to v20240610-ea747dbf
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#825 Fix runtime config CM
  resources/keb/templates/keb-runtime-configuration.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#824 Update docs after Reconciler removal
  README.md
  docs/README.md
  docs/contributor/02-20-runtime-overrides.md
  docs/contributor/02-30-kyma-versions.md
  docs/user/01-20-target-architecture.md
  docs/user/03-10-service-description.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#818 EU Whitelist Refactoring
  internal/utils/testdata/embedded_object.yaml
  internal/utils/testdata/list_of_string_in_property.yaml
  internal/utils/testdata/multiple_mappings.yaml
  internal/utils/testdata/multiple_mappings_override.yaml
  internal/utils/yaml.go
  internal/utils/yaml_test.go
  internal/whitelist/whitelisted_globalaccounts.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#829 Missing Env Variable
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#833 Update schema-migrator version in go.mod
  go.mod
  go.sum
Labels: size/S, lgtm, kind/enhancement, cla: yes

#832 Make `cloudsql-proxy` exit zero on SIGTERM
  go.mod
  go.sum
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#841 Missing parameters added
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#843 Implementation of DefaultConvergedCloudRegionsProvider
  internal/broker/automock/region_reader.go
  internal/broker/converged_region_provider.go
  internal/broker/converged_region_provider_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#820 Injecting Region Mapping Config into KEB
  cmd/broker/main.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#844 Conditional Converged Plan Rendering
  internal/broker/plans.go
  internal/broker/plans_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#845 Added Missing Region Parameter
  internal/appinfo/runtime_info.go
  internal/broker/converged_region_provider.go
  internal/broker/converged_region_provider_test.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/provider/sap-converged-cloud_provider_test.go
Labels: size/S, kind/bug, lgtm, cla: yes

#840 Enhance gcp plan with new regions
  internal/broker/plans.go
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema.json
Labels: size/S, kind/feature, lgtm, cla: yes

#851 Docker library upgraded
  go.mod
  go.sum
  internal/docker_helper.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#846 Integrating all Components for sap-converged-cloud Plan Region Mapping
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/schema_test.go
  cmd/broker/testdata/sap-converged-cloud-region-mappings.yaml
  internal/appinfo/runtime_info.go
  internal/appinfo/runtime_info_test.go
  internal/broker/converged_region_provider.go
  internal/broker/converged_region_provider_test.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/services.go
Labels: size/L, kind/feature, lgtm, cla: yes

#852 Update Azure lite docs with new default machineType
  docs/user/03-10-service-description.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#857 Use new KCP CLI in SKR tests
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/skr-test/oidc/index.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/skr-test/test.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#856 Removed Workaround Logic
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/old-sap-converged-cloud-region-mappings.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#853 Provide Pods and Service CIDRS in provisioning parameters
  cmd/broker/provisioning_test.go
  internal/broker/instance_create.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
Labels: kind/feature, lgtm, size/XL, cla: yes

#865 Corrected Region for sap-converged-plan Update Operation
  cmd/broker/update_test.go
  internal/broker/instance_update.go
Labels: size/M, kind/bug, lgtm, cla: yes

#863 Panic recovery in tests
  internal/subaccountsync/state_reconciler_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#869 Logs improved and corrected
  internal/kymacustomresource/kyma_cr_updater.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#861 Remove Kyma version configuration
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_kyma_test.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/dto.go
  internal/fixture/fixture.go
  internal/model.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/provisioning/initialisation.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/runtimeversion/account_mapping.go
  internal/runtimeversion/account_mapping_test.go
  internal/runtimeversion/runtimeversion.go
  internal/runtimeversion/runtimeversion_test.go
  resources/keb/files/swagger.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#870 Re-enable kubeconfig related SKR tests
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/skr-test/oidc/index.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/skr-test/test.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#871 Add "ap-au-1" Region to sap-converged-cloud Provider
  internal/provider/sap-converged-cloud_provider.go
  internal/provider/sap-converged-cloud_provider_test.go
Labels: size/S, kind/bug, lgtm, cla: yes

#873 More comprehensive logging for `subaccount-sync`
  internal/subaccountsync/cis_events.go
  internal/subaccountsync/informer.go
  internal/subaccountsync/state_reconciler.go
  internal/syncqueues/priority_queue.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#875 More detailed logging
  internal/kymacustomresource/kyma_cr_updater.go
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/state_reconciler_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#877 Logging when we ignore older element in the queue
  internal/syncqueues/priority_queue.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#879 Not recreating states after deletion
  internal/subaccountsync/state_reconciler.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#859 Documentation for sap-converged-cloud Plan Region Mappings
  docs/user/03-10-service-description.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#881 Extend logging and fix time update
  internal/subaccountsync/state_reconciler.go
  internal/syncqueues/priority_queue.go
  internal/syncqueues/priority_queue_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#882 Remove UseSmallerMachineTypes feature flag
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#860 Update docs after Reconciler removal
  docs/README.md
  docs/assets/hap-flow.drawio.svg
  docs/assets/hap-flow.svg
  docs/assets/keb-arch.drawio
  docs/assets/keb-arch.drawio.svg
  docs/assets/keb-arch.svg
  docs/contributor/01-20-swagger.md
  docs/contributor/02-30-keb-configuration.md
  docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md
  docs/contributor/02-50-orchestration.md
  docs/contributor/02-60-orchestrate-kyma-upgrade.md
  docs/contributor/02-70-orchestration-status.md
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
  docs/contributor/05-10-e2e_tests.md
  docs/contributor/07-20-subaccount-sync.md
  docs/user/01-10-architecture.md
  docs/user/01-20-target-architecture.md
  docs/user/03-10-service-description.md
  docs/user/04-30-custom-networking-configuration.md
  docs/user/05-10-provisioning-kyma-environment.md
  docs/user/05-20-deprovisioning-kyma-environment.md
  docs/user/05-40-instance-details.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#887 IAS configuration removed from `values.yaml`
  resources/keb/templates/deployment.yaml
  resources/keb/templates/secrets.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#886 Validation Tests for Sap Converged Cloud Plan Mapping
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#890 Revert "Remove UseSmallerMachineTypes feature flag (#882)"
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#888 Eu Access Whitelist Removal
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/eu_access_whitelist.yaml
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#891 Eu Access Documentation Update
  docs/contributor/03-20-eu-access.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#889 Increase maximum worker node count
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#893 Warn message added
  internal/syncqueues/priority_queue.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#884 Remove Kyma version from runtime
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/broker/upgrade_kyma.go
  common/runtime/model.go
  internal/broker/instance_update.go
  internal/fixture/fixture.go
  internal/model.go
  internal/orchestration/manager/upgrade_kyma.go
  internal/process/input/automock/creator_for_plan.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/automock/runtime_version_configurator_for_provisioning.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/enable_for_trial_step_test.go
  internal/process/provisioning/initialisation.go
  internal/process/provisioning/initialisation_test.go
  internal/process/update/automock/runtime_version_configurator_for_updating.go
  internal/process/update/init_kyma_step.go
  internal/process/update/initialisation_step.go
  internal/process/update/initialisation_step_test.go
  internal/process/update/upgrade_shoot_step.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/initialisation.go
  internal/process/upgrade_cluster/initialisation_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/process/upgrade_kyma/automock/creator_for_plan.go
  internal/process/upgrade_kyma/automock/runtime_version_configurator_for_upgrade.go
  internal/process/upgrade_kyma/initialisation.go
  internal/process/upgrade_kyma/initialisation_test.go
  internal/runtime/converter.go
  internal/runtime/converter_test.go
  internal/runtime/handler.go
  internal/runtimeversion/runtimeversion.go
  internal/runtimeversion/runtimeversion_test.go
  internal/storage/dbmodel/runtime_state.go
  internal/storage/driver/memory/runtime_state.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  resources/keb/migrations/202406260800_drop_kyma_version.down.sql
  resources/keb/migrations/202406260800_drop_kyma_version.up.sql
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#850 Prepare KEB for CN region
  cmd/broker/suite_test.go
  docs/README.md
  internal/config/provider_test.go
  internal/config/testdata/keb-config-expected.yaml
  internal/config/testdata/keb-config.yaml
  internal/config/validator.go
  internal/config/validator_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  resources/cn/cn.md
  resources/cn/sql.yaml
  resources/cn/values.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes
