Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-01, with the labels that each got.

#280 Remove trial expiration logic from update endpoint
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/expiration_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  internal/broker/client.go
  internal/broker/client_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/dto.go
  internal/expiration/handler.go
  testing/e2e/skr/keb-endpoints-test/index.js
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#308 Use kubeconfigprovider
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/broker/upgrade_kyma.go
  internal/btpmanager/credentials/manager.go
  internal/kubeconfig/provider.go
  internal/kubeconfig/provider_test.go
  internal/model.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
  internal/process/provisioning/get_kubeconfig_step.go
  internal/process/provisioning/get_kubeconfig_test.go
  internal/process/provisioning/inject_btp_operator_credentials_step.go
  internal/process/provisioning/inject_btp_operator_credentials_step_test.go
  internal/process/update/get_kubeconfig_step.go
  internal/process/upgrade_kyma/apply_cluster_configuration.go
  internal/process/upgrade_kyma/get_kubeconfig_step.go
  internal/process/upgrade_kyma/get_kubeconfig_test.go
Labels: lgtm, size/XL, area/control-plane, kind/enhancement, cla: yes

#320 Bump KEB 1.0.3
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, area/control-plane, kind/enhancement, cla: yes

#322 remove temporary featutre flag
  cmd/broker/suite_test.go
  internal/appinfo/runtime_info.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#321 Kcfgprovider kubeconfig endpoint
  cmd/broker/main.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
Labels: size/M, lgtm, area/control-plane, kind/enhancement, cla: yes

#323 update azure machines
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-region-required.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-region-required.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-region-required.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu-region-required.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params-region-required.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu-region-required.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema-region-required.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
Labels: size/L, lgtm, kind/enhancement, cla: yes

#325 Set CompassRuntimeID during runtime provisioning
  go.mod
  go.sum
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/provisioner/fake_client.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#337 Bump keb to 1.0.4
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, area/control-plane, kind/enhancement, cla: yes

#339 Revert "Bump keb to 1.0.4 (#337)"
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#341 bump to 1.1.0
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#331 Remove allowNetworkingParameters feature flag
  cmd/broker/suite_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
Labels: kind/cleanup, lgtm, size/XS, kind/enhancement, cla: yes

#348 Bump KEB images to version 1.1.1
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#346 Make gardener kubeconfig optional in SKR test
  testing/e2e/skr/gardener/client.js
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/skr-test/helpers.js
  testing/e2e/skr/skr-test/machine-type/index.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: size/L, lgtm, kind/enhancement, cla: yes

#350 default machines also outside of schema generator
  cmd/broker/provisioning_test.go
  internal/provider/azure_provider.go
  internal/provisioner/graphqlizer_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#313 Removal of Subscription Cleanup Job from KEB
  CODEOWNERS
  Makefile
  cmd/subscriptioncleanup/cloudprovider/aws.go
  cmd/subscriptioncleanup/cloudprovider/azure.go
  cmd/subscriptioncleanup/cloudprovider/factory.go
  cmd/subscriptioncleanup/cloudprovider/gcp.go
  cmd/subscriptioncleanup/cloudprovider/mocks/ProviderFactory.go
  cmd/subscriptioncleanup/job/cleaner.go
  cmd/subscriptioncleanup/job/cleaner_test.go
  cmd/subscriptioncleanup/main.go
  cmd/subscriptioncleanup/model/types.go
  go.mod
  go.sum
  scripts/generic_make_go.mk
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#359 Update OIDC params docs
  docs/user/04-10-custom-oidc-configuration.md
Labels: documentation, lgtm, area/control-plane, kind/enhancement, cla: yes

#358 Remove allowNetworkingParameters feature flag from resources
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, kind/enhancement, cla: yes

#360 Update the default machineType parameter
  docs/user/03-10-service-description.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#361 cleanup module param
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#362 Disable skr test assertions
  testing/e2e/skr/skr-test/machine-type/index.js
  testing/e2e/skr/skr-test/oidc/index.js
Labels: size/S, lgtm, kind/enhancement, cla: yes

#334 Fix cmd/broker unit test flakiness
  cmd/broker/broker_suite_test.go
  cmd/broker/expiration_test.go
  cmd/broker/last_operation_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma_test.go
  internal/reconciler/fake.go
Labels: size/L, lgtm, area/control-plane, kind/enhancement, cla: yes

#364 Service Binding
  cmd/broker/binding_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/broker/bind_create.go
  internal/broker/bind_delete.go
  internal/broker/bind_get.go
  internal/broker/broker.go
  internal/broker/services.go
  internal/broker/services_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, area/control-plane, kind/enhancement, cla: yes

#368 Fix btp operator cleanup nosecret
  internal/kubeconfig/error.go
  internal/kubeconfig/provider.go
  internal/kubeconfig/provider_test.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
Labels: size/M, kind/bug, lgtm, cla: yes

#370 Bump KEB to 1.1.2
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#373 Bump to 1.1.3
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#352 Add version validation
  .github/workflows/create-release.yaml
  docs/contributor/04-20-release.md
  scripts/python/release_label_validator.py
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#369 Remove unused issuer from RequestAuthentication
  resources/keb/templates/request-authentication.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#377 Golang update to 1.21.6
  Dockerfile.job
  Dockerfile.keb
  Dockerfile.runtimereconciler
  go.mod
  go.sum
Labels: size/S, lgtm, kind/enhancement, cla: yes

#379 refactor of Makefile and Tests execution part1
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-verify.yaml
  .golangci.yaml
  Makefile
  docs/contributor/04-10-workflows.md
  scripts/README.md
  scripts/generic_make_go.mk
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#384 KEB Configuration in a Separate File
  README.md
  docs/contributor/02-31-keb-configuration.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#387 Makefile improvments
  .github/workflows/run-eslint.yaml
  .github/workflows/run-verify.yaml
  .golangci.yml
  Makefile
Labels: size/S, lgtm, kind/enhancement, cla: yes

#389 Runtime Operations Doc Correction
  docs/user/03-20-runtime-operations.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#385 Environments Cleanup Job Doc Verification
  docs/contributor/06-20-environments-cleanup-cronjob.md
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#392 Bump cloudsql-proxy image to v1.33.16-133356bc
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#394 Make Check_GardenerCluster step timeout as an env
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  internal/process/input/input.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#396 Bump KEB to 1.1.4
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#397 dont repeat tests after merge
  .github/workflows/run-verify.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#388 Storage Tests
  go.mod
  internal/docker_helper.go
  internal/storage/driver/postsql/conflict_test.go
  internal/storage/driver/postsql/initialization_test.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/driver/postsql/orchestration_test.go
  internal/storage/driver/postsql/postsql_test.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/tests_utils.go
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#398 remove not needed code in makefile
  Makefile
Labels: size/S, lgtm, kind/enhancement, cla: yes

#378 Add gardener_config parameter to /runtimes endpoint
  cmd/broker/main.go
  common/runtime/model.go
  internal/provisioner/fake_client.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  resources/keb/files/swagger.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#400 Bump KEB to 1.1.5
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#401 Add gardener_config param to query
  common/runtime/client.go
  common/runtime/client_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#403 Bump KEB to 1.1.6
  resources/keb/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#411 Enable skr test assertions
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/skr-test/machine-type/index.js
  testing/e2e/skr/skr-test/oidc/index.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#412 Remove region required feature flags from deployment
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#414 golint remove gofmt
  .golangci.yml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#416 dry run
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#382 Kyma resource name is always as the first runtimeID
  cmd/broker/broker_suite_test.go
  cmd/broker/update_test.go
  internal/process/deprovisioning/remove_instance_step.go
Labels: size/L, kind/bug, lgtm, cla: yes
