Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-07, with the labels that each got.

#896 Remove kyma upgrade capability
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma_test.go
  go.mod
  go.sum
  internal/model.go
  internal/orchestration/handlers/cluster_handler_test.go
  internal/orchestration/handlers/cluster_retry.go
  internal/orchestration/handlers/handlers.go
  internal/orchestration/handlers/kyma_handler.go
  internal/orchestration/handlers/kyma_handler_test.go
  internal/orchestration/handlers/kyma_retry.go
  internal/orchestration/handlers/orchestration_handler.go
  internal/orchestration/handlers/orchestration_handler_test.go
  resources/keb/files/swagger.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#897 Retry kubeconfig init in SKR tests
  testing/e2e/skr/skr-test/oidc/index.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: size/S, lgtm, kind/enhancement, cla: yes

#900 Kyma orchestration processing queue removal
  cmd/broker/upgrade_kyma.go
  docs/user/03-20-runtime-operations.md
  internal/orchestration/handlers/orchestration_handler.go
  internal/orchestration/handlers/orchestration_handler_test.go
  internal/orchestration/manager/upgrade_cluster_test.go
  internal/orchestration/manager/upgrade_kyma.go
  internal/orchestration/manager/upgrade_kyma_test.go
  internal/process/steps/kyma_template.go
  internal/process/upgrade_cluster/automock/creator_for_plan.go
  internal/process/upgrade_cluster/initialisation_test.go
  internal/process/upgrade_kyma/apply_kyma_step.go
  internal/process/upgrade_kyma/automock/hyperscaler_input_provider.go
  internal/process/upgrade_kyma/automock/provisioner_input_creator.go
  internal/process/upgrade_kyma/automock/step.go
  internal/process/upgrade_kyma/automock/step_condition.go
  internal/process/upgrade_kyma/avs_maintenance.go
  internal/process/upgrade_kyma/config.go
  internal/process/upgrade_kyma/initialisation.go
  internal/process/upgrade_kyma/initialisation_test.go
  internal/process/upgrade_kyma/manager.go
  internal/process/upgrade_kyma/manager_test.go
  internal/process/upgrade_kyma/send_notification.go
  internal/process/upgrade_kyma/send_notification_test.go
  internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  internal/process/upgrade_kyma/skip_for_trial_step.go
  internal/process/upgrade_kyma/skip_for_trial_step_test.go
  internal/process/upgrade_kyma_operation.go
  internal/process/upgrade_kyma_operation_test.go
Labels: area/documentation, lgtm, size/XXL, kind/enhancement, cla: yes

#901 Update MT
  docs/user/03-10-service-description.md
  resources/cn/cn.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#904 Add missing await in skr tests
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#903 Remove upgrade Kyma operation
  cmd/broker/main.go
  internal/avs/delegator_test.go
  internal/fixture/fixture.go
  internal/model.go
  internal/orchestration/handlers/converter.go
  internal/orchestration/handlers/converter_test.go
  internal/orchestration/handlers/orchestration_handler_test.go
  internal/process/events.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
  internal/process/update/initialisation_step_test.go
  internal/runtime/converter.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/operation_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#911 Change condition for retrying kubeconfig init in SKR tests
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: size/S, lgtm, kind/enhancement, cla: yes

#907 Remove Kyma version
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/orchestration_test.go
  cmd/broker/suite_test.go
  common/orchestration/dto.go
  docs/contributor/02-30-keb-configuration.md
  internal/orchestration/handlers/kyma_handler_test.go
  internal/orchestration/manager/manager.go
  internal/orchestration/manager/upgrade_cluster.go
  internal/orchestration/manager/upgrade_cluster_test.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_kyma_resource_step_test.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/initialisation_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#910 Update docs after Kyma upgrade removal
  docs/README.md
  docs/contributor/02-50-orchestration.md
  docs/contributor/02-60-orchestrate-kyma-upgrade.md
  docs/contributor/02-70-orchestration-status.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#914 Unrecognized type of operation
  internal/model.go
  internal/storage/driver/postsql/operation.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#920 KCP CLI - List Deprovisioned Instances
  cmd/broker/deprovisioning_test.go
  internal/runtime/handler.go
  internal/storage/driver/memory/instance_archived.go
  internal/storage/driver/postsql/instance_archived.go
  internal/storage/driver/postsql/instance_archived_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#922 KCP CLI - Add created at to runtime status
  internal/runtime/handler.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#918 Using Kyma Infrastructure Manager - Phase 0
  cmd/broker/main.go
  cmd/broker/provisioning.go
  go.mod
  go.sum
  internal/broker/broker.go
  internal/kim/config.go
  internal/kim/config_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/provisioning/generate_runtime_id_step.go
  internal/process/provisioning/generate_runtime_id_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#924 Add more retries and cooldown to SKR kubeconfig initd
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: size/S, lgtm, kind/enhancement, cla: yes

#926 Test provisioning process with KIM
  cmd/broker/provisioning_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#925 Labels for Runtime CR - stage 1 of KIM integration
  cmd/broker/provisioning_test.go
  go.mod
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#928 Add missing await in SKR test
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#929 Add image builder workflow for KEB image
  .github/workflows/pull-btp-manager-build-ga.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#932 Add image builder workflow for expirator image
  .github/workflows/pull-keb-build-ga.yaml
  .github/workflows/pull-keb-expirator-build-ga.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#937 Setting valid Kyma Resource Name in a new step
  cmd/broker/deprovisioning_test.go
  cmd/broker/provisioning.go
  internal/process/provisioning/apply_kyma_step.go
  internal/process/provisioning/create_kyma_name_step.go
  internal/process/provisioning/create_kyma_name_step_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/generate_runtime_id_step.go
  internal/process/steps/lifecycle_manager.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#938 Shoot data for GCP provider
  internal/provider/aws.go
  internal/provider/common.go
  internal/provider/gcp.go
  internal/provider/gcp_provider.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#939 Removing unused data
  cmd/broker/provisioning.go
  internal/process/provisioning/generate_runtime_id_step.go
  internal/process/provisioning/generate_runtime_id_step_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#941 KIM integration - AWS trial
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/trial-regions.yaml
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#933 Create Runtime CR - KIM integration - phase 1
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#942 KIM Integration - GCP Trial plan
  internal/process/provisioning/create_runtime_resource_step.go
  internal/provider/aws.go
  internal/provider/aws_provider.go
  internal/provider/gcp.go
  internal/provider/gcp_provider.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#943 KIM integration - Azure trial plan
  internal/process/provisioning/create_runtime_resource_step.go
  internal/provider/azure.go
  internal/provider/zones.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#950 KIM integration - assertions for workers
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#951 KIM Integration - shoot name and networking for basic plans
  internal/process/input/input.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/aws.go
  internal/provider/model.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#957 Zones for new regions
  internal/provider/sap-converged-cloud_provider.go
  internal/provider/sap-converged-cloud_provider_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#959 Configuration variables fixed
  resources/keb/templates/deployment.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#961 KIM Integration - add label indicating what drives provisioning
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  resources/keb/templates/rbac.yaml
Labels: lgtm, kind/enhancement, cla: yes

#963 Add KEB jobs image builders
  .github/workflows/pull-keb-archiver-job-build-ga.yaml
  .github/workflows/pull-keb-cleanup-build-ga.yaml
  .github/workflows/pull-keb-deprovision-retrigger-job-build-ga.yaml
  .github/workflows/pull-keb-runtime-reconciler-job-build-ga.yaml
  .github/workflows/pull-keb-subaccount-cleanup-job-build-ga.yaml
  .github/workflows/pull-keb-subaccount-sync-build-ga.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#955 KIM Integration - test refactor with more flexible fixtures
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#966 Add release workflow without prow
  .github/workflows/create-release-without-prow.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#965 KIM Integration - handle existing Runtime CR during retry
  internal/kim/config.go
  internal/process/provisioning/create_kyma_name_step.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#968 KIM Integration - test for Kyma name corrected
  internal/process/provisioning/create_kyma_name_step_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes
