Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-04, with the labels that each got.

#603 Fix promote workflow
  .github/workflows/promote-keb-to-dev.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#605 Add promote KEB to dev workflow docs
  docs/contributor/04-10-workflows.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#604 metrics improvements
  internal/error/errors.go
  internal/metrics/operations_collector.go
  internal/metrics/operations_db_collector.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
  internal/model.go
  resources/keb/files/business-metrics-dashboardv2.json
  resources/keb/templates/business-metrics-dashboardv2.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#607 Expirator - an app which can be used as Trial/Free cleanup job
  cmd/expiratior/main.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#615 Fix expirator directory
  cmd/expirator/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#617 dashboard update
  resources/keb/files/dashboardv2.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#616 Configure expirator
  cmd/expirator/main.go
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
  scripts/bump_keb_chart.sh
  scripts/create_bump_keb_chart_pr.sh
  scripts/create_scan_config.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#614 metrics refactor
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/metricsv2/instances_collector.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operation_duration.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/process/staged_manager.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#623 fix metrics time in tests
  internal/metricsv2/operations_stats_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#608 One freemium per global account
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/freemium_whitelist.yaml
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/storage/dbmodel/operation.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/memory/instance_archived.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/instance_archived.go
  internal/storage/driver/postsql/instance_archived_test.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/whitelist/test/whitelist.yaml
  internal/whitelist/whitelisted_globalaccounts.go
  internal/whitelist/whitelisted_globalaccounts_test.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#625 Sleep time and label are passed to updater constructor
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#624 Fake server with sorting corrected
  internal/cis/fake_server.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#613 Update the docs README file
  docs/README.md
  docs/contributor/04-10-workflows.md
  docs/contributor/04-20-release.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#630 Bump github.com/docker/docker from 25.0.4+incompatible to 26.0.0+inco…
  go.mod
  go.sum
  internal/docker_helper.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#632 Bump Go to 1.22.2
  go.mod
  go.sum
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#631 Free cleanup job
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#634 Adjust release workflow to the new way of promoting KEB
  .github/workflows/create-release.yaml
  scripts/create_bump_keb_chart_pr.sh
  scripts/create_bump_pr.sh
  scripts/upload_assets.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#642 Enhance waiting for commit statuses in release workflow
  .github/workflows/check-commit-status/action.yaml
  .github/workflows/create-release.yaml
  scripts/create_scan_config.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#644 Secret template for new secret
  resources/keb/templates/secrets.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#650 Bump appVersion when promoting KEB
  .github/workflows/promote-keb-to-dev.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#640 Documentation for `subaccount-sync` app
  docs/contributor/07-20-subaccount-sync.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#653 Retry Overrides_From_Secrets_And_Config_Step operation
  internal/process/provisioning/secret_cm_overrides.go
  internal/process/upgrade_kyma/secret_cm_overrides.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#655 Remove trial cleanup job build
  .github/workflows/create-release.yaml
  docs/contributor/04-20-release.md
  scripts/check_artifacts_existence.sh
  scripts/create_scan_config.sh
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#657 Missing placeholder in log message
  internal/process/deprovisioning/btp_operator_cleanup.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#460 Synchronizing betaEnabled attribute with Kyma resource
  cmd/subaccountsync/main.go
  go.mod
  internal/subaccountsync/cis_accounts.go
  internal/subaccountsync/cis_events.go
  internal/subaccountsync/cis_model.go
  internal/subaccountsync/config.go
  internal/subaccountsync/event_window.go
  internal/subaccountsync/event_window_test.go
  internal/subaccountsync/informer.go
  internal/subaccountsync/metrics.go
  internal/subaccountsync/rate_limited_client.go
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/state_reconciler_test.go
  internal/subaccountsync/subaccount_sync_service.go
  internal/subaccountsync/testdata/events.json
  internal/subaccountsync/testdata/subaccounts.json
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: kind/feature, lgtm, size/XXL, cla: yes

#660 Reference to kyma version deployment corrected
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#662 Fix subaccount sync deployment
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#665 Change expirator log message
  cmd/expirator/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#668 Fix ControlPlaneFailureTolerance and max surge for sap CC
  internal/process/input/builder.go
  internal/provider/sap-converged-cloud_provider.go
Labels: size/S, kind/bug, lgtm, cla: yes

#664 Add australiaeast azure region
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
Labels: size/L, kind/feature, lgtm, cla: yes

#672 Make Kyma resource deletion timeout configurable
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#666 Fixing CIS access for `subaccount-sync`
  internal/subaccountsync/subaccount_sync_service.go
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#669 Uniform Logger
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/update.go
  cmd/runtimereconciler/main.go
  common/deprovision/client.go
  internal/archive/service.go
  internal/kymacustomresource/kyma_cr_updater.go
  internal/process/staged_manager.go
  internal/storage/driver/postsql/operation.go
  internal/storage/storage.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#654 Removed Println Invocations
  cmd/archiver/main.go
  cmd/broker/main.go
  cmd/environmentscleanup/main.go
  cmd/runtimereconciler/main.go
  common/setup/builder.go
  internal/model.go
  internal/provisioner/client.go
  internal/provisioner/client_test.go
Labels: size/M, kind/bug, lgtm, cla: yes

#679 Fix archiving feature flag name
  cmd/broker/main.go
  resources/keb/templates/deployment.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#675 Remove IncludeNewMachineTypesInSchema feature flag
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  internal/appinfo/runtime_info.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/aws/aws-schema-additional-params-reduced.json
  internal/broker/testdata/aws/aws-schema-reduced.json
  internal/broker/testdata/aws/update-aws-schema-additional-params-reduced.json
  internal/broker/testdata/aws/update-aws-schema-reduced.json
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input_test.go
  internal/process/provisioning/check_cluster_configuration_test.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provider/aws_provider.go
  internal/provider/azure_provider.go
  internal/provider/gcp_provider.go
  internal/provider/sap-converged-cloud_provider.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#681 Add gitleaks workflow
  .github/workflows/pull-gitleaks.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#682 Do not break archiver loop in case of an error
  internal/archive/archive.go
  internal/archive/service.go
  utils/archiver/kyma-environment-broker-archiver.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#685 Disable sync kubeconfig
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#686 Archiver continues on error processing
  internal/archive/service.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#674 More debug logs for event tracking
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#690 Handle error insert archived instance in the archiver
  internal/archive/service.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#695 Add debug logs for updater
  cmd/subaccountsync/main.go
  internal/kymacustomresource/kyma_cr_updater.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#697 Handling not boolean label
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/state_reconciler_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#698 Passing logger to updater
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#701 Added Missing Upgrade Metrics
  internal/metricsv2/operations_stats.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#703 Timeout for k8s operations
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#707 Close response body after cluster deletion
  internal/reconciler/client.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#689 Fix runtimes endpoint to handle instances_archived
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/archive/archive.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  resources/keb/migrations/202404240900_instance_archived_londer_instanceid.down.sql
  resources/keb/migrations/202404240900_instance_archived_londer_instanceid.up.sql
Labels: size/L, lgtm, kind/enhancement, cla: yes

#710 Configure scraping for sub sync
  resources/keb/templates/policy.yaml
  resources/keb/templates/service-monitor.yaml
  resources/keb/templates/service.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#711 Labels changed
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#712 Bump github.com/99designs/gqlgen from 0.17.28 to 0.17.45
  go.mod
  go.sum
  internal/provisioner/fake_client.go
  internal/provisioner/graphqlizer_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#715 Last Error Only
  internal/avs/delegator.go
  internal/process/deprovisioning/avs_evaluations.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/delete_gardener_cluster.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/ias_deregistration.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/operation_manager.go
  internal/process/staged_manager.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#716 Initial `subaccount-sync` dashboard
  resources/keb/files/subaccount-sync-dashboard.json
  resources/keb/templates/subaccount-sync-dashboard.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#714 Metrics with time in the queue
  internal/subaccountsync/metrics.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#667 logs, for testing metrics
  internal/metrics/operations_db_collector.go
  internal/metricsv2/debuger.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#720 Missing Nil Check
  internal/process/staged_manager.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#722 Avoided Error Logs for Recoverable Cases in EDP Step
  internal/process/operation_manager.go
  internal/process/provisioning/edp_registration.go
  internal/process/staged_manager.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#721 Extending metrics for `subaccount-sync` app
  internal/subaccountsync/metrics.go
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/subaccount_sync_service.go
  internal/syncqueues/priority_queue.go
Labels: size/M, lgtm, kind/enhancement, cla: yes
