Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-05, with the labels that each got.

#719 Handle all finished operation events for metrics
  internal/metrics/operations_db_collector.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/process/events.go
  internal/process/staged_manager.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
  utils/archiver/kyma-environment-broker-archiver.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#726 Metrics for `subaccount-sync` continued
  internal/subaccountsync/metrics.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#706 Get LastOperation endpoint without upgrades operations
  internal/broker/instance_last_operation.go
  internal/broker/instance_last_operation_test.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/L, kind/bug, lgtm, cla: yes

#729 Corrected Preview Plan Id in Metrics
  internal/metricsv2/operations_stats.go
Labels: kind/bug, lgtm, cla: yes

#732 Dashboard for `subaccount-sync` extended
  internal/subaccountsync/state_reconciler.go
  resources/keb/files/subaccount-sync-dashboard.json
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#737 Archiver - disable deletion on flag
  internal/archive/service.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#728 Disable Argo Pruning
  resources/keb/templates/app-config.yaml
  resources/keb/templates/authorization-policy.yaml
  resources/keb/templates/business-metrics-dashboard.yaml
  resources/keb/templates/business-metrics-dashboardv2.yaml
  resources/keb/templates/dashboard.yaml
  resources/keb/templates/dashboardv2.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/gardener-dashboard.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/keb-migrations.yaml
  resources/keb/templates/policy.yaml
  resources/keb/templates/profiler-pvc.yaml
  resources/keb/templates/rbac.yaml
  resources/keb/templates/request-authentication.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/secrets.yaml
  resources/keb/templates/service-monitor.yaml
  resources/keb/templates/service.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-dashboard.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/templates/virtualservice.yaml
Labels: size/M, kind/bug, lgtm, cla: yes

#705 Make go linter timeout configurable
  .github/workflows/run-verify.yaml
  Makefile
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#740 Tuning `subaccount-sync` dashboard
  internal/subaccountsync/state_reconciler.go
  resources/keb/files/subaccount-sync-dashboard.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#741 Free provisioning response
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#724 operation result metrics test
  cmd/broker/broker_suite_test.go
  cmd/broker/metrics_test.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_result_test.go
  internal/metricsv2/operations_stats_test.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/postsql/operation.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#743 add metrics for error panel dashboard
  resources/keb/files/dashboardv2.json
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#744 Registering DB metrics
  cmd/subaccountsync/main.go
  internal/subaccountsync/config.go
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/subaccount_sync_service.go
  resources/keb/files/subaccount-sync-dashboard.json
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#746 Debug log for tracking state deletion
  internal/subaccountsync/state_reconciler.go
Labels: lgtm, kind/enhancement, cla: yes

#649 More informative messages in BTP Cleanup Step
  internal/process/deprovisioning/btp_operator_cleanup.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#754 Removing CIS request totals from dashboard
  resources/keb/files/subaccount-sync-dashboard.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#751 Disable reconciler steps
  cmd/broker/provisioning.go
  cmd/broker/update.go
  cmd/broker/upgrade_kyma.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#758 Bump Go to 1.22.3
  go.mod
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#761 Sum by service for informer panel
  resources/keb/files/subaccount-sync-dashboard.json
Labels: size/S, lgtm, kind/enhancement, cla: yes

#757 Leaving EDP Logs Level Selection to Manager
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/main.go
  internal/edp/client.go
  internal/edp/client_fake.go
  internal/edp/client_test.go
  internal/process/deprovisioning/automock/edp_client.go
  internal/process/deprovisioning/edp_deregistration.go
  internal/process/deprovisioning/edp_deregistration_test.go
  internal/process/operation_manager.go
  internal/process/provisioning/automock/edp_client.go
  internal/process/provisioning/edp_registration.go
  utils/edp-registrator/main.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#763 Features/edp logger context
  internal/edp/client.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#753 Add APIServerURL to response labels
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/response_labels.go
  internal/broker/response_labels_test.go
  internal/kubeconfig/automock/kc_builder.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/handler.go
  internal/kubeconfig/handler_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#764 EDP Log Levels Corrections
  internal/process/deprovisioning/deregister_cluster.go
  internal/process/deprovisioning/edp_deregistration.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#768 New metrics signalling dry run mode
  internal/subaccountsync/metrics.go
  internal/subaccountsync/subaccount_sync_service.go
Labels: lgtm, kind/enhancement, cla: yes

#770 Metrics scraping documentation for `subaccount-sync`
  docs/contributor/07-20-subaccount-sync.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#777 Bump k8s
  go.mod
  go.sum
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#778 Add config to disable AVS steps
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#769 Changing Eval State Only if Changed in AVS
  internal/avs/delegator.go
  internal/avs/delegator_test.go
Labels: size/S, kind/bug, lgtm, cla: yes

#780 Delete old metrics
  cmd/broker/main.go
  internal/metrics/instances_collector.go
  internal/metrics/metrics.go
  internal/metrics/operation_duration.go
  internal/metrics/operation_result.go
  internal/metrics/operations_collector.go
  internal/metrics/operations_db_collector.go
  internal/metrics/step_result.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#775 Remove overrides and reconciler steps
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/expiration_test.go
  cmd/broker/main.go
  cmd/broker/metrics_test.go
  cmd/broker/orchestration_test.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  cmd/broker/upgrade_kyma.go
  cmd/broker/upgrade_kyma_test.go
  internal/process/deprovisioning/check_cluster_deregistration.go
  internal/process/deprovisioning/check_cluster_deregistration_test.go
  internal/process/deprovisioning/deregister_cluster.go
  internal/process/deprovisioning/deregister_cluster_test.go
  internal/process/provisioning/btp_operator_overrides.go
  internal/process/provisioning/check_cluster_configuration.go
  internal/process/provisioning/check_cluster_configuration_test.go
  internal/process/provisioning/create_cluster_configuration.go
  internal/process/provisioning/create_cluster_configuration_step_test.go
  internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  internal/process/provisioning/initialisation.go
  internal/process/provisioning/secret_cm_overrides.go
  internal/process/provisioning/secret_cm_overrides_test.go
  internal/process/update/apply_reconciler_configuration.go
  internal/process/update/btp_operator_overrides.go
  internal/process/update/conditions.go
  internal/process/update/sc_migration_check_step.go
  internal/process/upgrade_kyma/apply_cluster_configuration.go
  internal/process/upgrade_kyma/btp_operator_overrides.go
  internal/process/upgrade_kyma/check_cluster_configuration.go
  internal/process/upgrade_kyma/conditions.go
  internal/process/upgrade_kyma/initialisation.go
  internal/process/upgrade_kyma/secret_cm_overrides.go
  internal/process/upgrade_kyma/secret_cm_overrides_test.go
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#785 Adjust time sleeps and pooling intervals in metrics tests
  internal/metricsv2/operations_result_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#787 Logging 500 Errors for Kubeconfig Handler
  internal/kubeconfig/handler.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#782 Remove kcp reconciliations from skr test
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  testing/e2e/skr/skr-test/oidc/index.js
  testing/e2e/skr/skr-test/provision/deprovision-skr.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/trial-suspension-test/helpers.js
Labels: size/M, lgtm, kind/enhancement, cla: yes
