Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-09, with the labels that each got.

#1081 Add runtime_config to query
  common/runtime/client.go
  common/runtime/client_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1078 Change skr test to use runtime CR if needed
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1084 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1086 Decompose CreateRuntimeResource step
  internal/process/provisioning/create_runtime_resource_step.go
  internal/provider/provider_values.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1074 dont return error if there was context update to expired instance
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1093 Blocking Sap Converged Cloud with Specific Message
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, kind/feature, lgtm, cla: yes

#1094 KIM Integration - using imported constants
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/steps/runtime_resource.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1097 Support only me-central2 region for cf-sa30
  common/hyperscaler/hyperscaler_type.go
  internal/assuredworkloads/assured_workloads.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/provider/gcp.go
  internal/provider/gcp_provider.go
  internal/provider/gcp_provider_test.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#1090 Kim update process
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/broker/update_test.go
  internal/broker/instance_update.go
  internal/model.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/steps/runtime_resource.go
  internal/process/update/check_step.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  internal/process/update/upgrade_shoot_step.go
  internal/process/update/upgrade_shoot_step_test.go
Labels: lgtm, size/XL, kind/enhancement, cla: yes

#1103 Create Assured Workloads documentation
  docs/contributor/03-25-assured-workloads.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#1106 Use Runtime CR to create a kubeconfig
  cmd/broker/main.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1104 KIM integration - fixes and improvements for `runtime_config` query parameter
  internal/runtime/handler.go
  internal/runtime/handler_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1108 feature flag -> subaccount movement enable as true
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1110 add logs to subaccount movement
  cmd/broker/main.go
  internal/broker/instance_update.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1111 Do not delete instances and binding for free expirations
  internal/process/deprovisioning/btp_operator_cleanup.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1115 Move subaccount feature flag to different section
  resources/keb/values.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1114 Wait for runtime to be ready in update process
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1113 Migrate e2e test from control-plane
  .github/workflows/build-e2e-provisioning-test-image.yaml
  testing/e2e/provisioning/Dockerfile
  testing/e2e/provisioning/Makefile
  testing/e2e/provisioning/README.md
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
  testing/e2e/provisioning/pkg/client/broker/broker_client.go
  testing/e2e/provisioning/pkg/client/broker/model.go
  testing/e2e/provisioning/pkg/client/broker/upgrade_broker_client.go
  testing/e2e/provisioning/pkg/client/runtime/runtime_client.go
  testing/e2e/provisioning/pkg/client/v1_client/configmap.go
  testing/e2e/provisioning/pkg/client/v1_client/secret.go
  testing/e2e/provisioning/test/e2e_provisioning_test.go
  testing/e2e/provisioning/test/e2e_suspension_test.go
  testing/e2e/provisioning/test/e2e_upgrade_test.go
  testing/e2e/provisioning/test/test_suite.go
  testing/e2e/provisioning/test/upgrade_test_suite.go
Labels: area/documentation, lgtm, size/XXL, kind/enhancement, cla: yes

#1121 Check runtime delay to 10 sec
  internal/process/steps/runtime_resource.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1109 Fix AVS disabled flag for external eval
  cmd/broker/provisioning.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1123 KIM Integration - provisioner client removed from `runtime reconciler`
  cmd/runtimereconciler/main.go
  internal/btpmanager/credentials/manager.go
  internal/btpmanager/credentials/manager_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1122 Fix imports in e2e tests
  testing/e2e/provisioning/Dockerfile
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
  testing/e2e/provisioning/pkg/client/broker/broker_client.go
  testing/e2e/provisioning/test/test_suite.go
  testing/e2e/provisioning/test/upgrade_test_suite.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1124 Environment cleanup job does not call provisioner
  cmd/environmentscleanup/main.go
  common/setup/builder.go
  docs/contributor/06-20-environments-cleanup-cronjob.md
  internal/environmentscleanup/automock/ProvisionerClient.go
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1127 Do not retry deprovisioning if Kyma resource was not deleted
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1129 KIM Integration - removal of the `managedFields` key in `metadata`
  internal/runtime/handler.go
  internal/runtime/handler_test.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1130 Use runtime ID from Infrastructure Manager
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1131 KIM integration - safer casting during `managedFields` removal
  internal/runtime/handler.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1136 KIM Integration - config referring to removed variable deleted
  cmd/runtimereconciler/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1138 Remove provisioner dependencies from e2e provisioning test
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
  testing/e2e/provisioning/pkg/client/runtime/runtime_client.go
  testing/e2e/provisioning/test/test_suite.go
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#1143 KIM integration - skip volume type and size for SAP converged cloud plan
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/provider_values.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1141 Improve KEB chart install test
  .github/workflows/pull-build-images.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  .github/workflows/run-keb-chart-install-tests.yaml
  docs/contributor/04-10-workflows.md
  scripts/wait_for_images.sh
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1150 Update dependencies
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1155 subaccount movement tests
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1151 Kyma Bindings Based on Token Requests - Create Endpoint
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bindings/bindings_manager.go
  internal/broker/bindings/bindings_manager_test.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/kubeconfig.go
  internal/kubeconfig/provider.go
  internal/ptr/ptr.go
Labels: kind/feature, lgtm, size/XL, cla: yes

#1163 `setup-envtest` workaround
  envtest.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1161 update expire instance
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1166 Cleaning envtest setup files
  clean-envtest-binaries.sh
  internal/broker/bind_create_test.go
  internal/btpmanager/credentials/manager_test.go
  internal/kubeconfig/provider_test.go
  internal/test_utils.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1171 KIM Integration - additional logs
  internal/process/deprovisioning/delete_runtime_resource_step.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1173 KIM Integration - return from delete resource step with success when resource already deleted
  internal/process/deprovisioning/delete_runtime_resource_step.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1175 Fix typo
  internal/broker/plans.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema.json
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1178 KIM Integration - setting default values - fix
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1160 Kyma Binding with Gardener's Adminkubeconfig
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  common/gardener/fake.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bindings/bindings_manager.go
  internal/broker/bindings/bindings_manager_test.go
  internal/broker/bindings/gardener_request_bindingmanager.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1180 Extend binding create endpoint
  internal/broker/bind_create_test.go
  internal/broker/bindings/bindings_manager.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1184 Add SKR binding test
  docs/contributor/05-10-e2e_tests.md
  testing/e2e/skr/Makefile
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/package.json
  testing/e2e/skr/skr-binding-test/index.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1158 Label CRs with new global account id
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/broker.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/k8s/gvk.go
  internal/k8s/kyma_labels.go
  internal/k8s/metadata.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1190 KIM Integration removal of unused function
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1153 Update expiration doc
  docs/README.md
  docs/contributor/03-30-trial-and-free-expiration.md
  docs/contributor/03-30-trial-expiration.md
  docs/contributor/04-10-workflows.md
  docs/contributor/06-40-trial-cleanup-cronjob.md
  docs/user/02-10-broker-endpoints.md
  testing/e2e/provisioning/README.md
Labels: documentation, size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1188 Increase retry timeout in Inject BTP Operator Credentials step
  internal/process/provisioning/inject_btp_operator_credentials_step.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1192 Move subaccount expired
  cmd/broker/expiration_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1193 Add logs for move account and fix typo
  cmd/broker/main.go
  internal/broker/broker.go
  internal/broker/instance_update.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1201 Fix wrong namespace
  internal/broker/broker.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1186 Docs and Requests for Create Binding
  docs/user/05-60-kyma-bindings.md
  requests/bindings/create-adminkubeconfig.http
  requests/bindings/create-tokenrequest.http
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1206 KIM Integration - safer configuration parsing
  internal/broker/kim_config.go
  internal/broker/kim_config_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1194 Define better RBAC roles
  resources/keb/templates/rbac.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1210 fix order of clients
  cmd/broker/main.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1212 Use Gardener in SKR binding test
  docs/contributor/05-10-e2e_tests.md
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/skr-binding-test/index.js
  testing/e2e/skr/utils/index.js
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1217 Add auto enable auto-merge PR
  .github/workflows/auto-merge.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1216 Dependencies Update
  go.mod
  go.sum
  internal/process/provisioning/create_runtime_resource_step.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1218 KIM Integration - more concise step implementation
  internal/process/provisioning/create_runtime_resource_step.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1215 Prepare for tide removal
  .github/workflows/create-release.yaml
  .github/workflows/label-validator.yml
  .github/workflows/pr-checks.yaml
  .github/workflows/run-eslint.yaml
  .github/workflows/run-govulncheck.yaml
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-verify.yaml
  scripts/label_validator.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1219 Update workflow docs
  docs/contributor/04-10-workflows.md
Labels: size/M, area/documentation, kind/enhancement, cla: yes

#1221 Disable tracing for label validator
  scripts/label_validator.sh
Labels: size/XS, kind/enhancement, cla: yes

#1224 Update bind create response
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes
