Repository kyma-project/kyma-environment-broker, pull requests merged in 2024-11, with the labels that each got.

#1400 Remove unused env variables from KEB deployment
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1402 Delete unused configurations from KEB
  cmd/broker/main.go
  internal/orchestration/config.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1403 Test
  cmd/broker/main.go
Labels: size/XS, kind/enhancement, cla: yes

#1405 wip
  cmd/broker/main.go
Labels: size/XS, cla: yes

#1406 Add binding cleanup job to sec file
  scripts/create_scan_config.sh
Labels: size/XS, kind/enhancement, cla: yes

#1393 Labeling custom resources unified
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  internal/broker/instance_update_test.go
  internal/broker/labeler.go
  internal/customresources/gvk.go
  internal/customresources/gvk_test.go
  internal/customresources/labels.go
  internal/k8s/gvk.go
  internal/k8s/kyma_labels.go
  internal/model.go
  internal/process/provisioning/apply_kyma_step_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/steps/labeling.go
  internal/process/steps/lifecycle_manager.go
  internal/provider/provider_values.go
Labels: size/XL, kind/enhancement, cla: yes

#1413 Fix Service Binding Cleanup Job
  internal/broker/client.go
  internal/servicebindingcleanup/service.go
  internal/servicebindingcleanup/service_test.go
Labels: size/M, kind/enhancement

#1397 Add tutorial for SI and SB provisioning through Provisioning API
  docs/contributor/06-40-trial-free-cleanup-cronjobs.md
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
  docs/contributor/06-70-service-binding-cleanup-cronjob.md
  docs/user/05-70-manage-kyma-environment-through-cis-provisioning-service.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1416 Adjust values.yaml
  resources/keb/values.yaml
Labels: size/XS, kind/enhancement, cla: yes

#1414 Auto merge chart and images bump
  .github/workflows/create-release.yaml
  scripts/merge_pr.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1422 Update release docs
  docs/assets/release.drawio.svg
  docs/contributor/04-20-release.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#1423 Create and promote release pipeline
  .github/workflows/create-and-promote-release.yaml
  .github/workflows/create-release.yaml
  .github/workflows/promote-keb-to-dev.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1426 Watch added to RBAC
  resources/keb/templates/rbac.yaml
Labels: kind/bug, size/XS, cla: yes

#1425 Add validation in promotion workflow
  .github/workflows/promote-keb-to-dev.yaml
Labels: size/S, kind/enhancement, cla: yes

#1429 Debugging timeout in `CreateRuntimeResource` step
  internal/process/steps/runtime_resource.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1431 Timeout triggering corrected
  internal/process/staged_manager.go
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1438 Update workflow docs
  docs/contributor/04-10-workflows.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1440 Deprovision Existing Kyma in First Steps of Provisioning E2E Test
  docs/contributor/05-10-e2e_tests.md
  testing/e2e/skr/provisioning-service-test/.env.template
  testing/e2e/skr/provisioning-service-test/cmd/provisioning_service_test.go
  testing/e2e/skr/provisioning-service-test/internal/model.go
  testing/e2e/skr/provisioning-service-test/internal/provisioning_client.go
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1442 Add check if any PR was merged during release
  .github/workflows/create-release.yaml
Labels: size/S, kind/enhancement, cla: yes

#1447 Add more check for PR's merged during release
  .github/workflows/create-release.yaml
Labels: size/S, kind/enhancement, cla: yes

#1401 Metrics for bindings
  cmd/broker/binding_test.go
  cmd/broker/bindings_envtest_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/metrics_test.go
  cmd/broker/suite_test.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_delete.go
  internal/metricsv2/bind.go
  internal/metricsv2/metrics.go
  internal/metricsv2/operations_result.go
  internal/metricsv2/operations_result_test.go
  internal/metricsv2/operations_stats.go
  internal/metricsv2/operations_stats_test.go
  internal/model.go
  internal/storage/dbmodel/binding.go
  internal/storage/driver/memory/binding.go
  internal/storage/driver/postsql/binding.go
  internal/storage/driver/postsql/binding_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/L, kind/enhancement, cla: yes

#1448 Add missing tokens to release workflow
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1441 SB - Creation in progress cases
  cmd/broker/binding_test.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_get.go
  internal/broker/bind_get_test.go
  internal/fixture/fixture.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1450 Add new versions of diagrams
  docs/assets/binding_delete_flow.drawio.svg
  docs/assets/bindings-create-flow.drawio
  docs/assets/bindings-create-flow.drawio.svg
  docs/assets/bindings-delete-flow.drawio
  docs/assets/bindings-delete-flow.drawio.svg
  docs/assets/bindings-get-flow.drawio
  docs/assets/bindings-get-flow.drawio.svg
  docs/assets/bindings_create_flow.drawio.svg
  docs/assets/bindings_get_flow.drawio.svg
Labels: size/L, area/documentation, kind/enhancement, cla: yes

#1452 Fix unbind histogram update
  internal/metricsv2/bind.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1458 Add the source files for the diagrams on bindings
  docs/assets/bindings_create_flow.drawio
  docs/assets/bindings_delete_flow.drawio
  docs/assets/bindings_get_flow.drawio
Labels: size/XL, kind/enhancement, cla: yes

#1459 SB - diagram update
  docs/assets/bindings_create_flow.drawio
  docs/assets/bindings_create_flow.drawio.svg
  docs/assets/bindings_get_flow.drawio
  docs/assets/bindings_get_flow.drawio.svg
Labels: size/L, kind/enhancement

#1465 Fix Service Binding metric name
  internal/metricsv2/bind.go
Labels: size/XS, kind/enhancement, cla: yes

#1470 Additional Test Case for Invalidating a Kubeconfig
  cmd/broker/bindings_envtest_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1466 Fix tutorial for SI and SB provisioning through Provisioning API
  docs/user/05-70-manage-kyma-environment-through-cis-provisioning-service.md
Labels: size/M, area/documentation, lgtm, kind/enhancement, cla: yes

#1461 Environments cleanup job removes Runtime CRs
  cmd/environmentscleanup/main.go
  common/setup/builder.go
  docs/contributor/06-20-environments-cleanup-cronjob.md
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
  utils/kyma-environments-cleanup-job/apply.sh
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1474 Disable Provisioner in deprovisioning process
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1471 Environment cleanup job sanity check
  common/setup/builder.go
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1479 Revert "Bump jsonpath-plus and @kubernetes/client-node in /testing/e2…
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
Labels: kind/bug, size/XXL, cla: yes

#1482 Remove the mention of AWS
  docs/assets/metrics.drawio
  docs/assets/metrics.drawio.svg
  docs/assets/metrics.svg
  docs/assets/target-keb-arch.drawio
  docs/assets/target-keb-arch.drawio.svg
  docs/assets/target-keb-arch.svg
  docs/user/01-20-target-architecture.md
  docs/user/03-20-runtime-operations.md
  docs/user/05-70-manage-kyma-environment-through-cis-provisioning-service.md
  docs/user/06-10-metrics.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1486 Corrected Limit Mention to Describe Non-expired Bindings
  docs/user/05-60-kyma-bindings.md
Labels: area/documentation, size/XS, kind/enhancement, cla: yes

#1473 Additional Logging in Workers
  cmd/broker/deprovisioning.go
  cmd/broker/provisioning.go
  cmd/broker/update.go
  cmd/broker/upgrade_cluster.go
  internal/broker/broker.go
  internal/orchestration/handlers/cluster_handler_test.go
  internal/orchestration/handlers/orchestration_handler_test.go
  internal/process/queue.go
  internal/process/queue_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1477 Fail deprovisioning if Runtime CR exists despite removal attempt
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
Labels: kind/bug, size/XS, cla: yes

#1490 Format Specified Correction
  internal/process/queue.go
  internal/process/queue_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1460 `betaEnabled` and `usedForProduction` on `runtimes` endpoint
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  common/runtime/model.go
  internal/appinfo/runtime_info_test.go
  internal/model.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/dbmodel/instance.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/storage.go
Labels: size/XL, kind/enhancement, cla: yes

#1491 KEB Errors improvements v1
  common/runtime/model.go
  internal/edp/errors.go
  internal/error/errors.go
  internal/error/errors_test.go
  internal/error/not_found_error.go
  internal/error/temporary_error.go
  internal/metricsv2/metrics.go
  internal/process/operation_manager.go
  internal/process/operation_manager_test.go
  internal/process/provisioning/apply_kyma_step.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/edp_registration.go
  internal/process/provisioning/start_step.go
  internal/process/staged_manager.go
  internal/provisioner/client.go
  internal/provisioner/client_test.go
  internal/runtime/converter.go
  internal/storage/dberr/errors.go
Labels: size/L, kind/enhancement, cla: yes

#1492 Fix runtimes endpoint for suspended filter
  internal/runtime/handler.go
  internal/storage/dbmodel/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/read.go
Labels: size/M, kind/bug, lgtm, cla: yes

#1498 Save region in the create runtime resource step
  internal/process/provisioning/create_runtime_resource_step.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1505 Add missing filter for suspended instances on runtimes endpoint
  internal/storage/postsql/read.go
Labels: kind/bug, size/XS, cla: yes

#1502 Env cleanup job works on shoot names
  internal/environmentscleanup/service.go
  internal/environmentscleanup/service_test.go
  internal/storage/driver/memory/instance.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1510 Make Check_RuntimeResource_Deletion step timeout configurable
  cmd/broker/deprovisioning.go
  cmd/broker/suite_test.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step_test.go
  internal/process/input/input.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/M, kind/enhancement, cla: yes

#1509 Remove unnecessary database call
  internal/environmentscleanup/service.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1481 Second deprovisioning uses information where should go the deprovisio…
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/suite_test.go
  internal/model.go
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/deprovisioning/delete_runtime_resource_step_test.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/deprovisioning/remove_runtime_test.go
  internal/provisioner/fake_client.go
  internal/suspension/handler.go
Labels: size/L, kind/enhancement, cla: yes
