Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-03, with the labels that each got.

#1812 Timeouts in EDP and deprovisioning steps using `RetryOperations` helper function
  internal/process/deprovisioning/edp_deregistration.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/operation_manager.go
  internal/process/provisioning/edp_registration.go
Labels: size/M, lgtm, kind/enhancement

#1809 Add documentation for build runtime plans
  docs/user/03-10-service-description.md
Labels: area/documentation, size/XS, kind/enhancement, cla: yes

#1811 HAP 0.0.12 Refactoring and Plugging Parsing in KEB Main
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/parser/main.go
  cmd/parser/parse.go
  cmd/parser/parse_test.go
  cmd/parser/root.go
  cmd/parser/rules/rules-final.yaml
  cmd/parser/rules/rules.yaml
  cmd/parser/rules/test-cases.yaml
  cmd/parser/rules/wrong_rules.yaml
  common/hyperscaler/rules/attribute.go
  common/hyperscaler/rules/config.go
  common/hyperscaler/rules/config_test.go
  common/hyperscaler/rules/definitions.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/matching_result.go
  common/hyperscaler/rules/parser.go
  common/hyperscaler/rules/parser_test.go
  common/hyperscaler/rules/parsing_result.go
  common/hyperscaler/rules/parsing_results.go
  common/hyperscaler/rules/printer.go
  common/hyperscaler/rules/rule.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
  common/hyperscaler/rules/signature_set.go
  common/hyperscaler/rules/signature_set_mirrored_test.go
  common/hyperscaler/rules/simple_parser.go
  common/hyperscaler/rules/sorter.go
  common/hyperscaler/rules/utils.go
  go.mod
  go.sum
Labels: lgtm, size/XXL, kind/enhancement

#1804 Populate additionalOIDC field during provisioning and update
  cmd/broker/broker_suite_test.go
  cmd/broker/suite_test.go
  internal/process/input/input.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, kind/enhancement, cla: yes

#1823 Add permissions to token in create and promote workflow
  .github/workflows/create-and-promote-release.yaml
Labels: lgtm, size/XS, kind/enhancement

#1826 Use `ProviderValues` from operation
  cmd/broker/provisioning.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, kind/enhancement

#1828 Fail operation on failed runtime custom resource state
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
Labels: size/L, kind/enhancement

#1831 Fix provider in instance
  cmd/broker/provisioning.go
  internal/process/provisioning/init_provider_values_step.go
  internal/process/provisioning/init_provider_values_step_test.go
Labels: size/M, kind/bug

#1833 Drop support for the `us-west-1` region
  cmd/broker/provisioning_test.go
  internal/broker/plans.go
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/provider/aws_provider.go
Labels: size/S, kind/enhancement

#1771 Support for GPU machines
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
Labels: kind/feature, lgtm, size/XL, cla: yes

#1821 Hap parser pr hr
  cmd/parser/parse.go
  cmd/parser/parse_test.go
  cmd/parser/rules/test-cases.yaml
  common/hyperscaler/rules/attribute.go
  common/hyperscaler/rules/definitions.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/matching_result.go
  common/hyperscaler/rules/rule.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/simple_parser.go
  resources/keb/values.yaml
Labels: size/L, kind/enhancement

#1829 Logging the message when step is completed
  internal/process/staged_manager.go
Labels: size/XS, kind/enhancement

#1837 Cleaning after query optimization
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/globalaccounts.yaml
Labels: kind/enhancement

#1840 Fix building API server, kubeconfig URLs when kubeconfig secret is missing
  internal/broker/response_labels.go
  internal/broker/response_labels_test.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/handler.go
  internal/kubeconfig/handler_test.go
Labels: kind/enhancement

#1830 Postmigration cleanup in the update runtime step
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
Labels: size/S, kind/enhancement

#1847 HAP Rules creation extended
  common/hyperscaler/rules/config.go
  common/hyperscaler/rules/rules_service.go
Labels: kind/enhancement

#1848 `hap` CLI leaner
  Makefile
  cmd/parser/main.go
  cmd/parser/parse.go
  cmd/parser/parse_test.go
  cmd/parser/root.go
Labels: kind/enhancement

#1850 Bump x/oauth2 and x/net
  go.mod
  go.sum
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
  testing/e2e/skr-tester/go.mod
  testing/e2e/skr-tester/go.sum
  testing/e2e/skr/provisioning-service-test/go.mod
  testing/e2e/skr/provisioning-service-test/go.sum
Labels: kind/enhancement

#1852 Fix parser hap help
  cmd/parser/parse.go
Labels: kind/enhancement

#1843 Support multiple OIDC list in schema
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  internal/broker/automock/plan_validator.go
  internal/broker/automock/queue.go
  internal/broker/automock/region_reader.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/services_test.go
  internal/process/input/builder.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1853 Additional worker node pool name validation
  cmd/broker/provisioning_test.go
  go.mod
  go.sum
  internal/broker/automock/json_schema_validator.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/aws/update-free-aws-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/azure/update-azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/update-free-azure-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
  internal/broker/testdata/update-own-cluster-schema-additional-params.json
  internal/broker/testdata/update-own-cluster-schema.json
  internal/validator/validator.go
Labels: kind/bug

#1857 Missing case in switch handled
  internal/metricsv2/operations_stats.go
Labels: kind/bug

#1859 KimConfig not used any more
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/kim_config.go
  internal/broker/kim_config_test.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1861 Do not fail if HAP configuration is invalid
  cmd/broker/main.go
Labels: kind/bug

#1855 HAP verified by cmd/broker tests
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/old-sap-converged-cloud-region-mappings.yaml
  common/gardener/client.go
Labels: kind/enhancement

#1863 HAP rules service with all options on
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/parser/parse.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
  common/hyperscaler/rules/sorter.go
Labels: kind/enhancement

#1864 HAP parser sort fixed
  cmd/parser/rules/test-cases.yaml
  common/hyperscaler/rules/sorter.go
  common/hyperscaler/rules/sorter_test.go
Labels: kind/enhancement

#1867 [HAP] tests for uniqueness check
  cmd/parser/parse.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/parsing_results.go
  common/hyperscaler/rules/parsing_results_test.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
Labels: kind/enhancement

#1871 Fix kubeconfig builder to use additionalOIDC
  cmd/broker/main.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_envtest_test.go
  internal/broker/bindings/bindings_manager.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
Labels: kind/bug

#1875 Fix flags in kubeconfig builder
  cmd/broker/main.go
Labels: kind/bug

#1879 Subscription Service - `log.Fatalf` removed
  common/hyperscaler/rules/rules_service.go
Labels: kind/bug

#1880 Expand gardener seed CIDRs
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/networking/cidr.go
Labels: kind/bug

#1885 Use kcp rt status in skr-tester
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1872 Subscription Service - post-parse processing redesigned
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/matching_result.go
  common/hyperscaler/rules/parsing_results_test.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
  common/hyperscaler/rules/ruleset.go
  common/hyperscaler/rules/ruleset_test.go
Labels: kind/enhancement

#1886 Add events command in skr-tester
  testing/e2e/skr-tester/pkg/command/events.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1890 Subscription Service - missing accessors
  common/hyperscaler/rules/matching_result.go
  common/hyperscaler/rules/ruleset.go
Labels: kind/enhancement

#1870 Add `used-for-production` label to Kyma CR
  docs/contributor/07-20-subaccount-sync.md
  internal/kymacustomresource/kyma_cr_updater.go
  internal/kymacustomresource/kyma_cr_updater_test.go
  internal/subaccountsync/informer.go
  internal/subaccountsync/state_reconciler.go
  internal/subaccountsync/state_reconciler_test.go
  internal/subaccountsync/subaccount_sync_service.go
  internal/subaccountsync/testdata/events.json
  internal/syncqueues/model.go
  internal/syncqueues/priority_queue.go
Labels: kind/enhancement

#1891 Separate timeouts for create and update in `checkRuntimeResource` step
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1892 Update HAP rules doc to include label selector info
  docs/contributor/03-11-hap-rules.md
Labels: kind/enhancement

#1903 Wrap errors returned by KCP CLI in SKR-tester
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1894 Minimal `hap parse` CLI
  Makefile
  cmd/parser/main.go
  cmd/parser/parse.go
  cmd/parser/parse_test.go
  cmd/parser/rules/test-cases.yaml
  common/hyperscaler/rules/rules_service.go
Labels: kind/enhancement

#1906 3S - elementary error reporting
  cmd/broker/main.go
  cmd/parser/parse.go
  cmd/parser/parse_test.go
  common/hyperscaler/rules/rules_service.go
Labels: kind/enhancement

#1908 Fix check runtime resource timeout fix
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/parser/rules/rules-final.yaml
Labels: kind/bug

#1910 3S [HAP] clean-up
  common/hyperscaler/rules/attribute.go
  common/hyperscaler/rules/definitions.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/matching_result.go
  common/hyperscaler/rules/parsing_result.go
  common/hyperscaler/rules/parsing_results.go
  common/hyperscaler/rules/parsing_results_test.go
  common/hyperscaler/rules/printer.go
  common/hyperscaler/rules/rule.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
  common/hyperscaler/rules/ruleset.go
  common/hyperscaler/rules/signature_set.go
  common/hyperscaler/rules/signature_set_mirrored_test.go
  common/hyperscaler/rules/simple_parser.go
  common/hyperscaler/rules/sorter.go
  common/hyperscaler/rules/sorter_test.go
Labels: kind/enhancement

#1911 Increase SKR access timeout
  testing/e2e/skr-tester/pkg/command/assert.go
Labels: kind/enhancement

#1912 Add log info about resolved target secret
  internal/process/provisioning/resolve_subscription_secret.go
Labels: kind/enhancement

#1914 AWS G4dn machine type
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
Labels: kind/feature

#1916 README for `hap parse`
  cmd/parser/README.md
  cmd/parser/rules/rules-final.yaml
Labels: kind/enhancement
