Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-01, with the labels that each got.

#1603 SKR tester: wait for operation to finish
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/command/root.go
Labels: size/L, kind/enhancement, cla: yes

#1598 Metric for multiple kymas per subaccount
  internal/metricsv2/instances_collector.go
  internal/model.go
  internal/storage/dbmodel/operation.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/M, kind/enhancement, cla: yes

#1605 SKR tester: update machineType
  testing/e2e/skr-tester/pkg/broker/client.go
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/command/update.go
Labels: size/L, kind/enhancement, cla: yes

#1606 Revert @kubernetes/client-node bump
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
Labels: size/XXL, kind/enhancement, cla: yes

#1604 Logging Worker Execution Times Only if Limit Exceeded
  internal/process/queue.go
  internal/process/queue_test.go
Labels: size/M, kind/bug, cla: yes

#1610 SKR tester: adjust kcp login for CI/CD
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: size/L, kind/enhancement, cla: yes

#1613 SKR tester: OIDC and administrators update test
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1616 SKR tester: assert command
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1611 Add 64CPU machines
  internal/broker/plans.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1617 Additional worker node pools docs
  docs/user/03-10-service-description.md
  docs/user/04-40-additional-worker-node-pools.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1626 Fix GCP n2-standard-48 machine type display
  internal/broker/plans.go
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1629 Skip sha comapre step when no bump needed
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1631 Fix networking suffix validation message
  internal/broker/instance_create.go
Labels: kind/bug, size/XS, cla: yes

#1632 Ignore space change during bump check in promotion pipeline
  .github/workflows/promote-keb-to-dev.yaml
Labels: kind/bug, size/XS, cla: yes

#1633 SKR tester: networking test
  testing/e2e/skr-tester/pkg/broker/client.go
  testing/e2e/skr-tester/pkg/command/provision.go
Labels: size/M, kind/enhancement, cla: yes

#1635 Ignore all whitespaces in bump check during promotion
  .github/workflows/promote-keb-to-dev.yaml
Labels: kind/bug, size/XS, cla: yes

#1627 SKR tester: wait for suspension operation
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1639 Adjust promote workflow
  .github/workflows/promote-keb-to-dev.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1638 Fix availability zones for plans
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure.go
  internal/provider/azure_test.go
  internal/provider/gcp.go
  internal/provider/gcp_test.go
  internal/provider/model.go
  internal/provider/provider_values.go
  internal/provider/sap-converged-cloud.go
  internal/provider/sap-converged-cloud_test.go
Labels: size/L, kind/bug, lgtm, cla: yes

#1641 Fix head in promote
  .github/workflows/promote-keb-to-dev.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#1642 Fix -H using full path instead only of branch name in promote workflow
  .github/workflows/promote-keb-to-dev.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#1645 Fix for preview and more coverage for FailureTolerance
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/provider/provider_values.go
Labels: size/S, kind/bug, cla: yes

#1647 Correct Labels to lowerCamelCase in HAP Documentation
  docs/contributor/03-10-hyperscaler-account-pool.md
Labels: size/S, area/documentation, kind/enhancement, cla: yes

#1648 Send nil if controlplainFailureTolerance is empty
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/M, kind/bug, cla: yes

#1651 SKR tester: bindings
  testing/e2e/skr-tester/pkg/broker/client.go
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/binding.go
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/command/deprovision.go
  testing/e2e/skr-tester/pkg/command/provision.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/command/update.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1653 Time library updated
  go.mod
  go.sum
Labels: size/XS, kind/enhancement, cla: yes

#1654 Enable current configuration load on Preview
  internal/broker/plans.go
  internal/broker/plans_schema.go
Labels: size/M, kind/enhancement, cla: yes

#1656 Fixing annotation for KIM in `taskrun`
  common/orchestration/resolver.go
  common/orchestration/resolver_test.go
Labels: size/M, kind/bug, cla: yes

#1659 Additional worker node pools schema on Preview
  common/runtime/model.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
  internal/dto.go
Labels: size/XL, kind/enhancement, cla: yes

#1661 Refresh updateAt operation field to measure timeout
  internal/process/operation_manager.go
  internal/process/provisioning/check_runtime_step.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#1664 Switch to slog and unify errors in skr-tester
  testing/e2e/skr-tester/pkg/broker/client.go
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/binding.go
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/command/deprovision.go
  testing/e2e/skr-tester/pkg/command/provision.go
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/logger/logger.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1665 SKR tester: expand help section and add build workflow
  .github/workflows/build-skr-tester.yaml
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/binding.go
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/command/deprovision.go
  testing/e2e/skr-tester/pkg/command/provision.go
  testing/e2e/skr-tester/pkg/command/root.go
  testing/e2e/skr-tester/pkg/command/update.go
Labels: size/L, kind/enhancement, cla: yes

#1669 SKR-tester: custom updates
  testing/e2e/skr-tester/pkg/command/update.go
Labels: size/M, kind/enhancement, cla: yes

#1668 Introduce HA zones
  common/runtime/model.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans_schema.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1671 Disable changing HA zones setting
  common/runtime/model.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans_schema.go
Labels: size/S, kind/enhancement, cla: yes

#1674 Enhance error handling
  internal/broker/instance_create.go
  internal/broker/instance_update.go
Labels: size/S, kind/enhancement, cla: yes

#1677 SKR tester: migrate KEB endpoints test
  testing/e2e/skr-tester/pkg/command/assert.go
Labels: size/M, kind/enhancement, cla: yes

#1679 Add label app.kubernetes.io/instance
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1684 Proper retries
  internal/process/operation_manager.go
  internal/process/operation_manager_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1688 SKR tester: add documentation
  testing/e2e/skr-tester/README.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1691 Additional workers in RuntimeCR
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/update.go
  cmd/broker/update_test.go
  go.mod
  go.sum
  internal/dto.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
Labels: size/L, kind/enhancement, cla: yes

#1692 Documentation update regarding update of SM Credentials
  docs/contributor/07-10-runtime-reconciler.md
  docs/user/03-20-runtime-operations.md
Labels: area/documentation, lgtm, size/XS, kind/enhancement, cla: yes

#1695 Additional worker node pools feature flag
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1697 Remove HA zones for azure lite plan
  internal/broker/plans.go
  internal/broker/plans_test.go
Labels: size/M, kind/enhancement, cla: yes

#1702 Bump dependencies in e2e provisioning test
  testing/e2e/provisioning/Dockerfile
  testing/e2e/provisioning/go.mod
  testing/e2e/provisioning/go.sum
Labels: size/L, lgtm, kind/enhancement, cla: yes
