Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-04, with the labels that each got.

#1917 `skr-test` - more retries for delete secret test
  testing/e2e/skr-tester/pkg/command/assert.go
Labels: kind/enhancement

#1921 KCP CLI display licenseType and commercialModel
  common/runtime/model.go
  internal/runtime/converter.go
  internal/runtime/handler_test.go
Labels: kind/enhancement

#1922 Link to `hap CLI tool readme` in hap documentation
  docs/contributor/03-11-hap-rules.md
Labels: kind/enhancement

#1926 Add groupsPrefix to additionalOidc[0] in RuntimeCR
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
Labels: kind/enhancement

#1927 Check KEB pod status in chart install tests
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
Labels: kind/enhancement

#1929 Enhance KEB pod status check in chart install tests
  .github/workflows/run-keb-chart-install-tests-reusable.yaml
Labels: kind/enhancement

#1925 New configuration for Infrastructure Manager
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  internal/broker/broker.go
  internal/process/input/input.go
  internal/process/provisioning/create_resource_names_step_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/provisioning/init_provider_values_step.go
  internal/process/provisioning/init_provider_values_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1920 Add groupsPrefix to OIDC schema
  internal/broker/plans.go
  internal/broker/plans_schema.go
Labels: kind/enhancement

#1940 Avoid unnecessary error on response label creation
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/response_labels.go
Labels: kind/enhancement

#1942 Bump go to 1.24.2
  Makefile
  common/pagination/pagination.go
  common/runtime/model.go
  go.mod
  internal/broker/bind_create.go
  internal/broker/bind_get.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/error/errors_test.go
  internal/notification/client.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/operation_manager.go
  internal/process/steps/lifecycle_manager_kubeconfig.go
  internal/process/upgrade_cluster_operation.go
  internal/storage/driver/postsql/binding.go
  internal/storage/driver/postsql/events/events.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/orchestration.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/subaccount_state.go
Labels: kind/enhancement

#1918 Remove input builder
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  internal/broker/bind_create_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/response_labels.go
  internal/broker/response_labels_test.go
  internal/config/provider.go
  internal/kymacustomresource/resource_kind_provider.go
  internal/metricsv2/operations_result_test.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/input/automock/configuration_provider.go
  internal/process/input/automock/creator_for_plan.go
  internal/process/input/automock/hyperscaler_input_provider.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/input/input.go
  internal/process/input/input_test.go
  internal/process/steps/kyma_template.go
  internal/process/update/initialisation_step_test.go
  internal/provider/own.go
  internal/provider/provider_values.go
Labels: kind/enhancement

#1944 Do not abort - only log if config not in sync
  cmd/broker/main.go
Labels: kind/enhancement

#1948 Revert to panic again - in case of config inconsistency
  cmd/broker/main.go
Labels: kind/enhancement

#1953 Maintenance - update codeowners
  OWNERS_ALIASES
Labels: kind/enhancement

#1954 Provisioner related variables removed from deployment
  resources/keb/templates/deployment.yaml
Labels: kind/enhancement

#1956 Display the runtime configuration upon failure in SKR-tester
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1955 Removed redundant parameter
  cmd/broker/provisioning.go
  cmd/broker/update.go
  internal/process/update/initialisation_step.go
  internal/process/update/initialisation_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
Labels: kind/enhancement

#1958 Fix provider setting in the instance creation
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/runtime/converter.go
Labels: kind/bug

#1946 remove graphql deps
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  common/orchestration/dto.go
  common/runtime/model.go
  go.mod
  go.sum
  internal/archive/service.go
  internal/archive/service_test.go
  internal/broker/broker.go
  internal/broker/instance_update.go
  internal/error/errors.go
  internal/fixture/fixture.go
  internal/model.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
  internal/process/deprovisioning/clean_step.go
  internal/process/deprovisioning/clean_step_test.go
  internal/process/provisioning/automock/director_client.go
  internal/process/provisioning/automock/provisioner_input_creator.go
  internal/process/provisioning/base_provision_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/update/initialisation_step_test.go
  internal/provider/aws.go
  internal/provider/aws_provider.go
  internal/provider/aws_provider_test.go
  internal/provider/azure.go
  internal/provider/azure_provider.go
  internal/provider/azure_provider_test.go
  internal/provider/gcp.go
  internal/provider/gcp_provider.go
  internal/provider/gcp_provider_test.go
  internal/provider/own_cluster_provider.go
  internal/provider/sap-converged-cloud_provider.go
  internal/provider/sap-converged-cloud_provider_test.go
  internal/provisioning/automock/provisioner_input_creator.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/driver/memory/runtime_state.go
  internal/storage/driver/memory/runtime_state_test.go
  internal/storage/driver/postsql/runtime_state.go
  internal/storage/driver/postsql/runtimestate_test.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/storage.go
  internal/third_party/machinebox/graphql/LICENSE
  internal/third_party/machinebox/graphql/README.md
  internal/third_party/machinebox/graphql/graphql.go
  internal/third_party/machinebox/graphql/graphql_json_test.go
  internal/third_party/machinebox/graphql/graphql_multipart_test.go
Labels: kind/enhancement

#1960 Less params in deprovisioning - storage passed
  cmd/broker/deprovisioning.go
  internal/process/deprovisioning/archiving_step.go
  internal/process/deprovisioning/archiving_step_test.go
  internal/process/deprovisioning/btp_operator_cleanup.go
  internal/process/deprovisioning/btp_operator_cleanup_test.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step.go
  internal/process/deprovisioning/check_runtime_resource_deletion_step_test.go
  internal/process/deprovisioning/clean_step.go
  internal/process/deprovisioning/clean_step_test.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_kyma_resource_step_test.go
  internal/process/deprovisioning/delete_runtime_resource_step.go
  internal/process/deprovisioning/delete_runtime_resource_step_test.go
  internal/process/deprovisioning/edp_deregistration.go
  internal/process/deprovisioning/edp_deregistration_test.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/init_test.go
  internal/process/deprovisioning/release_subscription_step.go
  internal/process/deprovisioning/release_subscription_step_test.go
  internal/process/deprovisioning/remove_instance_step.go
  internal/process/deprovisioning/remove_instance_step_test.go
Labels: kind/enhancement

#1865 Handle object and list type OIDC input param, add requiredClaims support
  cmd/broker/broker_suite_test.go
  cmd/broker/get_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update.go
  cmd/broker/update_test.go
  common/runtime/model.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_envtest_test.go
  internal/broker/bindings/bindings_manager.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans_schema.go
  internal/broker/utils.go
  internal/dto.go
  internal/fixture/fixture.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
  internal/process/infrastructure_manager/infrastructure_manager.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  resources/keb/values.yaml
Labels: kind/feature

#1936 Enhance kubeconfig to display all OIDC contexts
  cmd/broker/main.go
  internal/broker/bind_create.go
  internal/broker/bind_create_test.go
  internal/broker/bind_envtest_test.go
  internal/broker/bindings/bindings_manager.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
  internal/kubeconfig/kubeconfig.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1971 Remove feature flags from deployment
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1972 Remaining provisioner settings removed from deployment
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#1963 Remove orchestration code
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  common/orchestration/automock/runtime_resolver.go
  common/orchestration/automock/strategy.go
  common/orchestration/client.go
  common/orchestration/client_test.go
  common/orchestration/dto.go
  common/orchestration/ext.go
  common/orchestration/resolver.go
  common/orchestration/resolver_test.go
  common/orchestration/runtime_lister_mock.go
  common/orchestration/strategies/parallel.go
  common/orchestration/strategies/parallel_test.go
  common/runtime/model.go
  internal/broker/instance_last_operation.go
  internal/broker/instance_last_operation_test.go
  internal/expiration/handler.go
  internal/fixture/fixture.go
  internal/kubeconfig/handler.go
  internal/kubeconfig/handler_test.go
  internal/model.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/init.go
  internal/process/deprovisioning/init_test.go
  internal/process/operation_manager.go
  internal/process/provisioning/start_step.go
  internal/process/provisioning/start_step_test.go
  internal/process/update/initialisation_step.go
  internal/process/update/initialisation_step_test.go
  internal/process/upgrade_cluster_operation.go
  internal/runtime/converter.go
  internal/runtime/converter_test.go
  internal/runtime/handler.go
  internal/storage/automock/operations.go
  internal/storage/dbmodel/operation.go
  internal/storage/dbmodel/orchestration.go
  internal/storage/dbmodel/orchestration_test.go
  internal/storage/driver/memory/operation.go
  internal/storage/driver/memory/orchestration.go
  internal/storage/driver/postsql/binding_test.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/driver/postsql/orchestration.go
  internal/storage/driver/postsql/orchestration_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/init.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  internal/storage/storage.go
  internal/suspension/handler.go
  internal/suspension/handler_test.go
Labels: kind/enhancement

#1973 Add ID types to logs
  internal/broker/bind_create.go
  internal/broker/bind_delete.go
  internal/broker/bind_get.go
  internal/broker/labeler.go
  internal/btpmanager/credentials/manager.go
  internal/globalaccounts/globalaccounts.go
  internal/process/provisioning/edp_registration.go
  internal/process/staged_manager.go
  internal/runtime/handler.go
  internal/storage/driver/postsql/events/events.go
  internal/storage/storage.go
  testing/e2e/provisioning/pkg/client/broker/broker_client.go
  testing/e2e/provisioning/pkg/client/runtime/runtime_client.go
Labels: kind/enhancement

#1969 Add multipleOIDC update to skr-tester
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1970 Parsing errors decorated with rule number [Subscription Secret Service]
  common/hyperscaler/rules/attribute.go
  common/hyperscaler/rules/definitions.go
  common/hyperscaler/rules/match_test.go
  common/hyperscaler/rules/rule.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/simple_parser.go
Labels: kind/enhancement

#1977 Show default OIDC values as first element of OIDC list
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/services.go
  internal/broker/services_test.go
Labels: kind/enhancement

#1974 Dropping obsolete tables
  internal/storage/dbmodel/runtime_state.go
  internal/storage/ext.go
  internal/storage/postsql/init.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  resources/keb/migrations/202504141000_drop_orchestrations.down.sql
  resources/keb/migrations/202504141000_drop_orchestrations.up.sql
  resources/keb/migrations/202504141100_drop_runtime_states.down.sql
  resources/keb/migrations/202504141100_drop_runtime_states.up.sql
Labels: kind/enhancement

#1975 Display runtime-config in SKR-tester
  testing/e2e/skr-tester/pkg/command/check_operation.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: kind/enhancement

#1988 Add missing property in update oidc in skr-tester
  testing/e2e/skr-tester/pkg/command/update.go
Labels: kind/enhancement

#1990 internal/error cleanup after provisioner removal
  internal/error/errors.go
  internal/process/operation_manager_test.go
Labels: kind/enhancement

#1983 KEB running in k3d
  Makefile
  docs/contributor/01-05-local-installation.md
  resources/installation/crd/secret-binding.yaml
  resources/installation/crd/shoot.yaml
  resources/installation/secretbindings/aws-secret-binding.yaml
  resources/installation/secretbindings/azure-secret-binding.yaml
  resources/installation/secretbindings/gcp-secret-binding.yaml
  resources/installation/secrets/aws-secret.yaml
  resources/installation/secrets/azure-secret.yaml
  resources/installation/secrets/gcp-secret.yaml
  resources/keb/values.yaml
  scripts/installation.sh
  scripts/set_kyma_state.sh
  scripts/set_runtime_state.sh
Labels: kind/enhancement

#1998 Extend regions supporting machine with zone mapping
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/regions-supporting-machine.yaml
  cmd/broker/update.go
  cmd/broker/update_test.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  internal/regionssupportingmachine/regions_supporting_machine.go
  internal/regionssupportingmachine/regions_supporting_machine_test.go
  internal/regionssupportingmachine/test/regions-supporting-machine-with-zones.yaml
  internal/workers/provider.go
  internal/workers/provider_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement
