Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-02, with the labels that each got.

#1705 Fix HAP step retries
  internal/process/provisioning/resolve_creds.go
Labels: size/M, kind/bug, cla: yes

#1708 Assert workers and additional workers on `runtimes` endpoint
  cmd/broker/provisioning_test.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1712 More logs to Discover Flakiness
  internal/btpmanager/credentials/manager.go
  testing/e2e/skr/skr-test/btp-manager-secret/index.js
Labels: size/XS, kind/enhancement, cla: yes

#1715 Step passed explicitly to make it thread-safe
  internal/process/operation_manager.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1716 Bump golang version to 1.23.6
  go.mod
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1721 Additional worker node pools E2E test
  testing/e2e/skr-tester/pkg/command/assert.go
  testing/e2e/skr-tester/pkg/command/update.go
  testing/e2e/skr-tester/pkg/kcp/client.go
Labels: size/L, kind/enhancement, cla: yes

#1723 Add logs to skr-tester
  testing/e2e/skr-tester/pkg/command/update.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1724 Explicitly passed arguments
  internal/process/operation_manager.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1727 Revert "Bump jsonpath-plus and @kubernetes/client-node in /testing/e2e/skr"
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
Labels: kind/bug, lgtm, size/XXL, cla: yes

#1728 Add index on `operations` table
  internal/storage/driver/postsql/operation.go
  internal/storage/driver/postsql/operation_test.go
  internal/storage/ext.go
  resources/keb/migrations/202502111757_add_indexes.down.sql
  resources/keb/migrations/202502111757_add_indexes.up.sql
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1709 Remove provisioner logic cmd tests
  cmd/broker/binding_test.go
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning_suite_test.go
  cmd/broker/deprovisioning_test.go
  cmd/broker/expiration_test.go
  cmd/broker/last_operation_test.go
  cmd/broker/metrics_test.go
  cmd/broker/object_tracker.go
  cmd/broker/orchestration_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/storage_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  cmd/broker/upgrade_cluster_test.go
  internal/archive/archive.go
  internal/broker/instance_update.go
  internal/process/update/update_runtime_step.go
  internal/storage/driver/postsql/instance.go
Labels: size/XXL, kind/enhancement, cla: yes

#1644 Hap Rule Configs Wiring
  internal/process/provisioning/resolve_creds.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/S, kind/enhancement, cla: yes

#1731 Assertion uncommented
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
Labels: size/M, kind/cleanup, kind/enhancement, cla: yes

#1732 Regions supporting machine
  cmd/broker/main.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/regions-supporting-machine.yaml
  docs/contributor/03-50-regions-supporting-machine.md
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/regionssupportingmachine/regions_supporting_machine.go
  internal/regionssupportingmachine/regions_supporting_machine_test.go
  internal/regionssupportingmachine/test/regions-supporting-machine.yaml
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: area/documentation, lgtm, size/XL, kind/enhancement, cla: yes

#1736 Instances table contains last operation id to speed up listinstances …
  cmd/broker/deprovisioning_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  internal/broker/instance_create.go
  internal/process/deprovisioning/init.go
  internal/process/provisioning/start_step.go
  internal/process/update/initialisation_step.go
  internal/storage/config.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
  internal/storage/storage.go
  resources/keb/migrations/202502121600_add_lastoperationid.down.sql
  resources/keb/migrations/202502121600_add_lastoperationid.up.sql
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, kind/enhancement, cla: yes

#1740 UseLastOperationID - log the value, implement new ListInstancesWithSubaccountStates
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/storage.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1742 Fix ListInstancesWithSubaccountStatesWithUseLastOperationID query
  internal/storage/postsql/read.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1745 Use total count for ListInstancesWithSubaccountStatesWithUseLastOpera…
  internal/storage/postsql/read.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#1743 Fix worker pool update params in last operation
  internal/model.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#1747 Add timeout for KEB calls in skr-tester
  testing/e2e/skr-tester/pkg/broker/client.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1748 Enhance error messages
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: size/L, kind/enhancement, cla: yes

#1749 Aliases for join queries corrected
  internal/storage/postsql/read.go
Labels: size/S, kind/bug, cla: yes

#1751 Corrected Logger Initialization
  internal/process/queue.go
  internal/process/queue_test.go
Labels: size/M, kind/bug, cla: yes

#1753 Add new regions for Azure, Azure lite, GCP plans
  internal/broker/plans.go
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema.json
Labels: size/M, kind/feature, cla: yes

#1754 Missing filters added
  internal/runtime/handler.go
  internal/storage/driver/memory/instance.go
  internal/storage/driver/postsql/instance.go
  internal/storage/ext.go
  internal/storage/postsql/read.go
Labels: size/L, kind/bug, cla: yes

#1759 Fix additionalWorkerNodePool name validation
  internal/broker/instance_create_test.go
  internal/broker/instance_update_test.go
  internal/broker/plans_schema.go
Labels: size/M, kind/bug, cla: yes

#1678 Update additional worker node pools docs
  docs/README.md
  docs/user/03-10-service-description.md
  docs/user/04-40-additional-worker-node-pools.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#1755 New versions of queries added - using `last_operation_id`
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/XXL, kind/enhancement, cla: yes

#1752 Support for compute-intensive machines
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/free-aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/free-aws-schema-additional-params.json
  internal/broker/testdata/aws/free-aws-schema-eu.json
  internal/broker/testdata/aws/free-aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/aws/update-free-aws-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/azure-trial-schema.json
  internal/broker/testdata/azure/free-azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/free-azure-schema-additional-params.json
  internal/broker/testdata/azure/free-azure-schema-eu.json
  internal/broker/testdata/azure/free-azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/azure/update-azure-trial-schema-additional-params.json
  internal/broker/testdata/azure/update-free-azure-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
Labels: kind/feature, lgtm, size/XXL, cla: yes

#1763 ERS stats query using `last_operation_id`
  internal/fixture/fixture.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1762 Add more OIDC validation
  common/runtime/model.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update_test.go
Labels: size/L, kind/enhancement, cla: yes

#1765 Remove obsolete feature flags
  cmd/broker/provisioning_test.go
  cmd/broker/update_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/own-cluster-schema-additional-params.json
  internal/broker/testdata/own-cluster-schema.json
  internal/broker/testdata/update-own-cluster-schema-additional-params.json
  internal/broker/testdata/update-own-cluster-schema.json
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: size/L, kind/enhancement, cla: yes

#1769 Alias changed to track query
  internal/storage/postsql/read.go
Labels: size/S, kind/enhancement, cla: yes

#1774 Migration to Checkmarx One
  scripts/create_scan_config.sh
  sec-scanners-config.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1775 Passing feature flag to jobs
  cmd/expirator/main.go
  cmd/runtimereconciler/main.go
  cmd/trialcleanup/main.go
  internal/storage/postsql/read.go
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
Labels: size/S, kind/enhancement, cla: yes

#1776 Remove redundant comment
  internal/runtime/handler.go
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1777 Passing feature flag to jobs - two remaining jobs
  cmd/deprovisionretrigger/main.go
  internal/globalaccounts/globalaccounts.go
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/globalaccounts.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1784 Reduce logging while introducing new queries based on `last_operation_id`
  internal/storage/postsql/read.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#1789 Add write permission to GitHub token
  .github/workflows/create-release.yaml
  .github/workflows/label-validator.yml
Labels: size/XS, kind/enhancement, cla: yes

#1790 Cleanup after migration to `last_operation_id` based queries
  cmd/broker/deprovisioning_test.go
  cmd/broker/update_test.go
  cmd/deprovisionretrigger/main.go
  cmd/expirator/main.go
  cmd/runtimereconciler/main.go
  cmd/trialcleanup/main.go
  internal/globalaccounts/globalaccounts.go
  internal/storage/config.go
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/instance_test.go
  internal/storage/driver/postsql/operation.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/storage.go
  resources/keb/values.yaml
Labels: lgtm, size/XXL, kind/enhancement, cla: yes

#1791 Cleaning after migration to `last_operation_id` queries - part 2
  internal/storage/driver/postsql/instance.go
  internal/storage/driver/postsql/operation.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  resources/keb/templates/deployment.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1792 Add id token write permission to release
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, kind/enhancement, cla: yes

#1794 Bump gardener 1.113.0
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#1797 Revert "Bump jsonpath-plus and @kubernetes/client-node in /testing/e2…
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
Labels: kind/bug, size/XXL, cla: yes

#1795 Add new build runtime plans
  cmd/broker/broker_suite_test.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  internal/broker/plans.go
  internal/process/input/builder.go
  internal/process/input/builder_test.go
  internal/process/provisioning/edp_registration.go
  internal/provider/provider_values.go
Labels: size/L, kind/feature, cla: yes

#1782 Hap Rules Wiring Part 2
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/testdata/hap-rules.yaml
  common/hyperscaler/rules/app_config_test.go
  common/hyperscaler/rules/model/config.go
  common/hyperscaler/rules/model/config_test.go
  common/hyperscaler/rules/model/utils.go
  common/hyperscaler/rules/rules_service.go
  common/hyperscaler/rules/rules_service_test.go
  go.mod
  go.sum
  internal/process/provisioning/resolve_creds.go
  internal/process/provisioning/resolve_creds_test.go
  resources/keb/templates/app-config.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1801 Remove Provisioner affected steps and Provisioner client
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/update.go
  cmd/broker/upgrade_cluster.go
  docs/user/03-20-runtime-operations.md
  go.mod
  go.sum
  internal/broker/bindings/bindings_manager.go
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
  internal/kubeconfig/handler.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step.go
  internal/process/deprovisioning/check_gardenercluster_deleted_step_test.go
  internal/process/deprovisioning/check_runtime_removal_step.go
  internal/process/deprovisioning/check_runtime_removal_step_test.go
  internal/process/deprovisioning/delete_gardener_cluster.go
  internal/process/deprovisioning/delete_gardenercluster_step_test.go
  internal/process/deprovisioning/remove_runtime.go
  internal/process/deprovisioning/remove_runtime_test.go
  internal/process/deprovisioning/utils.go
  internal/process/provisioning/check_runtime_step.go
  internal/process/provisioning/check_runtime_step_test.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_without_kyma_step.go
  internal/process/provisioning/create_runtime_without_kyma_test.go
  internal/process/provisioning/get_kubeconfig_step.go
  internal/process/provisioning/get_kubeconfig_test.go
  internal/process/steps/gardener_cluster.go
  internal/process/steps/gardener_cluster_test.go
  internal/process/update/check_step.go
  internal/process/update/check_step_test.go
  internal/process/update/upgrade_shoot_step.go
  internal/process/update/upgrade_shoot_step_test.go
  internal/process/upgrade_cluster/automock/creator_for_plan.go
  internal/process/upgrade_cluster/config.go
  internal/process/upgrade_cluster/initialisation.go
  internal/process/upgrade_cluster/initialisation_test.go
  internal/process/upgrade_cluster/log_skipping_upgrade.go
  internal/process/upgrade_cluster/manager.go
  internal/process/upgrade_cluster/manager_test.go
  internal/process/upgrade_cluster/send_notification.go
  internal/process/upgrade_cluster/send_notification_test.go
  internal/process/upgrade_cluster/upgrade_cluster_step.go
  internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  internal/provisioner/automock/client.go
  internal/provisioner/client.go
  internal/provisioner/client_test.go
  internal/provisioner/fake_client.go
  internal/provisioner/graphqlizer.go
  internal/provisioner/graphqlizer_test.go
  internal/provisioner/query.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
Labels: area/documentation, lgtm, size/XXL, area/control-plane, kind/enhancement, cla: yes

#1806 Retries in `CreateRuntimeResource` step
  cmd/broker/provisioning.go
  go.mod
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#1808 Delete old NodeJS SKR tests
  .github/workflows/run-eslint.yaml
  docs/README.md
  docs/contributor/04-10-workflows.md
  docs/contributor/05-10-e2e_tests.md
  testing/e2e/skr/.eslintrc.json
  testing/e2e/skr/.gitignore
  testing/e2e/skr/Makefile
  testing/e2e/skr/gardener/client.js
  testing/e2e/skr/gardener/index.js
  testing/e2e/skr/kcp/client.js
  testing/e2e/skr/keb-endpoints-test/.env.template
  testing/e2e/skr/keb-endpoints-test/index.js
  testing/e2e/skr/kyma-environment-broker/client.js
  testing/e2e/skr/kyma-environment-broker/helpers.js
  testing/e2e/skr/kyma-environment-broker/index.js
  testing/e2e/skr/lib/oauth.js
  testing/e2e/skr/mocha-reporter-config.json
  testing/e2e/skr/package-lock.json
  testing/e2e/skr/package.json
  testing/e2e/skr/skr-aws-upgrade-integration/.env.template
  testing/e2e/skr/skr-aws-upgrade-integration/index.js
  testing/e2e/skr/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  testing/e2e/skr/skr-binding-test/index.js
  testing/e2e/skr/skr-networking-test/.env.template
  testing/e2e/skr/skr-networking-test/index.js
  testing/e2e/skr/skr-test/.env.template
  testing/e2e/skr/skr-test/btp-manager-secret/index.js
  testing/e2e/skr/skr-test/deprovision-skr.js
  testing/e2e/skr/skr-test/helpers.js
  testing/e2e/skr/skr-test/index.js
  testing/e2e/skr/skr-test/machine-type/index.js
  testing/e2e/skr/skr-test/oidc/index.js
  testing/e2e/skr/skr-test/provision-skr.js
  testing/e2e/skr/skr-test/provision/deprovision-skr.js
  testing/e2e/skr/skr-test/provision/provision-skr.js
  testing/e2e/skr/skr-test/test.js
  testing/e2e/skr/smctl/helpers.js
  testing/e2e/skr/trial-suspension-test/helpers.js
  testing/e2e/skr/trial-suspension-test/test.js
  testing/e2e/skr/utils/index.js
Labels: area/documentation, lgtm, size/XXL, kind/enhancement, cla: yes

#1807 Retries in `CheckRuntimeResource` step
  cmd/broker/provisioning.go
  cmd/broker/update.go
  internal/model.go
  internal/process/steps/runtime_resource.go
  internal/process/steps/runtime_resource_test.go
Labels: size/M, kind/enhancement, cla: yes
