Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-07, with the labels that each got.

#2161 KCP cli shows actions
  cmd/broker/update_test.go
  common/runtime/model.go
  internal/broker/instance_update.go
  internal/model.go
  internal/runtime/handler.go
  internal/runtime/handler_test.go
  internal/storage/driver/memory/action.go
  internal/storage/driver/postsql/action.go
  internal/storage/driver/postsql/action_test.go
  internal/storage/ext.go
  internal/storage/postsql/factory.go
  internal/storage/postsql/read.go
  internal/storage/postsql/write.go
Labels: kind/enhancement

#2166 Enhance quota limit check
  docs/contributor/02-30-keb-configuration.md
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/quota/client.go
  internal/quota/client_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2170 Check quota limit during update
  cmd/broker/main.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
Labels: kind/enhancement

#2171 Plan updates - docs
  docs/README.md
  docs/contributor/03-80-plan-updates.md
Labels: area/documentation, kind/enhancement

#2176 Optional cis secret
  internal/quota/client.go
  resources/keb/templates/deployment.yaml
Labels: kind/enhancement

#2191 fix plan updates docs
  docs/contributor/03-80-plan-updates.md
Labels: documentation, kind/enhancement

#2192 Fix panic when updating an empty oidc list
  cmd/broker/update_test.go
  common/runtime/model.go
  internal/broker/instance_update.go
Labels: kind/bug

#2185 Document deployments, jobs, cronjobs
  docs/contributor/02-30-keb-configuration.md
  docs/contributor/06-30-subaccount-cleanup-cronjob.md
  docs/contributor/06-40-trial-free-cleanup-cronjobs.md
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
  docs/contributor/06-60-archiver-job.md
  docs/contributor/06-70-service-binding-cleanup-cronjob.md
  docs/contributor/07-10-runtime-reconciler.md
  docs/contributor/07-20-subaccount-sync.md
  docs/contributor/07-30-schema-migrator.md
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/globalaccounts.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/service-binding-cleanup-job.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
  scripts/python/generate_env_docs.py
Labels: kind/enhancement

#1979 Update OIDC documentation with OIDC list
  docs/user/04-10-custom-oidc-configuration.md
Labels: documentation, area/documentation, kind/enhancement

#2198 Add Plan name to not allowed plan update message
  cmd/broker/update_test.go
  internal/broker/instance_update.go
Labels: kind/enhancement

#2208 Switch from Provisioning to Entitlements Service
  docs/contributor/02-30-keb-configuration.md
  docs/contributor/02-50-external-validations.md
  internal/quota/client.go
  internal/quota/client_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/templates/secrets.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2214 Revert "Change kubeconfig context names (#2211)"
  internal/kubeconfig/builder.go
  internal/kubeconfig/builder_test.go
Labels: kind/enhancement

#2218 Renaming auxiliary functions related internal/external license type
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/dto.go
  internal/process/provisioning/create_runtime_resource_step.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/steps/lifecycle_manager.go
  internal/process/update/update_runtime_step.go
Labels: kind/enhancement

#2210 Document doc gen workflow
  docs/contributor/04-10-workflows.md
  scripts/python/generate_env_docs.py
Labels: kind/enhancement

#2219 Change jobs restart policy to onFailure
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/service-binding-cleanup-job.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  utils/archiver/kyma-environment-broker-archiver.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: kind/enhancement

#2221 Actions docs
  docs/README.md
  docs/contributor/03-75-subaccount-movement.md
  docs/contributor/03-80-plan-updates.md
  docs/contributor/03-90-actions-recording.md
Labels: kind/enhancement

#2226 Add CIS entitlements to VSO secrets
  resources/keb/values.yaml
Labels: kind/enhancement

#2231 Don't show default oidc on update
  internal/broker/plans_schema.go
Labels: kind/bug

#2232 Better OIDC description in schema
  internal/broker/plans_schema.go
Labels: kind/enhancement

#2239 Update platform provider mappings
  internal/middleware/provider.go
Labels: kind/enhancement

#2240 Adjust sec file generation scripts
  scripts/create_scan_config.sh
Labels: kind/enhancement
