Repository kyma-project/kyma-environment-broker, pull requests merged in 2025-05, with the labels that each got.

#2003 Disable machine type update
  common/runtime/model.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2011 Add ingress filtering support to provision and update commands in skr…
  testing/e2e/skr-tester/pkg/command/provision.go
  testing/e2e/skr-tester/pkg/command/update.go
Labels: kind/enhancement

#2013 Ingress filtering - `Contains` invocation fixed
  cmd/broker/main.go
  internal/broker/broker.go
  internal/broker/broker_test.go
  internal/broker/instance_create.go
  internal/broker/plans.go
  internal/broker/services.go
Labels: kind/enhancement

#2010 Ingress Filtering support - documentation update
  docs/contributor/02-30-keb-configuration.md
  docs/contributor/04-10-workflows.md
  docs/user/04-50-ingress-filtering.md
  resources/keb/values.yaml
Labels: documentation, kind/feature, area/documentation

#2017 Remove deprecated ResolveCredentials step
  cmd/broker/get_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  cmd/broker/update_test.go
  internal/process/provisioning/resolve_creds.go
  internal/process/provisioning/resolve_creds_test.go
  internal/process/provisioning/resolve_subscription_secret_label_selector_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2019 Allow AutoscalerMin zero value for non-HA Additional Worker Node Pools
  common/runtime/model.go
  docs/user/04-40-additional-worker-node-pools.md
  internal/broker/instance_create_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/testdata/aws/aws-schema-additional-params-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params-ingress-eu.json
  internal/broker/testdata/aws/aws-schema-additional-params-ingress.json
  internal/broker/testdata/aws/aws-schema-additional-params.json
  internal/broker/testdata/aws/aws-schema-eu.json
  internal/broker/testdata/aws/aws-schema.json
  internal/broker/testdata/aws/update-aws-schema-additional-params-ingress.json
  internal/broker/testdata/aws/update-aws-schema-additional-params.json
  internal/broker/testdata/aws/update-aws-schema.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced-ingress.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-ingress-eu.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-ingress.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced-ingress.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/azure-lite-schema-eu-reduced.json
  internal/broker/testdata/azure/azure-lite-schema-eu.json
  internal/broker/testdata/azure/azure-lite-schema-reduced.json
  internal/broker/testdata/azure/azure-lite-schema.json
  internal/broker/testdata/azure/azure-schema-additional-params-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params-ingress-eu.json
  internal/broker/testdata/azure/azure-schema-additional-params-ingress.json
  internal/broker/testdata/azure/azure-schema-additional-params.json
  internal/broker/testdata/azure/azure-schema-eu.json
  internal/broker/testdata/azure/azure-schema.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-ingress.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced-ingress.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-lite-schema-reduced.json
  internal/broker/testdata/azure/update-azure-lite-schema.json
  internal/broker/testdata/azure/update-azure-schema-additional-params-ingress.json
  internal/broker/testdata/azure/update-azure-schema-additional-params.json
  internal/broker/testdata/azure/update-azure-schema.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads-ingress.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema-additional-params-ingress.json
  internal/broker/testdata/gcp/gcp-schema-additional-params.json
  internal/broker/testdata/gcp/gcp-schema-assured-workloads.json
  internal/broker/testdata/gcp/gcp-schema.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params-ingress.json
  internal/broker/testdata/gcp/update-gcp-schema-additional-params.json
  internal/broker/testdata/gcp/update-gcp-schema.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params-ingress.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params-ingress.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema-additional-params.json
  internal/broker/testdata/sap-converged-cloud/update-sap-converged-cloud-schema.json
Labels: kind/enhancement

#2023 Sorted services
  internal/broker/services.go
Labels: kind/enhancement

#2028 Remove notifications package and kymaResourceDeletionTimeout
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/notification/builder.go
  internal/notification/bundle.go
  internal/notification/bundle_test.go
  internal/notification/client.go
  internal/notification/client_test.go
  internal/notification/fake_client.go
  internal/notification/mocks/Bundle.go
  internal/notification/mocks/BundleBuilder.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2029 Sort envs in templates
  .github/workflows/run-keb-chart-integration-tests-reusable.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/templates/deprovision-retrigger-job.yaml
  resources/keb/templates/free-cleanup-job.yaml
  resources/keb/templates/globalaccounts.yaml
  resources/keb/templates/keb-db-job.yaml
  resources/keb/templates/migrator-job.yaml
  resources/keb/templates/runtime-reconciler-deployment.yaml
  resources/keb/templates/service-binding-cleanup-job.yaml
  resources/keb/templates/subaccount-cleanup-job.yaml
  resources/keb/templates/subaccount-sync-deployment.yaml
  resources/keb/templates/trial-cleanup-job.yaml
  resources/keb/values.yaml
  scripts/check_env_alphabetical_order.sh
Labels: kind/enhancement

#2031 Describe Additional Worker Node Pool Autoscaler
  docs/user/04-40-additional-worker-node-pools.md
Labels: documentation, area/documentation, kind/enhancement

#2015 Monitor additional properties
  cmd/broker/main.go
  internal/additionalproperties/handler.go
  internal/additionalproperties/handler_test.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  resources/keb/templates/additional-properties-pvc.yaml
  resources/keb/templates/authorization-policy.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2034 Remove `zoneMapping` and `disableMachineTypeUpdate` feature flags
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_schema.go
  internal/broker/plans_test.go
  internal/broker/services.go
  internal/regionssupportingmachine/regions_supporting_machine.go
  internal/regionssupportingmachine/regions_supporting_machine_test.go
  internal/regionssupportingmachine/test/regions-supporting-machine-with-zones.yaml
  internal/regionssupportingmachine/test/regions-supporting-machine.yaml
  internal/workers/provider.go
  internal/workers/provider_test.go
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2022 Regions configurable
  .gitignore
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/provisioning_test.go
  cmd/broker/schema_test.go
  cmd/broker/suite_test.go
  cmd/broker/testdata/old-sap-converged-cloud-region-mappings.yaml
  cmd/broker/testdata/plans.yaml
  cmd/broker/testdata/providers.yaml
  cmd/broker/update.go
  cmd/broker/update_test.go
  internal/broker/converged_region_provider.go
  internal/broker/converged_region_provider_test.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/broker/instance_update.go
  internal/broker/instance_update_test.go
  internal/broker/plans.go
  internal/broker/plans_test.go
  internal/broker/schemas.go
  internal/broker/schemas_test.go
  internal/broker/services.go
  internal/broker/services_test.go
  internal/broker/testdata/plans.yaml
  internal/broker/testdata/providers.yaml
  internal/broker/testdata/sap-converged-cloud/sap-converged-cloud-schema-additional-params-ingress.json
  internal/model.go
  internal/process/provisioning/create_runtime_resource_step_test.go
  internal/process/provisioning/init_provider_values_step.go
  internal/process/provisioning/init_provider_values_step_test.go
  internal/process/update/update_runtime_step.go
  internal/process/update/update_runtime_step_test.go
  internal/provider/aws.go
  internal/provider/aws_test.go
  internal/provider/azure.go
  internal/provider/azure_test.go
  internal/provider/configuration/plan.go
  internal/provider/configuration/plan_test.go
  internal/provider/configuration/provider.go
  internal/provider/configuration/provider_test.go
  internal/provider/gcp.go
  internal/provider/gcp_test.go
  internal/provider/provider_values.go
  internal/provider/sap-converged-cloud.go
  internal/provider/sap-converged-cloud_test.go
  internal/provider/zones.go
  internal/provider/zones_test.go
  resources/keb/templates/app-config.yaml
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2038 Use supported linux image
  resources/keb/templates/deployment.yaml
Labels: kind/enhancement

#2037 Reorganize KEB configs
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/suite_test.go
  internal/broker/broker.go
  resources/keb/templates/deployment.yaml
  resources/keb/templates/profiler-pvc.yaml
  resources/keb/values.yaml
Labels: kind/enhancement

#2047 Remove disable machine type update feature flag
  resources/keb/values.yaml
Labels: kind/enhancement

#2048 Fix additional worker node pool autoscaler validation messages
  common/runtime/model.go
Labels: kind/enhancement

#2050 Move default plans provider conf
  resources/keb/values.yaml
  scripts/installation.sh
  scripts/values.yaml
Labels: kind/enhancement

#2027 Document KEB values.yaml
  .github/workflows/run-verify.yaml
  docs/contributor/02-30-keb-configuration.md
  resources/keb/templates/deployment.yaml
  resources/keb/values.yaml
  scripts/python/generate_env_docs.py
Labels: kind/enhancement

#2045 Conf regions docs
  docs/README.md
  docs/contributor/03-60-regions-configuration.md
Labels: documentation, area/documentation, kind/enhancement

#2057 'ingressFiltering' - additional test case
  cmd/broker/provisioning_test.go
Labels: kind/enhancement

#2060 `ingressFiltering` - provisioning parameters updated during update operation
  cmd/broker/update_test.go
  internal/broker/instance_update.go
  internal/fixture/fixture.go
Labels: kind/bug

#2055 General configuration provider for the broker
  cmd/broker/broker_suite_test.go
  cmd/broker/deprovisioning.go
  cmd/broker/main.go
  cmd/broker/provisioning.go
  cmd/broker/suite_test.go
  cmd/subaccountsync/main.go
  internal/config/converter.go
  internal/config/converter_test.go
  internal/config/provider.go
  internal/config/provider_test.go
  internal/config/reader.go
  internal/config/reader_test.go
  internal/config/testdata/keb-config-expected.yaml
  internal/config/validator.go
  internal/config/validator_test.go
  internal/kymacustomresource/resource_kind_provider.go
  internal/kymacustomresource/resource_kind_provider_test.go
  internal/process/deprovisioning/delete_kyma_resource_step.go
  internal/process/deprovisioning/delete_kyma_resource_step_test.go
  internal/process/steps/kyma_template.go
  internal/process/steps/kyma_template_test.go
Labels: kind/enhancement

#2063 Same region for Seed and Shoot validation
  cmd/broker/broker_suite_test.go
  cmd/broker/main.go
  cmd/broker/provisioning_test.go
  cmd/broker/suite_test.go
  docs/contributor/02-30-keb-configuration.md
  internal/broker/broker.go
  internal/broker/instance_create.go
  internal/broker/instance_create_input_params_test.go
  internal/broker/instance_create_test.go
  internal/broker/instance_get_test.go
  internal/config/fake.go
  internal/config/validator.go
  internal/model.go
  resources/keb/templates/deployment.yaml
Labels: kind/feature

#2065 Remove Provisioner from docs
  README.md
  docs/assets/hap-flow.drawio.svg
  docs/assets/target-keb-arch.drawio.svg
  docs/contributor/01-05-local-installation.md
  docs/contributor/03-10-hyperscaler-account-pool.md
  docs/contributor/03-20-eu-access.md
  docs/contributor/06-20-environments-cleanup-cronjob.md
  docs/contributor/06-40-trial-free-cleanup-cronjobs.md
  docs/contributor/06-50-deprovision-retrigger-cronjob.md
  docs/contributor/06-60-archiver-job.md
  docs/contributor/06-70-service-binding-cleanup-cronjob.md
  docs/contributor/07-10-runtime-reconciler.md
  docs/user/01-10-architecture.md
  docs/user/03-10-service-description.md
  docs/user/03-20-runtime-operations.md
Labels: kind/enhancement
